### PR TITLE
escape thing inside of code tag

### LINKED ISSUE #2322: Inline block code display issue
**What happened**:
[This post](https://dev.to/pandanoxes/lab-3-merging-and-resolving-code-conflict-3304) is not being rendered correctly. 
The post contains a single line code 
 `` `Closed by <short_name_issue_code>.` `` in telescope it is render `<code>Closed by <short_name_issue_code>.</short_name_issue_code></code>`
 
image

**What should have happened**:
It should render `` `Closed by <short_name_issue_code>.` ``

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS: Windows 10
- Browser: Chrome Version 94.0.4606.61

### PR DESCRIPTION
**Pull request by Kevan-Y**
## Issue This PR Addresses
Fixes #2322 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Removed `replace-entities.js ` to fix our current issue but will re-introduce  #1091.
Added a regex at end of https://github.com/Seneca-CDOT/telescope/blob/bce0b2106c59c33b712e9581c47f7bb8012f2720/src/backend/utils/html/syntax-highlight.js#L58 to turn `&amp;gt;` back to `&gt;`
## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
This is different than what I thought we were discussing.  I thought you were going to submit a PR to change the options we pass to the sanitizer so it escapes vs. deletes unknown tags.

I don't think running regexes on the HTML is a good idea.

**Comment by Kevan-Y** [comment]
> This is different than what I thought we were discussing. I thought you were going to submit a PR to change the options we pass to the sanitizer so it escapes vs. deletes unknown tags.
> 
> I don't think running regexes on the HTML is a good idea.

But adding the escape will convert tag like `<code><text></code>` to `<code><text></text></code>` or  `<code><text/></code>` to `<code><text></text></code>`

**Comment by humphd** [comment]
I want to understand the underlying problem here vs. fix one specific case.  Consider:

1. `<code><text></code>`
2. `<code>&lt;text&gt;</code>`

The example in 1. is not valid HTML5, only 2. is.  Why are we being dealing with invalid HTML in the first place?  Are we being sent it?  Or is our feed pipeline producing it somehow?

In the case of [your post](view-source:https://dev.to/pandanoxes/lab-3-merging-and-resolving-code-conflict-3304), I see that we get this: `<code>Closed by &lt;short_name_issue_code&gt;.</code>`

I think the underlying issue is the fact that the sanitizer is forcing entities to be decoded, see https://github.com/fb55/htmlparser2/issues/105.  Undoing this has some interesting security implications.

**Comment by manekenpix** [comment]
@Kevan-Y any updates?

**Comment by Grommers00** [comment]
If you can just rebase it onto master. So we can merge it should be good to go :).

**Comment by Grommers00** [comment]
If you can just rebase it onto master. So we can merge it should be good to go :).

**Comment by humphd** [comment]
OK, let's try this.  @Kevan-Y we'll open further issues to tweak it when we see what happens on staging.

**Pull request merged**
