### PR TITLE
Fix part of 2171 signup flow styles

### PR DESCRIPTION
**Pull request by Meneguini**
## Issue This PR Addresses
Part of #2171 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
This PR is fixing the most urgent problems related to the `SignUp` page styles.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by Meneguini** [comment]
@humphd  @PedroFonsecaDEV  @DukeManh

**Comment by humphd** [comment]
The first screen looks way better (login button has correct margins).  However, I can't test the rest.  @chrispinkney, can you delete me from Firebase?

Screen Shot 2021-04-20 at 4 49 49 PM

**Comment by humphd** [comment]
Screen Shot 2021-04-20 at 4 55 00 PM
Screen Shot 2021-04-20 at 4 55 08 PM
Screen Shot 2021-04-20 at 4 55 27 PM
Screen Shot 2021-04-20 at 4 55 40 PM
Screen Shot 2021-04-20 at 4 55 54 PM
Screen Shot 2021-04-20 at 4 56 06 PM
Screen Shot 2021-04-20 at 4 56 13 PM
Screen Shot 2021-04-20 at 4 56 18 PM
Screen Shot 2021-04-20 at 4 56 23 PM

**Review by humphd — APPROVED** [review]

**Comment by chrispinkney** [comment]
image

😄

**Review by PedroFonsecaDEV — APPROVED** [review]

**Review by HyperTHD — APPROVED** [review]

**Pull request merged**
