### PR TITLE
Fix #2563: Standardize package versions and use caret (^) for all packages

### LINKED ISSUE #2563: Standardize package versions across package.json files
In #2545, @menghif and I are debugging an issue in CI with versions and the lock file.  It led me to take a look at what packages/versions we have defined for `dependencies` and `devDependencies` in all of our `package.json` files (see below).

***tldr;***: we should standardize all of our packages, and probably start using `^` versions by default, since `pnpm` is going to introduce a lock file.  See my Analysis section below for what needs to be found/fixed.

## `devDependencies`

```sh
find . -name 'package.json' -not -path "./node_modules/*" -exec cat {} + | jq -s .[].devDependencies | sort
  "@babel/core": "7.14.3",
  "@babel/plugin-transform-runtime": "7.13.15",
  "@babel/preset-env": "7.13.15",
  "@babel/preset-react": "7.13.13",
  "@babel/preset-typescript": "7.16.0",
  "@firebase/rules-unit-testing": "^2.0.1",
  "@mdx-js/loader": "^1.6.22",
  "@mdx-js/mdx": "^1.6.22",
  "@testing-library/react": "^12.1.0",
  "@types/jest": "27.0.2",
  "@types/node": "^16.7.0",
  "@types/react": "^17.0.3",
  "@typescript-eslint/eslint-plugin": "4.17.0",
  "@typescript-eslint/parser": "4.17.0",
  "@vercel/node": "1.9.1",
  "babel-loader": "^8.2.2",
  "babel-preset-next": "1.4.0",
  "cross-env": "7.0.3",
  "del-cli": "^4.0.1",
  "env-cmd": "^10.1.0",
  "env-cmd": "^10.1.0",
  "env-cmd": "^10.1.0",
  "env-cmd": "^10.1.0",
  "eslint": "7.23.0",
  "eslint-config-airbnb": "18.2.1",
  "eslint-config-prettier": "8.1.0",
  "eslint-plugin-import": "2.25.3",
  "eslint-plugin-jest": "25.3.0",
  "eslint-plugin-jest-playwright": "0.2.1",
  "eslint-plugin-jsx-a11y": "6.4.1",
  "eslint-plugin-prettier": "3.4.0",
  "eslint-plugin-promise": "5.1.0",
  "eslint-plugin-react": "7.22.0",
  "eslint-plugin-react-hooks": "4.2.0",
  "fast-xml-parser": "3.19.0",
  "firebase-tools": "^9.9.0",
  "husky": "5.1.3",
  "jest": "27.3.1",
  "jest-fetch-mock": "3.0.3",
  "jest-playwright-preset": "1.7.0",
  "nock": "13.0.11",
  "nodemon": "^2.0.15"
  "nodemon": "^2.0.15"
  "nodemon": "^2.0.15"
  "nodemon": "^2.0.15"
  "nodemon": "^2.0.15"
  "nodemon": "^2.0.15"
  "nodemon": "^2.0.15",
  "npm-run-all": "4.1.5",
  "playwright": "1.11.0",
  "prettier": "2.2.1",
  "pretty-quick": "3.1.0",
  "run.env": "1.1.0",
  "supertest": "6.1.3",
  "supertest": "^6.1.3"
  "supertest": "^6.1.3"
  "terser-webpack-plugin": "^5.1.1",
  "ts-jest": "27.0.7"
  "typescript": "^4.3.5"
```

## Dependencies

```sh
find . -name 'package.json' -not -path "./node_modules/*" -exec cat {} + | jq -s .[].dependencies | sort
  "@bull-board/api": "3.6.0",
  "@bull-board/express": "3.7.0",
  "@elastic/elasticsearch": "7.11.0",
  "@elastic/elasticsearch": "^7.11.0",
  "@elastic/elasticsearch": "^7.12.0",
  "@elastic/elasticsearch-mock": "0.3.0",
  "@elastic/elasticsearch-mock": "^0.3.0",
  "@elastic/elasticsearch-mock": "^0.3.0",
  "@fontsource/pt-serif": "^4.2.2",
  "@fontsource/spartan": "^4.2.2",
  "@material-ui/core": "^4.12.3",
  "@material-ui/icons": "^4.11.2",
  "@next/mdx": "^12.0.4",
  "@octokit/webhooks": "^9.15.0",
  "@senecacdot/satellite": "^1.x",
  "@senecacdot/satellite": "^1.x",
  "@senecacdot/satellite": "^1.x",
  "@senecacdot/satellite": "^1.x",
  "@senecacdot/satellite": "^1.x",
  "@senecacdot/satellite": "^1.x",
  "@senecacdot/satellite": "^1.x",
  "@senecacdot/satellite": "^1.x",
  "@senecacdot/satellite": "^1.x",
  "@senecacdot/satellite": "^1.x",
  "@types/smoothscroll-polyfill": "^0.3.1",
  "@types/yup": "^0.29.11",
  "@wordpress/wordcount": "2.15.0",
  "babel-jest": "27.3.1",
  "bull": "3.20.1",
  "bull": "^3.22.0",
  "bull-board": "^2.1.3",
  "celebrate": "^15.0.0",
  "celebrate": "^15.0.0",
  "celebrate": "^15.0.0",
  "cheerio": "^1.0.0-rc.5",
  "clean-whitespace": "0.1.2",
  "connect-redis": "5.1.0",
  "connect-redis": "^6.0.0",
  "cors": "2.8.5",
  "date-fns": "2.19.0",
  "date-fns": "^2.24.0",
  "docker-compose": "0.23.6",
  "dotenv": "8.2.0",
  "dotenv": "^10.0.0",
  "dotenv": "^10.0.0",
  "entities": "2.2.0",
  "express": "4.17.1",
  "express": "^4.17.1",
  "express": "^4.17.1",
  "express-handlebars": "^5.3.4"
  "express-healthcheck": "0.1.0",
  "express-pino-logger": "6.0.0",
  "express-session": "1.17.1",
  "express-session": "^1.17.1",
  "express-validator": "6.10.0",
  "express-validator": "^6.10.0",
  "express-validator": "^6.9.2"
  "feed": "4.2.2",
  "firebase-admin": "^10.0.0",
  "formik": "^2.2.6",
  "got": "^11.8.1"
  "got": "^11.8.1",
  "helmet": "4.4.1",
  "highlight.js": "11.3.1",
  "highlight.js": "11.3.1",
  "http-link-header": "^1.0.3"
  "http-proxy-middleware": "1.0.6",
  "ioredis": "4.26.0",
  "ioredis": "^4.25.0",
  "ioredis-mock": "5.5.5",
  "ioredis-mock": "^5.4.1",
  "jsdom": "16.5.1",
  "jsdom": "^16.5.2",
  "jsdom": "^18.0.0",
  "jsdom": "^18.0.1",
  "jsonwebtoken": "^8.5.1",
  "jwt-decode": "^3.1.2",
  "merge-stream": "^2.0.0",
  "minimatch": "^3.0.4",
  "nanoid": "^3.1.22",
  "next": "^12.0.4",
  "next-compose-plugins": "^2.2.1",
  "next-pwa": "^5.4.1",
  "node-fetch": "2.6.1",
  "node-fetch": "^2.6.1"
  "normalize-url": "6.0.1",
  "normalize-url": "^6.0.1"
  "normalize-url": "^6.0.1",
  "opml-generator": "1.1.1",
  "passport": "0.4.1",
  "passport": "^0.5.0",
  "passport-saml": "3.1.2",
  "passport-saml": "^3.1.2"
  "pino": "7.3.0",
  "pino-elasticsearch": "6.2.0",
  "pino-pretty": "7.2.0",
  "pm2": "^5.1.1",
  "react": "^17.0.2",
  "react-dom": "^17.0.2",
  "react-icons": "^4.3.1",
  "react-transition-group": "^4.4.2",
  "react-use": "^17.2.1",
  "rss-parser": "3.12.0",
  "rss-parser": "^3.12.0"
  "sanitize-html": "2.3.2",
  "sass": "^1.43.5"
  "set-interval-async": "2.0.3",
  "sharp": "^0.29.3"
  "shelljs": "^0.8.4"
  "smoothscroll-polyfill": "^0.4.4",
  "stoppable": "1.1.0"
  "swr": "^1.0.0",
  "yup": "^0.32.9"
```

## Analysis

Looking at these, I notice that we are defining multiple versions of the same dependencies, sometimes with pinned versions, and sometimes with caret (`^`) versions, which will pull in newer versions if available:

```
  "supertest": "6.1.3",
  "supertest": "^6.1.3"

  "@elastic/elasticsearch": "7.11.0",
  "@elastic/elasticsearch": "^7.11.0",
  "@elastic/elasticsearch": "^7.12.0",

  "@elastic/elasticsearch-mock": "0.3.0",
  "@elastic/elasticsearch-mock": "^0.3.0",

  "bull": "3.20.1",
  "bull": "^3.22.0",

  "connect-redis": "5.1.0",
  "connect-redis": "^6.0.0",

  "date-fns": "2.19.0",
  "date-fns": "^2.24.0",

  "dotenv": "8.2.0",
  "dotenv": "^10.0.0",

  "express": "4.17.1",
  "express": "^4.17.1",

  "express-session": "1.17.1",
  "express-session": "^1.17.1",

  "express-validator": "6.10.0",
  "express-validator": "^6.10.0",
  "express-validator": "^6.9.2"

  "ioredis": "4.26.0",
  "ioredis": "^4.25.0",

  "ioredis-mock": "5.5.5",
  "ioredis-mock": "^5.4.1",

  "jsdom": "16.5.1",
  "jsdom": "^16.5.2",
  "jsdom": "^18.0.0",
  "jsdom": "^18.0.1",

  "node-fetch": "2.6.1",
  "node-fetch": "^2.6.1"

  "normalize-url": "6.0.1",
  "normalize-url": "^6.0.1"

  "passport": "0.4.1",
  "passport": "^0.5.0",

  "passport-saml": "3.1.2",
  "passport-saml": "^3.1.2"

  "rss-parser": "3.12.0",
  "rss-parser": "^3.12.0"
```

### PR DESCRIPTION
**Pull request by menghif**
## Issue This PR Addresses

Fixes #2563 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR standardizes our `package.json` files to have all repeating dependencies on the same version. It also changes all dependencies to use caret (^) versions since we are introducing a lock file in #2545.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — DISMISSED** [review]
The big question is, what will this do for pnpm?

**Review by LuigiZaccagnini — DISMISSED** [review]

**Comment by humphd** [comment]
@menghif please squash and rebase this.  I landed a prettier fix since you did this that might help with those other files.

**Comment by DukeManh** [comment]
Looks like the `prettier-check` has passed with prettier being exactly `v2.41`. When we use semver caret `^2.4.1` version, npm always installs newer minor/patch versions, which according to [this issue](https://github.com/prettier/prettier/issues/2201), don't guarantee the same format results.

**Comment by humphd** [comment]
This is going to suck to remember down the road when people go to update it, and we can't leave comments in package.json :(

**Review by humphd — APPROVED** [review]
@menghif do you want this to land before or after the pnpm stuff?

**Review by manekenpix — APPROVED** [review]

**Comment by menghif** [comment]
@humphd This can go after the pnpm PR

**Comment by humphd** [comment]
@menghif the pnpm changes are landed, let's get this rebased and tested again on CI so we can add it too.

**Comment by humphd** [comment]
Specifically, this will trigger an update to the lock file.

**Review by humphd — APPROVED** [review]

**Review by HyperTHD — APPROVED** [review]

**Review by LuigiZaccagnini — APPROVED** [review]

**Pull request merged**
