### PR TITLE
Remove showLastUpdate in Docusaurus

### LINKED ISSUE #3403: Falied to retrieve git history for files in Docusarus build
**What happened**:

When building the Docusaurus app we get many error messages about missing git history:

```
#22 157.8 [ERROR] Error: Failed to retrieve the git history for file "/docs/i18n/uk/docusaurus-plugin-content-docs/current/overview.md" with exit code 128: fatal: not a git repository (or any of the parent directories): .git
#22 157.8 
#22 157.9 [ERROR] Error: Failed to retrieve the git history for file "/docs/docs/architecture.md" with exit code 128: fatal: not a git repository (or any of the parent directories): .git
```
**What should have happened**:

No git history errors during the build

**How to reproduce it (as precise as possible)**:

- `pnpm services:start`

### PR DESCRIPTION
**Pull request by menghif**
## Issue This PR Addresses
Fixes #3403

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR removes `showLastUpdateAuthor` and `showLastUpdateTime` to fix Docusaurus build errors.

## Steps to test the PR

- `pnpm i`
- `pnpm services:start`

No errors during the Docusaurus build step:

```
#114 [telescope_api_nginx build-docs 4/4] RUN pnpm build
#114 45.06 ✔ Client: Compiled successfully in 42.70s
#114 47.85 ✔ Server: Compiled successfully in 45.40s
```

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by sirinoks** [comment]
Unless steps to reproduce are incorrect, this is not working for me:
image

I ran `pnpm services:start` in the root folder. I have also tried to do that in the docusaurus folder (`telescope/src/web/docusaurus`), but that didn't do anything at all.

**Comment by menghif** [comment]
> Unless steps to reproduce are incorrect, this is not working for me: image
> 
> I ran `pnpm services:start` in the root folder. I have also tried to do that in the docusaurus folder (`telescope/src/web/docusaurus`), but that didn't do anything at all.

I don't think that's related. Did you run `pnpm install`?

**Comment by sirinoks** [comment]
> I don't think that's related. Did you run `pnpm install`?

I did. I'm not sure what it's about either.

**Comment by sirinoks** [comment]
UPD: Can't test this due to docker windows stuff, will need other reviewers.

**Review by TDDR — APPROVED** [review]
Looks good to merge

**Review by JiaHua-Zou — APPROVED** [review]
Tested on my machine and it works!

**Pull request merged**
