### PR TITLE
Update muptiple dependencies

### PR DESCRIPTION
**Pull request by yuanLeeMidori**
## Issue This PR Addresses

Related to #1592 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR updates several dependencies (see the list below). They passed the `npm test` and didn't break our project. Please take a look and see if these updates break anything, if they do, please let me know, thanks!

```
* @elastic/elasticsearch
* @wordpress/wordcount
* bull
* connect-redis
* date-fns
* express-handlebars
* express-validator
* feed
* helmet
* http-proxy-middleware
* ioredis
* ioredis-mock
* normalize-url
* passport-saml
* pino
* pino-elasticsearch
* pino-pretty
* set-interval-async
* @typescript-eslint/eslint-plugin
* @typescript-eslint/parser
* @vercel/node
* eslint
* eslint-config-prettier
* eslint-plugin-prettier
* eslint-plugin-promise
* eslint-plugin-react
* jest
* nock
* prettier
* pretty-quick
```

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by cindyledev — APPROVED** [review]
This is great. Thanks :)

**Comment by cindyledev** [comment]
I noticed you didn't update any of the dependencies with major updates:
```
Package              Current  Wanted  Latest  Location
bull-board             0.9.0   0.9.0   1.2.0  @senecacdot/telescope
express-pino-logger    5.0.0   5.0.0   6.0.0  @senecacdot/telescope
highlight.js          10.4.1  10.4.1  10.6.0  @senecacdot/telescope
husky                  4.3.0   4.3.0   5.0.9  @senecacdot/telescope
sanitize-html         1.27.4  1.27.4   2.3.2  @senecacdot/telescope
supertest              4.0.2   4.0.2   6.1.3  @senecacdot/telescope
```

Probably needs more investigating whether or not they're compatible with Telescope.

**Comment by cindyledev** [comment]
Can I also bug you to update `telescope\src\frontend\next` dependencies in either this PR or another PR? :)
```
Package             Current    Wanted    Latest  Location
@material-ui/core    4.11.2    4.11.3    4.11.3  @senecacdot/telescope-frontend
@next/mdx            10.0.6    10.0.7    10.0.7  @senecacdot/telescope-frontend
@types/node        14.14.10  14.14.28  14.14.28  @senecacdot/telescope-frontend
@types/react        16.14.2   16.14.4    17.0.2  @senecacdot/telescope-frontend
next                 10.0.3    10.0.7    10.0.7  @senecacdot/telescope-frontend
react-use            15.3.8    15.3.8    17.1.1  @senecacdot/telescope-frontend
swr                   0.4.0     0.4.2     0.4.2  @senecacdot/telescope-frontend
typescript            4.1.2     4.1.5     4.1.5  @senecacdot/telescope-frontend
```

idk if we still care about Gatsby dependencies anymore but they're outdated too :P 
```
Package                           Current   Wanted          Latest  Location
@material-ui/core                  4.11.0   4.11.0          4.11.3  @senecacdot/telescope-frontend
@material-ui/icons                  4.9.1    4.9.1          4.11.2  @senecacdot/telescope-frontend
@material-ui/styles                4.10.0   4.10.0          4.11.3  @senecacdot/telescope-frontend
@svgr/webpack                       5.4.0    5.4.0           5.5.0  @senecacdot/telescope-frontend
@testing-library/jest-dom          5.11.6   5.11.6          5.11.9  @senecacdot/telescope-frontend
@testing-library/react             11.1.0   11.1.0          11.2.5  @senecacdot/telescope-frontend
babel-jest                         26.6.1   26.6.1          26.6.3  @senecacdot/telescope-frontend
babel-preset-gatsby                0.5.14   0.5.14          0.12.1  @senecacdot/telescope-frontend
gatsby                            2.24.85  2.24.85          2.32.3  @senecacdot/telescope-frontend
gatsby-image                       2.4.21   2.4.21          2.11.0  @senecacdot/telescope-frontend
gatsby-plugin-manifest             2.4.35   2.4.35          2.12.0  @senecacdot/telescope-frontend
gatsby-plugin-react-helmet         3.3.14   3.3.14          3.10.0  @senecacdot/telescope-frontend
gatsby-plugin-sharp                2.6.43   2.6.43          2.14.1  @senecacdot/telescope-frontend
gatsby-plugin-svgr                  2.0.2    2.0.2           2.1.0  @senecacdot/telescope-frontend
gatsby-source-filesystem           2.3.35   2.3.35          2.11.0  @senecacdot/telescope-frontend
gatsby-transformer-remark          2.8.46   2.8.46          2.16.0  @senecacdot/telescope-frontend
gatsby-transformer-sharp           2.5.19   2.5.19          2.12.0  @senecacdot/telescope-frontend
highlight.js                       10.4.1   10.4.1          10.6.0  @senecacdot/telescope-frontend
jest                               26.6.1   26.6.1          26.6.3  @senecacdot/telescope-frontend
react                             16.13.1  16.13.1          17.0.1  @senecacdot/telescope-frontend
react-dom                         16.13.1  16.13.1          17.0.1  @senecacdot/telescope-frontend
react-material-ui-form-validator    2.1.1    2.1.1           2.1.4  @senecacdot/telescope-frontend
react-swipeable-views-utils        0.13.9   0.13.9  0.14.0-alpha.0  @senecacdot/telescope-frontend
react-use                          15.3.4   15.3.4          17.1.1  @senecacdot/telescope-frontend
swr                                 0.3.6    0.3.6           0.4.2  @senecacdot/telescope-frontend
```

**Comment by HyperTHD** [comment]
> Can I also bug you to update `telescope\src\frontend\next` dependencies in either this PR or another PR? :)
> 
> ```
> Package             Current    Wanted    Latest  Location
> @material-ui/core    4.11.2    4.11.3    4.11.3  @senecacdot/telescope-frontend
> @next/mdx            10.0.6    10.0.7    10.0.7  @senecacdot/telescope-frontend
> @types/node        14.14.10  14.14.28  14.14.28  @senecacdot/telescope-frontend
> @types/react        16.14.2   16.14.4    17.0.2  @senecacdot/telescope-frontend
> next                 10.0.3    10.0.7    10.0.7  @senecacdot/telescope-frontend
> react-use            15.3.8    15.3.8    17.1.1  @senecacdot/telescope-frontend
> swr                   0.4.0     0.4.2     0.4.2  @senecacdot/telescope-frontend
> typescript            4.1.2     4.1.5     4.1.5  @senecacdot/telescope-frontend
> ```
> 
> idk if we still care about Gatsby dependencies anymore but they're outdated too :P
> 
> ```
> Package                           Current   Wanted          Latest  Location
> @material-ui/core                  4.11.0   4.11.0          4.11.3  @senecacdot/telescope-frontend
> @material-ui/icons                  4.9.1    4.9.1          4.11.2  @senecacdot/telescope-frontend
> @material-ui/styles                4.10.0   4.10.0          4.11.3  @senecacdot/telescope-frontend
> @svgr/webpack                       5.4.0    5.4.0           5.5.0  @senecacdot/telescope-frontend
> @testing-library/jest-dom          5.11.6   5.11.6          5.11.9  @senecacdot/telescope-frontend
> @testing-library/react             11.1.0   11.1.0          11.2.5  @senecacdot/telescope-frontend
> babel-jest                         26.6.1   26.6.1          26.6.3  @senecacdot/telescope-frontend
> babel-preset-gatsby                0.5.14   0.5.14          0.12.1  @senecacdot/telescope-frontend
> gatsby                            2.24.85  2.24.85          2.32.3  @senecacdot/telescope-frontend
> gatsby-image                       2.4.21   2.4.21          2.11.0  @senecacdot/telescope-frontend
> gatsby-plugin-manifest             2.4.35   2.4.35          2.12.0  @senecacdot/telescope-frontend
> gatsby-plugin-react-helmet         3.3.14   3.3.14          3.10.0  @senecacdot/telescope-frontend
> gatsby-plugin-sharp                2.6.43   2.6.43          2.14.1  @senecacdot/telescope-frontend
> gatsby-plugin-svgr                  2.0.2    2.0.2           2.1.0  @senecacdot/telescope-frontend
> gatsby-source-filesystem           2.3.35   2.3.35          2.11.0  @senecacdot/telescope-frontend
> gatsby-transformer-remark          2.8.46   2.8.46          2.16.0  @senecacdot/telescope-frontend
> gatsby-transformer-sharp           2.5.19   2.5.19          2.12.0  @senecacdot/telescope-frontend
> highlight.js                       10.4.1   10.4.1          10.6.0  @senecacdot/telescope-frontend
> jest                               26.6.1   26.6.1          26.6.3  @senecacdot/telescope-frontend
> react                             16.13.1  16.13.1          17.0.1  @senecacdot/telescope-frontend
> react-dom                         16.13.1  16.13.1          17.0.1  @senecacdot/telescope-frontend
> react-material-ui-form-validator    2.1.1    2.1.1           2.1.4  @senecacdot/telescope-frontend
> react-swipeable-views-utils        0.13.9   0.13.9  0.14.0-alpha.0  @senecacdot/telescope-frontend
> react-use                          15.3.4   15.3.4          17.1.1  @senecacdot/telescope-frontend
> swr                                 0.3.6    0.3.6           0.4.2  @senecacdot/telescope-frontend
> ```

Gatsby's getting deleted this release so the dependencies in there are irrelevant.

**Review by Metropass — APPROVED** [review]
Looks good on my end, we still need to clean up gatsby and any dependencies that we use, otherwise it looks good :)

**Comment by yuanLeeMidori** [comment]
@cindyledev @HyperTHD @Metropass thank you for checking!

1. Updating these dependencies will be divided to several PRs. For the major updates, most of them would come with changes of code as well. I want to put them in separate PRs
2. Yes, Gatsby ones will be remove in the future PRs, thanks for reminder
3. Sure! Me and Anton will be responsible for the whole updating stuff. Anyone sees dependencies needed to update can assign them to me or @birtony 

Thank you!

**Review by PedroFonsecaDEV — APPROVED** [review]

**Pull request merged**
