### PR TITLE
Sign Up page

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
Part of the solution of #1643. 

Here we start to have our /signup page. 

@DukeManh and I have been working on a separate branch, but I believe that if we land this work on our master, it will be good for everyone.
1 -We will have reviewers. 
2 -Everyone can follow what is going on regarding this topic. 
3 -Someone else can be interested in working with us. 

We don't have any buttons to get users to `/signup` yet, since the page is not ready.

TESTING:
1- Pull the PR.
2- As we don't have any button to get into the signup page yet and the SSO authentication must happen before the user hits `/signup`(this part is not done yet); so first you need to sign in into Telescope and then reach the page on the route `/signup`

Nothing here is 100% implemented. 
@DukeManh and I will be sending little PRs to implement the `signup` page. 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by PedroFonsecaDEV** [comment]
@DukeManh 
We failed on VERCEL. 

```

Type error: Type 'null' is not assignable to type '((event: ChangeEvent<HTMLInputElement>, checked: boolean) => void) \| undefined'.
--
02:43:33.908 | 101 \|                   <FormControlLabel
02:43:33.908 | 102 \|                     key={rss}
02:43:33.909 | > 103 \|                     control={<Checkbox checked name={rss} onChange={null} />}
02:43:33.909 | \|                                                           ^
02:43:33.909 | 104 \|                     label={<h1 className={classes.formControlLabel}>{rss}</h1>}
02:43:33.909 | 105 \|                   />
02:43:33.909 | 106 \|                 ))}
02:43:33.927 | npm ERR! code ELIFECYCLE
02:43:33.927 | npm ERR! errno 1
02:43:33.930 | npm ERR! @senecacdot/telescope-frontend@3.0.0 build: `next build && next export`
02:43:33.930 | npm ERR! Exit status 1
02:43:33.930 | npm ERR!
02:43:33.930 | npm ERR! Failed at the @senecacdot/telescope-frontend@3.0.0 build script.
02:43:33.930 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
02:43:33.934 | npm ERR! A complete log of this run can be found in:
02:43:33.934 | npm ERR!     /vercel/.npm/_logs/2021-03-26T06_43_33_931Z-debug.log
02:43:33.940 | Error: Command "npm run build" exited with 1


```

**Comment by PedroFonsecaDEV** [comment]
> @DukeManh
> We failed on VERCEL.
> 
> ```
> 
> Type error: Type 'null' is not assignable to type '((event: ChangeEvent<HTMLInputElement>, checked: boolean) => void) \| undefined'.
> --
> 02:43:33.908 | 101 \|                   <FormControlLabel
> 02:43:33.908 | 102 \|                     key={rss}
> 02:43:33.909 | > 103 \|                     control={<Checkbox checked name={rss} onChange={null} />}
> 02:43:33.909 | \|                                                           ^
> 02:43:33.909 | 104 \|                     label={<h1 className={classes.formControlLabel}>{rss}</h1>}
> 02:43:33.909 | 105 \|                   />
> 02:43:33.909 | 106 \|                 ))}
> 02:43:33.927 | npm ERR! code ELIFECYCLE
> 02:43:33.927 | npm ERR! errno 1
> 02:43:33.930 | npm ERR! @senecacdot/telescope-frontend@3.0.0 build: `next build && next export`
> 02:43:33.930 | npm ERR! Exit status 1
> 02:43:33.930 | npm ERR!
> 02:43:33.930 | npm ERR! Failed at the @senecacdot/telescope-frontend@3.0.0 build script.
> 02:43:33.930 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 02:43:33.934 | npm ERR! A complete log of this run can be found in:
> 02:43:33.934 | npm ERR!     /vercel/.npm/_logs/2021-03-26T06_43_33_931Z-debug.log
> 02:43:33.940 | Error: Command "npm run build" exited with 1
> ```

Fixed.

**Comment by DukeManh** [comment]
@humphd, this is so helpful, thank you. We're figuring out the design for the page, so we make sure we log in first before going there. The styling needs improvement and @PedroFonsecaDEV is working this.

**Comment by DukeManh** [comment]
@chrispinkney  Our validation logic is quite simple, we want to make sure `firstName, lastName, and display` are not empty (`githubData and blogUrl` are returned by GitHub and our backend, so we won't be able to make the most of Formik. But I like Formik and it sure will save us some common code.

**Comment by PedroFonsecaDEV** [comment]
PR not ready.

**Pull request closed without merging**
