### PR TITLE
Improve user accessibility of link to AAA

### PR DESCRIPTION
**Pull request by yuanLeeMidori**
## Issue This PR Addresses
Fixes: #2003

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
I check the contrast ratio of our link in dark mode, both visited and unvisited link are not level AAA. (Current unvisited link color with background color has 6.68 which is only AA level)
Therefore, not only the visited link color that was mentioned in the issue #2003 , I also change the color of the unvisited link to meet AAA requirement. And, since the visited link color for light mode is a bit reddish purple, I change the visited link color in dark mode from grey to something red-purple-ish as well.

Please let me know if you have other thoughts about the color :smiley: 

Before
image

After
image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by PedroFonsecaDEV — APPROVED** [review]
We should include these colors in our theme in a follow-up. 
Maybe @tonyvugithub can help us with the key names.

**Review by humphd — CHANGES_REQUESTED** [review]
Let's do this once in the colour theme vs. individually here.

**Comment by yuanLeeMidori** [comment]
@PedroFonsecaDEV  @humphd thanks for the review! Appriciate that

So I should change the theme instead, correct? And I should discuss this with @tonyvugithub ?

**Comment by HyperTHD** [comment]
> @PedroFonsecaDEV @humphd thanks for the review! Appriciate that
> 
> So I should change the theme instead, correct? And I should discuss this with @tonyvugithub ?

Think you can just modify the theme directly. It's a small change so shouldn't make that big of an impact. Go for it

**Comment by tonyvugithub** [comment]
@yuanLeeMidori @PedroFonsecaDEV right now I only applied it to the post content styling and not to the theme. Reason being is because there are link elements in the other parts of the app like Author info for example that we might not want to have the same effect.

**Comment by yuanLeeMidori** [comment]
@tonyvugithub will you suggest me to append color for post links to the theme, or just do them individually for now? Like what I've done in this PR

**Comment by tonyvugithub** [comment]
@yuanLeeMidori : I think what you did here is good for what we need.

**Review by tonyvugithub — APPROVED** [review]

**Review by humphd — APPROVED** [review]

**Pull request merged**
