### PR TITLE
Scroll action

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
ScrollAction component.

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [X] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
*ScrollTop and ScrollDown becomes: ScrollAction (We had repeated code for up and down, now we have only one component)
*BackToTop becomes: BackToTopButton - No more coupling with ScrollTop

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by PedroFonsecaDEV** [comment]
@manekenpix I will work in turn these components into one component in the future. 

@tianlangwu You are good to go. Reach me on Slack if you need help.

**Comment by PedroFonsecaDEV** [comment]
@humphd As promised the PR to help on #1271.

Thanks

**Comment by PedroFonsecaDEV** [comment]
@humphd I need help here with this test. I believe that it runs, passed but the worker doesn't stop.

```

**Comment by humphd** [comment]
See #1284

**Comment by PedroFonsecaDEV** [comment]
This one is good to go. @humphd @manekenpix

**Comment by humphd** [comment]
@PedroFonsecaDEV do you want to rebase this so we can deal with the conflict in `src/frontend/src/components/ScrollToTop/ScrollToTop.jsx` please?

**Comment by PedroFonsecaDEV** [comment]
Sorry, @humphd I hadn't seen the conflict. I think now we are good to go.

**Review by humphd — APPROVED** [review]

**Review by manekenpix — APPROVED** [review]
:+1:

**Pull request merged**
