### PR TITLE
Fixes #1686 [next] Update deprecated Fonts.

### LINKED ISSUE #1686: [next] Update deprecated Fonts.
**What happened**:
We are using deprecated fonts on our front-end. This issue is just a remind that `typeface-robot` that we currently use is deprecated. And should be replaced by https://github.com/fontsource/fontsource
What is going to be fixed when we start to work on the new UI. 
**What should have happened**:

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
Fixes: #1686 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Currently we use deprecated fonts on our NEXT front-end. 
This PR will fix it and add the font that our UI 2.0 is going to use. 

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by izhuravlev — COMMENTED** [review]
Looks good to me. Would you mind trying to squish all of those 4 commits in one? 
I or @birtony, @humphd can help you with that. 

Let's discuss this at the meeting. If everyone is okay with this, I am good to approve.

**Review by birtony — APPROVED** [review]
LGTM! @izhuravlev good call, we can just use the option `Squash and Merge` to combine these 4 commits in 1.

**Review by foxviet — DISMISSED** [review]
everything looks good

**Comment by PedroFonsecaDEV** [comment]
I'm going to rebase and then merge.

**Pull request merged**
