### PR TITLE
Creating a BottomBar for Mobile Devices

### LINKED ISSUE #1416: Improve Mobile Usability by adding a bottom app bar
**What would you like to be added**:

Proposed design for a bottom app bar, on the left an user that has not logged in, and on the right an user that has:

image

**Why would you like this to be added**:
While on mobile, design should keep in mind the range of the thumb. Currently, we have a top bar that is not easy to reach for people that visit the site on mobile.

image

By adding a bottom app bar, it would benefit the user experience of the mobile users. As an added benefit, it could allow for the title of the post to remain sticky, since there would be enough space for the post sandwiched between the title and the bottom app bar.

### PR DESCRIPTION
**Pull request by ghost**
## Issue This PR Addresses

USAGE: Fixes #1416

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

This pull request fulfills the proposed design for a bottom app bar in issue#1416. I have created the structure of how this bottom bar should work, however, I have not touched the UI and layout of the other components. I didn't not want to remove any components. eg. header, menubar, and circle component at the right bottom. This pull request does not have the correct functionally for the profile and login.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
Screen Shot 2020-12-07 at 12 25 43 PM

Hamburger menu and search are repeated top and bottom (we don't need both).  The scroll to top fab is overlapping the bottom bar.  The bottom bar is showing for non-mobile widths (media query isn't right).

**Comment by jiyoungsin** [comment]
Thank you for reviewing my pull request. I was unsure if this was in my scope of tasks, since this issue was requiring just a BottomBar. I will have these changes made within the next few days.

**Comment by jiyoungsin** [comment]
I have Made some changes to this Pull request. I have removed the icons at the MobileHeader.jsx. Refactored the code from the file that used those components.
In addition I have moved the Moved Typography and ScrollAction Component up a few pixels to allow a better user interface. Please let me know if you would like any other changes implemented!

**Comment by PedroFonsecaDEV** [comment]
Hey @jiyoungsin,
I believe that we are still facing the same issues that David pointed. 
1. Scroll button overlapping. 
2. >The bottom bar is showing for non-mobile widths (media query isn't right).

I would recommend improving the mobile headers CSS instead of using the same break-point that triggers it. (I will leave a comment on the code.) 
3. The version text, is too close to the bottom bar. 
Screen Shot 2020-12-27 at 3 17 39 AM

**Comment by chrispinkney** [comment]
I'm going to take this on for 1.6 using the feedback from @PedroFonsecaDEV, I'll be in touch with you @yuanLeeMidori for a review 😄

**Comment by chrispinkney** [comment]
@tonyvugithub and I will re-evaluate this when we begin the PWA (#801)

**Pull request closed without merging**
