### PR TITLE
Add GitHub components for Repos, Issues, PullRequests

### LINKED ISSUE #2360: Add GitHub components for Repos, Issues, PullRequests
I'd like to add a way to quickly see all the GitHub repos, issues, and PRs discussed in a blog post.  I'm thinking to include a side-bar of details showing quick links to things discussed in a post.  Here's a really rough mock-up (ignore colours, spacing, design, etc):

Screen Shot 2021-10-14 at 2 43 52 PM

When we render a post, we'd extract the URLs and then pass them as an array down to a component:

```jsx
// We have to do this part later...
const extractedGitHubUrls = extractGitHubUrlsFromPost(post.text);
return (
  ...
  <GitHubInfo ghUrls={extractedGitHubUrls} />
  ...
);
```

This `GitHubInfo` component would then take this list of `github.com/*` URLs and separate it out into repos, issues, and pull requests, passing them onto child components that would render everything:

```jsx
const { repos, issues, pullRequests } = filterGitHubUrls(ghUrls);

return (
  { repos ? <Repos repoUrls={repos} /> : null; }
  { issues ? <Issues issueUrls={issues} /> : null }
  { pullRequests <PullRequests prUrls={pullRequests} /> : null }  
);
```

Each of these would render the correct icons, links, etc in the sidebar.

We use `react-icons` which has what we need I think, for example: https://react-icons.github.io/react-icons/search?q=pull

### PR DESCRIPTION
**Pull request by menghif**
## Issue This PR Addresses
Fixes #2360

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

This PR adds a way to display links for all GitHub repos, issues and pull requests that are linked throughout a post. This information is displayed on the right sidebar underneath the blog post's date for easy visibility.

If there is no repo URL in the post, but there is at least one issue or PR, the repo URL will be taken from that issue or PR.

Screenshots:

Screenshot 2021-10-18 at 17-50-30 Search Telescope

---

Screenshot 2021-10-18 at 18-00-49 Telescope

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by menghif** [comment]
How do I fix this?

https://user-images.githubusercontent.com/53121061/137814595-023a6f72-5d5f-4d39-9b75-55cb6e18abba.mov

**Comment by Andrewnt219** [comment]
We may want to add type 'commit' to the list too.
image

**Comment by Andrewnt219** [comment]
> Issue with long names (check the repo)
> 
> image

This may be a problem with Safari. Doesn't happen on Firefox or Chrome on Window.

**Comment by Andrewnt219** [comment]
@humphd If we can decide on whether these components should receive a link or a parsed object, I can wrap things up in half an hour.

**Comment by HyperTHD** [comment]
I just wanna confirm that the repo looking buggy when the name is long is also appearing for me on Google Chrome.

Just something to consider if and when this does get merged, since the css used here never had this idea in mind

image

**Comment by HyperTHD** [comment]
> @HyperTHD I can't reproduce, Is it a `line-height` issue? Yes, we need to file an issue on this one too.

I suspect that is the issue. Unless I'm mistaken, this should be the problem

image

**Comment by humphd** [comment]
Rebased and merged in https://github.com/Seneca-CDOT/telescope/commit/bce0b2106c59c33b712e9581c47f7bb8012f2720.  Great job everyone!

**Pull request closed without merging**
