### PR TITLE
Reduce size of web service using nginx stable-alpine

### LINKED ISSUE #2835: Improve size of web Dockerfile
In our `src/web/Dockerfile`, we can use a smaller nginx image:

https://github.com/Seneca-CDOT/telescope/blob/master/src/web/Dockerfile#L56

That could be `nginx:stable-alpine`.  I'm not sure if we have other `nginx` layers anywhere that we could update as well.

### PR DESCRIPTION
**Pull request by TDDR**
## Issue This PR Addresses
Fixes #2835 

## Type of Change

There has been some discussion in the issue itself about how to tackle this. As requested by @humphd I have made a PR to get some help figuring this out.

> Using `USER nginx` should work. What does it show when you do this? Can you put the whole Dockerfile up somewhere so I can test with you?

Yesterday when I was trying this, I was getting an error message saying something like `the nginx user was not fond`. Today, when I went to replicate the error I get this message now when I run a `pnpm services:start` 
image

Switching into the web folder `cd src/web` and then running a `docker build .` produces a similar error
image

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Steps to test the PR
- checkout the pr `gh pr checkout 2944`
- `pnpm services:start`
- the project should build without error

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by manekenpix** [comment]
I'm getting this at launch

```sh
nginx   | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx   | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx   | 2022/02/16 00:44:11 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:22
nginx   | nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:22
nginx   | 2022/02/16 00:44:11 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx   | nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx exited with code 1
```

**Comment by manekenpix** [comment]
I was able to run `web` removing the user in the `Dockerfile` (USER nginx) and removing [this line](https://github.com/Seneca-CDOT/telescope/blob/2536b851da03543b403008f419983fbf8e97f734/config/nginx.conf.template#L22). We'd also have to remove the same line in [nginx.conf.development.template](https://github.com/Seneca-CDOT/telescope/blob/master/config/nginx.conf.development.template).
I tested it on `staging` and it seems to run with no issues.

**Comment by manekenpix** [comment]
> Using USER nginx should work. What does it show when you do this? Can you put the whole Dockerfile up somewhere so I can test with you?

I did some testing and removing `USER nginx` from Dockerfile **and** adding `user nginx;` to [nginx.template](https://github.com/Seneca-CDOT/telescope/blob/master/config/nginx.conf.template) and [nginx.conf.development.template](https://github.com/Seneca-CDOT/telescope/blob/master/config/nginx.conf.development.template) (line 22) seems to work.

**Comment by humphd** [comment]
Let's switch the user we use in the two `nginx.conf` files like @manekenpix suggests.

**Review by humphd — APPROVED** [review]
This is great.  Please file issues/PRs to do the same thing in other containers.

**Pull request merged**
