### PR TITLE
Fix #3212 - allow cross-origin image loading for image service

### LINKED ISSUE #3212: [Image]: Banner image failed to load because CORS violation
The banner image is not showing on staging

**What happened**:

image

**Environment**:
- OS: macOS Montery
- Browser: Any browser

### PR DESCRIPTION
**Pull request by humphd**
I think this will fix the change in helmet, stopping us from loading images cross-origin.

### CODE REVIEW

**Review by DukeManh — APPROVED** [review]
I was thinking of downgrading back to helmet@4.6 because I don't want to deal with this.

We should be more careful when merging Renovate major version release.

**Comment by humphd** [comment]
> We should be more careful when merging Renovate major version release.

Amen.  Any MAJOR bump should be viewed with extreme caution.

**Review by menghif — APPROVED** [review]
Sorry, I don't know how the update happened. Thank you for the fix!

**Comment by DukeManh** [comment]
I was a renovate dep update, i don't think you did it @menghif.

**Comment by cindyledev** [comment]
> I was a renovate dep update, i don't think you did it @menghif.

Yeah, it was me and my bf, Renovatebot

Was anyone able to get this fix to work? I've tried pulling this PR but I keep getting errors
Screenshot 2022-03-16 195150

and I've also tried downgrading helmet

**Comment by Kevan-Y** [comment]
Steps I did:
- `gh pr checkout 3229`
- `pnpm i`
- `pnpm services:start`
- go to `http://localhost:8000/`

I think it's not working.
image

**Comment by Kevan-Y** [comment]
There is a fix https://github.com/Seneca-CDOT/telescope/pull/3233, that works.

**Comment by humphd** [comment]
Closing in favour of #3233.

**Pull request closed without merging**
