### PR TITLE
Fixes #338: moved login.html to frontend dir

### LINKED ISSUE #338: Link to login.html doesn't work
Annotation 2019-11-23 213212

### PR DESCRIPTION
**Pull request by cindyledev**
Moved login.html from `src/login/login.html` to `src/frontend/login.html` and updated `index.html` to refer to correct relative URL for login.

Annotation 2019-11-25 212535

### CODE REVIEW

**Comment by agarcia-caicedo** [comment]
> 
> 
> Redirect works, the circle CI and Travis tests are due to an unrelated issue that should be fixed now.

Were the issues fixed in a commit or were the issues unrelated to the code. In other words, should this fix be updated to have the current code or is it fine as is?

**Comment by Grommers00** [comment]
Good find @agarcia-caicedo as well.
Once fixed I can approve request as well.

Keep in mind this page is just used as a place holder as well.

**Comment by UltimaBGD** [comment]
Unrelated to this PR, you can see it on a lot of recent PR’s. Should have been fixed with PR #344.

**Comment by cindyledev** [comment]
Thanks guys, I totally missed that. Fixed the href and rebased. Please review again :)

**Pull request merged**
