### PR TITLE
Test for using existing URL feed and fix feed typo

### PR DESCRIPTION
**Pull request by JiaHua-Zou**
## Issue This PR Addresses
#2909

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Closed PR #3319  .Reopening it.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by JiaHua-Zou** [comment]
In the SSO, the file `middleware.js` line 92 `(.in('feed_url', feeds)`. Test is failing becuase of it. When I ran the website on the local machine, I was able to create 2 accounts with the same blog. Changing the `feed_url` to `url` will fix this problem, but the `signup flow works to login and register a new Telescope user` test will fail. It fails at `partTwo` function. It expects a status `200` but got `404` instead.

**Comment by JiaHua-Zou** [comment]
Before changing `feed_url` to 'url'
image
After:
Fix the bug that the same user can signup with a same feed, but first test is failing. 
image

**Review by humphd — COMMENTED** [review]
I pulled your branch locally, and ran the tests.  They pass:

```
pnpm jest:e2e src/api/sso/test/e2e/signup-flow.test.js

> @senecacdot/telescope@2.9.0 jest:e2e /Users/humphd/repos/telescope
> jest -c jest.config.e2e.js --forceExit -- "src/api/sso/test/e2e/signup-flow.test.js"

LOG_LEVEL set to `silent`, change in jest.config.base.js if you want more logs
Waiting for Supabase postgres container to become ready...
Supabase postgres container ready.
 PASS   browser: chromium  src/api/sso/test/e2e/signup-flow.test.js
  Signup Flow
    ✓ should have none of the users in the Users service for test data accounts (202 ms)
    ✓ signup flow works to login and register a new Telescope user (971 ms)
    ✓ signup flow fails if user is not authenticated (74 ms)
    ✓ signup flow fails if user data is missing required properties (741 ms)
    ✓ signup flow fails if user is already a Telescope user (745 ms)
    ✓ Signup flow fails if feed is already used by another Telescope user (1641 ms)

 PASS   browser: firefox  src/api/sso/test/e2e/signup-flow.test.js (5.607 s)
  Signup Flow
    ✓ should have none of the users in the Users service for test data accounts (209 ms)
    ✓ signup flow works to login and register a new Telescope user (903 ms)
    ✓ signup flow fails if user is not authenticated (179 ms)
    ✓ signup flow fails if user data is missing required properties (823 ms)
    ✓ signup flow fails if user is already a Telescope user (860 ms)
    ✓ Signup flow fails if feed is already used by another Telescope user (2195 ms)

 PASS   browser: webkit  src/api/sso/test/e2e/signup-flow.test.js
  Signup Flow
    ✓ should have none of the users in the Users service for test data accounts (183 ms)
    ✓ signup flow works to login and register a new Telescope user (820 ms)
    ✓ signup flow fails if user is not authenticated (161 ms)
    ✓ signup flow fails if user data is missing required properties (945 ms)
    ✓ signup flow fails if user is already a Telescope user (756 ms)
    ✓ Signup flow fails if feed is already used by another Telescope user (1671 ms)

Test Suites: 3 passed, 3 of 1 total
Tests:       18 passed, 18 total
Snapshots:   0 total
Time:        16.604 s
Ran all test suites matching /src\/api\/sso\/test\/e2e\/signup-flow.test.js/i.
Force exiting Jest: Have you considered using `--detectOpenHandles` to detect async operations that kept running after all tests finished?
```

One thing I did notice while running this locally is that the `planet` service is crashing on startup, see #3347.  I fixed that manually in my tree to run the containers.  This causes the `nginx` container to crash too, since it depends on the `planet` upstream server.

This makes me think that we either don't have all the containers you need running, or one or more is crashing in CI and affecting this.  Here are the containers we run during e2e tests: https://github.com/Seneca-CDOT/telescope/blob/master/.github/workflows/e2e-tests-ci.yml#L15

I tried running these locally, then your tests:

```
$ pnpm services:start sso feed-discovery auth login kong rest meta elasticsearch redis posts traefik
$ pnpm jest:e2e src/api/sso/test/e2e/signup-flow.test.js
```

It all passes for me.

**Comment by humphd** [comment]
Rebasing to see what's up with the commits under this, I don't get why it's failing.

**Comment by humphd** [comment]
It's possible that #3347 is causing this, and taking nginx down in the process, which would explain the 404.  Beyond that, I have no idea.

Let's fix #3347 as a test, and rebase on that.

**Comment by JiaHua-Zou** [comment]
The test is still failing after rebasing my branch.

**Comment by JiaHua-Zou** [comment]
ok I get it now. When I run the test on my machine, it passes.

**Comment by humphd** [comment]
@Kevan-Y has a possible fix for this in #3307, which we'll need to get this rebased onto once that goes in.

**Comment by humphd** [comment]
#3307 is in, please rebase and test @JiaHua-Zou

**Comment by JiaHua-Zou** [comment]
I'll rebase asap.

**Review by DukeManh — APPROVED** [review]

**Pull request merged**
