### PR TITLE
Issue 1974: Student Quotes

### LINKED ISSUE #1974: Use quotes from former students about open source on front page
I'd like to see us extract some of the best quotes from former students about their experience working on open source, and use them on the front page (probably on top of the hero banner image in place of the stats?).

Every term for years and years, students write some amazing reflections on their experiences working in open source.  I think we could pull out some quotes that would be nice to use on the site as a way to inspire the current students.  We could put a bunch in a JSON file in the front-end and show a random one.

We can get at these old posts using various queries:

- https://dev.telescope.cdot.systems/search/?text=%22open%20source%22%20reflection&filter=post
- https://dev.telescope.cdot.systems/search/?text=%22open%20source%22%20conclusion&filter=post
- https://dev.telescope.cdot.systems/search/?text=%22open%20source%22%20feelings&filter=post

etc.  If you want to be involved in this, you can go do a search, read old posts, and if you see an inspiring quote about contributing to open source, blogging, etc. put it in this issue with:

- link to post
- quote
- author

### PR DESCRIPTION
**Pull request by AmasiaNalbandian**
## Issue This PR Addresses
Fixes #1974

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
I have added a temporary JSON in a file called student-quotes.js with some quotes that struck out to peers in the issue and I. In the Banner.tsx file I have added functionality to pick a random quote and display it on the home page in the banner. When you click on the student's name, it is redirected to the blog link for the quote.

chrome_VuKOGJDFtT
chrome_OjT6LZnfX9
## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by PedroFonsecaDEV — COMMENTED** [review]
I think a space between the quote and the author name would be a good idea. 
Also not sure about the `i` tag. 

I would go to with something like this:
Screen Shot 2021-10-30 at 8 07 43 PM

**Review by Grommers00 — CHANGES_REQUESTED** [review]
I think added in italics to the quote instead of the author might look better, and agreed with Pedro the space between the quote and the author will make it magnificent. 

What are your thoughts?

**Comment by AmasiaNalbandian** [comment]
> I think added in italics to the quote instead of the author might look better, and agreed with Pedro the space between the quote and the author will make it magnificent.
> 
> What are your thoughts?

This is how it looks italisized: 
image

**Review by PedroFonsecaDEV — APPROVED** [review]
LGTM.

**Review by Grommers00 — APPROVED** [review]

**Comment by Grommers00** [comment]
Looks good!

**Pull request merged**
