### PR TITLE
Progress towards #1237: Migrate front-end from GatsbyJS to Next.js

### PR DESCRIPTION
**Pull request by manekenpix**
## Issue This PR Addresses
Progress towards #1237 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

We're switching to [Nextjs](https://nextjs.org/). Since keeping both frameworks in the same folder would be difficult for clean development and testing, this PR removes all the previous code and sets up the developer tools (linters, prettier, husky...) for `Nextjs`.
This way, contributors can pick a component/piece code/feature from the `master` branch and add it to the `next` branch.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by cindyledev — APPROVED** [review]
Tested using Windows 10. For those checking this PR, remember to delete your old `node_modules` and `package-lock.json` in the frontend directory then run `npm install` and `npm run dev`.

To fresh starts 🍻

**Review by raygervais — APPROVED** [review]
To new beginnings ☕️

**Review by humphd — CHANGES_REQUESTED** [review]
I'd like this change to be accompanied with a migration plan.  The best time to do it, in my opinion, is before we lose track of everything we're removing.

Let's create a meta issue or wiki page that has a checklist of:

- every component, feature, setting, etc. that needs to get migrated
- a parity list of what the old site did, and what the new one needs to do in order to be complete
- a way to measure progress porting from one to the other
- a way for *lots* of people to get involved in doing small bits of work toward the larger goal.

I'd like to see the new site running (parity with Gatsby) by the end of term, and planning this migration is a bunch of work.  People won't know how to "take a component from the old site and move to the new one" unless they are one of the core developers who wrote everything.

I'm happy to be involved with developing this, but won't have cycles to do so until next week.

**Comment by manekenpix** [comment]
:+1: I'll close this PR until the migration plan is ready. I'd be great if we could all work together on the plan. This is so exciting!

**Pull request closed without merging**
