### PR TITLE
Change color for search bar in dark mode

### PR DESCRIPTION
**Pull request by yuanLeeMidori**
## Issue This PR Addresses
Fixes: #2009

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

For #2009
darkSearch

I change the color of hovered search bar for dark mode to improve user accessibility, Please let me know if you have different thought of the color choosing, thanks!
## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by HyperTHD — CHANGES_REQUESTED** [review]
Looked at it rn, and this is what I see for the select bug fix on your current deployment
image

idk if it's just me, but that doesn't look like what it should be in your screenshot

**Review by PedroFonsecaDEV — APPROVED** [review]
LGTM.

**Comment by yuanLeeMidori** [comment]
@PedroFonsecaDEV  @HyperTHD thank you for the review!
I double-checked, somehow the background color of select item does not applied to dark mode sometimes. Sorry about that.

I'll just push the change of search bar background in this PR, and move the select item color issue to next release.

**Review by PedroFonsecaDEV — APPROVED** [review]
LGTM.

**Review by HyperTHD — APPROVED** [review]
Much better, GTM

**Pull request merged**
