### PR TITLE
Update and document SSO authentication backend 

### PR DESCRIPTION
**Pull request by humphd**
## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Doing some dev work with @Grommers00 and @agarcia-caicedo yesterday, it was clear that having to always run the full docker-compose version of our app(s) can be very heavy, especially if you don't have a lot of RAM/CPU.

I've been working on a way to run our app without needing the Login system, or Gatsby and Express running in docker.

To do it, I've added a new environment variable, `MOCK_SSO`.  Similar to our `MOCK_REDIS`, if you set it, the app will run a fake SAML authentication service, and allow the front end to login/logout, and get user information for a single user.

You set the variable in your `.env` on on the command line like this:

```
MOCK_SSO=1
```

Now you can run your backend and Gatsby and login/logout, or hit authenticated routes as you would normally.  I've also updated the docs on how to run Gatsby + Express using the proxy @agarcia-caicedo setup for us.

This can probably be improved, and cleaned up a bit.  But it's working enough that I thought I should get it up for review and we can start using it to allow the frontend team to work faster.

### CODE REVIEW

**Comment by humphd** [comment]
I feel like the change I made in #690 makes this unnecessary, since we can use the staging auth backend too.

I might strip this down to just include a few bug fixes I made in the general auth code and update this PR.

**Comment by cindyledev** [comment]
Are you guys getting any feeds when setting the `API_URL=https://dev.telescope.cdot.systems`?
I'm trying to use the third method but I can't seem to get any blog posts and the Login button doesn't work
Annotation 2020-02-11 203736

**Comment by manekenpix** [comment]
@cindyledev I just tested it and it seems ok, Did you try localhost?
mierda

**Comment by manekenpix** [comment]
When login redirects you to `dev.telescope` (that's why it's showing `dev.telescope` in the address bar).
This is `localhost:8000`  with `API_URL=https://dev.telescope.cdot.systems`:

Screenshot_20200211_211029

**Comment by cindyledev** [comment]
I couldn't get this to work at home last night but I got it working in class today for Windows

**Pull request merged**
