### PR TITLE
Issue 1225b - Reposition search button for search UI

### PR DESCRIPTION
**Pull request by strawberries73**
## Issue This PR Addresses
Fixes Issue #1437 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Moved search button
image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by manekenpix — CHANGES_REQUESTED** [review]
I think you added the `.cache` folder inside of the frontend folder to the PR.

**Comment by strawberries73** [comment]
@manekenpix I didn't know I did that.  I had problems with the old PR 1225, and had to make a new branch.  Just realized 5 minutes ago I forgot to add something.

**Comment by c3ho** [comment]
I think this is the fifth PR opened on this issue? At this point I think it would be a better idea to understand why this is happening instead of opening new PRs

**Comment by manekenpix** [comment]
@strawberries73 is it ok to close #1437?

**Pull request closed without merging**
