### PR TITLE
Issue-1344  Added margin after search bar

### LINKED ISSUE #1344: Add Bottom margin to search component
**What would you like to be added**:
Currently, when results are displayed in the search page, there isn't much space separating the search component and the results
image

**Why would you like this to be added**:
Margin will improve the design of the page

### PR DESCRIPTION
**Pull request by strawberries73**
## Issue This PR Addresses
Fixes #1344 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Margin has been added under the search bar.
image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by humphd** [comment]
@strawberries73 can you update (i.e., Edit) the comment at the top of this PR to include:

- Issue # that this addresses (e.g., `Fixes #13241`)
- description of what you did in this change, including screenshots in this case, since it's a visual change

The template is missing info.  Thanks, this will help with review.

**Comment by strawberries73** [comment]
@humphd  How do I add an image?

**Comment by agarcia-caicedo** [comment]
@strawberries73 I usually just take a screenshot and just paste it in

**Comment by humphd** [comment]
Screen Shot 2020-11-15 at 3 32 53 PM

**Comment by strawberries73** [comment]
image

**Comment by humphd** [comment]
@strawberries73 you need to edit your original comment at the top, and put that info in there:

Screen Shot 2020-11-15 at 3 34 26 PM

**Comment by humphd** [comment]
@strawberries73 that formatting is perfect, thanks.  Do it like that every time.  It helps your reviewer know what you did, what you're fixing, and how to review the changes.

**Comment by strawberries73** [comment]
@humphd Thank you for walking me through this.  I will remember next time.

**Review by PedroFonsecaDEV — APPROVED** [review]

**Review by agarcia-caicedo — APPROVED** [review]

**Pull request merged**
