### PR TITLE
Add /status to deploy server, fix callback missing bug

### PR DESCRIPTION
**Pull request by humphd**
This updates the deployment server to do a few things:

1. adds a `/status` endpoint, so we can get info on what's happening (idle or building), what the duration of the build is, what the result of the last build was, etc.
1. fixes a bug where we would crash if someone tried to hit an endpoint other than the ones we expect (we needed a callback)
1. added logging for stdout and stderr

### CODE REVIEW

**Comment by humphd** [comment]
Would it make sense for me to add a route to the main server that redirects to this?

```
GET /admin/build-status   --->    redirect to :4000/status
```

?

**Comment by manekenpix** [comment]
I think it would. Maybe not redirect but show the info fetched from the deploy server, as a Telescope feature and not something _external_.

**Comment by humphd** [comment]
How should I deal with the fact that the deploy port is specified in an env outside the telescope app?  I either need to be able to read it in Telescope's node server, or we have to hard code it so I can assume it's always the same.

**Comment by manekenpix** [comment]
I'm not sure. I'm thinking that maybe Telescope can get that information from _the other_ `.env`? but I don't know if that'd be a good way to do it.

**Comment by humphd** [comment]
I did some more work on this, trying to add proxying from the main node app to the deployment app for admins, so you can get info and build logs.  It's not fully working yet.

**Comment by humphd** [comment]
@manekenpix should we land this before or after we release 1.0.0?  I'm fine either way.

**Comment by manekenpix** [comment]
I think we can do it before.

**Pull request merged**
