### PR TITLE
Added Search page

### LINKED ISSUE #720: Create a Search page
**What would you like to be added**: 

Create a search page that would go under the pages folder in the front-end. It should import the navbar and use the main styling.

**Why would you like this to be added**:
This page is needed to add search functionality

### PR DESCRIPTION
**Pull request by agarcia-caicedo**
## Issue This PR Addresses
This fixes #720 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

Added a new empty page for search. This will allow other contributors to add their search components. 

image

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by agarcia-caicedo** [comment]
> Do we need to add the .css to keep with the same format of the other react pages?

It already has the css. There is not really that much css in our project at the moment

**Comment by cindyledev** [comment]
We can always add a .css file if we need one later. We just need this as a home to put the other Search components

**Comment by miggs125** [comment]
I was under the impression that we were making a single page application (SPA)? This deviates from that idea.

**Comment by agarcia-caicedo** [comment]
> 
> 
> I was under the impression that we were making a single page application (SPA)? This deviates from that idea.

We are not making a SPA. Currently, in addition to the search page, we are in the process of adding profile page where the user can add their feed and manage it

**Pull request merged**
