### PR TITLE
Add commit link to latest contribution

### LINKED ISSUE #2506: Link to latest contribution
In the Dashboard we list the last contributor to Telescope and Satellite, which includes a link to the user's name.  However, I can't click anything to see the PR that they made.  Let's find a way to include this info somehow and a link.

Screen Shot 2021-11-21 at 12 55 34 PM

### PR DESCRIPTION
**Pull request by Kevan-Y**
## Issue This PR Addresses

Fixes #2506 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Format:
```
(avatar) Luigi Zaccagnini 2dc6a97
```
image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by humphd** [comment]
Can we do something to set the SHA off from the name a bit more?  Here is how GitHub does it:

Screen Shot 2021-11-23 at 5 23 43 PM

In other words: monospaced type 'code' font, clickable, in blue.

**Comment by Kevan-Y** [comment]
> Can we do something to set the SHA off from the name a bit more? Here is how GitHub does it:
> 
> Screen Shot 2021-11-23 at 5 23 43 PM
> 
> In other words: monospaced type 'code' font, clickable, in blue.

Is this enough, change to monospaced, used .text-xs , and .btn-link class 
image

**Comment by humphd** [comment]
Yeah, that's a lot better.

**Review by humphd — APPROVED** [review]
Tested on GitPod, works well (nice touch that @Kevan-Y is the latest contributor!):

Screen Shot 2021-11-23 at 6 35 35 PM

**Review by Andrewnt219 — APPROVED** [review]
Nice. Tested locally.

**Comment by humphd** [comment]
@Kevan-Y go ahead and merge this yourself.

**Pull request merged**
