### PR TITLE
Generalize the GitHubInfoProvider

### LINKED ISSUE #2946: Generalize the GitHubInfo Provider
So, for #2680 to be done, I think we would need to rewrite the GitHubInfoContextProvider so that it can also provide other types of information, like YouTube information.

The main idea I have is to have a GenericInfoProvider, which has a GenericInfoContext, which has a definition like the following:

```typescript
interface GenericInfoContextInterface {
    gitHubInfo: GitHubInfoContextInterface;
    youTubeInfo: YouTubeInfoContextInterface;
    ...
}
```

And then we can keep the same hook, by rewriting it like this:

```typescript
const useGitHubInfo = () => useContext(GenericInfoContext).gitHubInfo;
```

and we can also add more hooks

```typescript
const useYouTubeInfo = () => useContext(GenericInfoContext).youTubeInfo;
```

I think this is a trade-off between rewriting all the GitHub-related components to adjust to a new API, or writing a clever solution that might difficult to understand or maintain.

### PR DESCRIPTION
**Pull request by dbelokon**
## Issue This PR Addresses

Fixes #2946 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI
- [X] **Refactoring**: Change that refactors code without modifying current behaviour

## Description

This PR refactors the GitHubInfo Provider so that we can fit other types of data easier.

## Steps to test the PR

1. Pull my changes (`git fetch dbelokon`, you need a remote reference to my repo first!)
2. Go to the commit (`git checkout issue-2946`)
3. Run the front-end with any settings you prefer, although I recommend using `env.staging` because only the front-end is necessary (`pnpm dev`)

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by menghif — CHANGES_REQUESTED** [review]
Can we move the GitHubInfo logic from `GenericInfoProvider.tsx` to its own component `GitHubInfo.tsx`?

**Comment by dbelokon** [comment]
> Can we move the GitHubInfo logic from `GenericInfoProvider.tsx` to its own component `GitHubInfo.tsx`?

Sure!

**Review by menghif — DISMISSED** [review]
Looks good!

**Review by TueeNguyen — APPROVED** [review]
I just learnt about context here in your PR, I think it looks ok. You're going to add `youtubeInfo` in following PRs right?

**Comment by dbelokon** [comment]
> I just learnt about context here in your PR, I think it looks ok. You're going to add `youtubeInfo` in following PRs right?

Yeah, `YouTubeInfo.tsx` would be added in the second PR. I didn't want to do everything in a single PR because it would be overwhelming to review.

I will try to squash and rebase now!

**Comment by TueeNguyen** [comment]
@dbelokon, let's rebase again and clear this PR!

**Pull request merged**
