### PR TITLE
Implementing a Bottom Bar

### LINKED ISSUE #1416: Improve Mobile Usability by adding a bottom app bar
**What would you like to be added**:

Proposed design for a bottom app bar, on the left an user that has not logged in, and on the right an user that has:

image

**Why would you like this to be added**:
While on mobile, design should keep in mind the range of the thumb. Currently, we have a top bar that is not easy to reach for people that visit the site on mobile.

image

By adding a bottom app bar, it would benefit the user experience of the mobile users. As an added benefit, it could allow for the title of the post to remain sticky, since there would be enough space for the post sandwiched between the title and the bottom app bar.

### PR DESCRIPTION
**Pull request by jiyoungsin**
## Issue This PR Addresses

USAGE: Fixes #1416

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

This pull request fulfills the proposed design for a bottom app bar in issue#1416. I have created the structure of how this bottom bar should work, however, I have not touched the UI and layout of the other components. I didn't not want to remove any components. eg. header, menubar, and circle component at the right bottom. This pull request does not have the correct functionally for the profile and login.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by humphd** [comment]
Screenshots in your description for all UI changes, please.

**Comment by jiyoungsin** [comment]
Here is a little gif I have made using the buttons!
bottomBar

**Comment by agarcia-caicedo** [comment]
@jiyoungsin, just read your questions from #1416, the person Icon should be a link to myfeeds page, while the hamburger menu should be a modified version of the one that currently exists. For a logged out user, the menu would only have a link to the about page (though if #1414 goes through, we would also need the toggle), for a logged in user, the menu would have the about page, and the logout button

**Comment by jiyoungsin** [comment]
I have not Tested the endpoints. Can someone please test these for me? I will move the hamburger menu soon.

**Comment by humphd** [comment]
> I have not Tested the endpoints

Why not?  Do you need help running this locally?  You should get it all running so you know if it works.

**Comment by jiyoungsin** [comment]
Yes, I am having difficulty understanding how to test this locally. I looked at the code we used to log in for the implemented log in button and copied the exact method endpoint used. I found the testing locally a little difficult to understand. Could you please give me some more details on how to run this locally?

**Comment by humphd** [comment]
Find us on Slack and we can talk you through it.  We can help, but ultimately, you have to drive this.

**Review by manekenpix — CHANGES_REQUESTED** [review]
I think you've been merging other branches into yours, and now this PR shows 132 files changed, with 55 commits (and most of them are not yours). Can you please fix that?

**Comment by jiyoungsin** [comment]
@manekenpix Thank you for pointing this out i will fix this right away!

**Comment by jiyoungsin** [comment]
I will close this PR since I have created a new [Pull request](https://github.com/Seneca-CDOT/telescope/pull/1477).

**Pull request closed without merging**
