### PR TITLE
import Fragment from react

### LINKED ISSUE #3131: <Fragment> component not imported properly in nextjs.md doc
When I was working on #3128, I kept getting 

```
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
```

This is due to how we added the `Fragment` component in `src/docs/docs/tools-and-technologies/nextjs.md` file. We need to add

```
import { Fragment } from 'react';
```

To reproduce warning, run `pnpm build` in `src/docs` directory:
```
PS C:\Users\lecin\Documents\repo\telescope\src\docs> pnpm build

> @senecacdot/telescope-docs@0.0.1 build C:\Users\lecin\Documents\repo\telescope\src\docs
> docusaurus build

[INFO] Website will be built for all these locales:
- en
- fr
- vi
- ru
- uk
- es
- zh-cn
[INFO] [en] Creating an optimized production build...

✔ Client
  

✔ Server
  Compiled successfully in 6.19s

Component Fragment was not imported, exported, or provided by MDXProvider as global scope
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
Component Fragment was not imported, exported, or provided by MDXProvider as global scope
[SUCCESS] Generated static files in build.

### PR DESCRIPTION
**Pull request by sancodes**
## Issue This PR Addresses
Fixed #3131

## Type of Change

- [X] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Missing import statement has been added, to fix the break when building. 
It was added in the `src/docs/docs/tools-and-technologies/nextjs.md` file

## Steps to test the PR

   run `pnpm build` in `src/docs`directory
## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

Screen Shot 2022-03-07 at 12 30 18 PM

### CODE REVIEW

**Comment by tpmai22** [comment]
@sancodes Please kindly mention fix or refer to fully close the issue after this PR got merged.

**Review by tpmai22 — APPROVED** [review]
Nicely done !

**Comment by sancodes** [comment]
@tpmai22 I've added little description at the very start. Does that look okay?

**Comment by tpmai22** [comment]
@sancodes I think `Fixed [issue#] ` would help if I was not clear on my comment

**Comment by sancodes** [comment]
@tpmai22 does the change in comment look good?

**Comment by tpmai22** [comment]
@sancodes That perfect ! We are good to go with one more review. @cindyledev anytime you hanging around `telescope`  💯

**Review by DukeManh — APPROVED** [review]

**Comment by tpmai22** [comment]
@sancodes `Telescope` is moving fast so clicking this button will help with your rebase 
image

**Pull request merged**
