### PR TITLE
Fix some responsive  issues

### PR DESCRIPTION
**Pull request by DukeManh**
This fixes some responsiveness issues in the frontend:
- Truncate post title at 2 lines
- Fluid post title
- Smaller code block padding on mobile
- Smaller code block and inline code font-size

before          |  after
:-------------------------:|:-------------------------:
Screen Shot 2021-12-10 at 2 47 39 PM |  Screen Shot 2021-12-10 at 2 47 52 PM 

before          |  after
:-------------------------:|:-------------------------:
Screen Shot 2021-12-10 at 2 51 56 PM |  Screen Shot 2021-12-10 at 2 50 48 PM

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — APPROVED** [review]
Nice.  I really want to get rid of the white background on code blocks in a follow up.

**Comment by DukeManh** [comment]
@humphd, can you review again, I fixed the order of before and after images.

**Review by humphd — DISMISSED** [review]
Yeah, it's good. I tested on vercel.

**Review by HyperTHD — APPROVED** [review]

**Review by humphd — APPROVED** [review]

**Review by HyperTHD — APPROVED** [review]

**Review by tpmai22 — DISMISSED** [review]

**Review by humphd — APPROVED** [review]

**Review by Andrewnt219 — APPROVED** [review]
Look great on mobile.

**Pull request merged**
