### PR TITLE
Fix Search label text cut off

### LINKED ISSUE #3443: Search label text cut off
In the [search page](https://telescope.cdot.systems/search/), when the text moves to be a label, it gets cut off (not enough width?):

Screen Shot 2022-04-08 at 7 05 16 PM

### PR DESCRIPTION
**Pull request by Kevan-Y**
## Issue This PR Addresses
Fixes #3443

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Due to different font-size in `customInput` and `customInputText`, it makes the Search label text cut off.
Fixes:
 - Change font size in `customInput` to match `customInputText`

image

## Steps to test the PR

1. `cp config/env.staging .env`
2. pnpm dev`
3. Go to the search page 
## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — COMMENTED** [review]
I'm not a huge fan of fixed sizes on fonts, since it's not responsive.  Is there no better fix for this?

**Comment by Kevan-Y** [comment]
> I'm not a huge fan of fixed sizes on fonts, since it's not responsive. Is there no better fix for this?

I don't have it in mind, but the actual fix would work for any size of the screen.

image

**Review by humphd — APPROVED** [review]
Alright, let's do it.  This improves things for sure.

**Review by menghif — APPROVED** [review]
This seems to have fixed #3442 as well
IMG_810D6883329D-1

**Pull request merged**
