### PR TITLE
[next] Fixes #1612 Ported BannerDynamicItems component from Gatsby to Next

### LINKED ISSUE #1612: [next] Port BannerDynamicItems to NextJS
**What would you like to be added**:
BannerDynamicItems needs to be ported to NextJS. This needs to go in after #1492.

**Why would you like this to be added**:
Gotta port this to NextJS.

### PR DESCRIPTION
**Pull request by chrispinkney**
## Issue This PR Addresses
Fixes #1612

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI
- [x] **Next.JS Port** 

## Description
This PR ports the BannerDynamicItems component from Gatsby to NextJS. I used the `<Link>` component from NextJS and an anchor tag to style the actual link itself.

We do things differently in the [Footer](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/next/src/components/Footer.tsx) component so I'm curious to see what others think about this change.

(@humphd) I also added in a mocked `<DynamicImage>` component (as `<BannerDynamicItems>` [relies on](https://github.com/Seneca-CDOT/telescope/issues/1492) `<DynamicImage>`). Let me know if you want me to remove that part too, just trying to avoid something screaming at me for as long as possible.

#### How to test
Simply import and render the component wherever you like (I rendered mine in `Banner.tsx`):

```TS
import BannerDynamicItems from './BannerDynamicItems';
<BannerDynamicItems />
```

firefox_2021-01-26_16-41-02

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by Metropass** [comment]
Looks good! I also tested it without `<DynamicImage>` and Next does scream at me. 
I think we should keep the module, at least until we get the component ready so that we won't confuse any new devs.
If we have to remove it, maybe we should place a note or comment about it

**Review by Metropass — APPROVED** [review]
Looks great, per my original comment, if we have to remove `<DynamicImage>`, just make a note of it in the code as a comment

**Review by rjayroso — APPROVED** [review]
Tested, looks good to me!

**Review by HyperTHD — COMMENTED** [review]
Looks good. I'm not sure about the <a> tag in line 52. According to the next docs, when passing a styled anchor tag to a link component, you need to use the passHref attribute. 

From the next docs for the link component:

Link usage

**Comment by chrispinkney** [comment]
> 
> 
> Looks good. I'm not sure about the tag in line 52. According to the next docs, when passing a styled anchor tag to a link component, you need to use the passHref attribute.
> 
> From the next docs for the link component:
> 
> Link usage.
> 
> I may be wrong though. Outside of this, LGTM

I think that's only for when the child of a `<Link>` component is a custom component (which an anchor tag is not 😆)

**Pull request merged**
