### PR TITLE
added elasticsearch.md reference to main contributing readme

### PR DESCRIPTION
**Pull request by chrispinkney**
## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [X] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

While spending some time exploring the files in `./docs`, I noticed that the `elasticsearch.md` (which was only created recently) was never linked to in any document, so I added it as a technology in the main `CONTRIBUTING.md` readme.

This might be intentional or maybe I missed something. If so, let me know please and thanks!

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [X] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — DISMISSED** [review]
Nice find.  Are there other places where we should mention it?  Probably most of the references to Redis could use a link to elastic too?

**Review by manekenpix — DISMISSED** [review]

**Comment by chrispinkney** [comment]
> Probably most of the references to Redis could use a link to elastic too?

Agreed, my mistake. I'll add some more references while I'm at it and send another PR. Hold off on this for now please and thanks!

**Comment by chrispinkney** [comment]
"yeah, the web ui is not your friend, it's better not to trust it" -Josue, 2020

Words to live by. Sorry guys one sec.

**Comment by chrispinkney** [comment]
Many thanks to @manekenpix for holding my hand through a rebase... despite just doing the lab on rebasing.

**Review by humphd — APPROVED** [review]

**Review by manekenpix — APPROVED** [review]

**Review by cindyledev — APPROVED** [review]

**Pull request merged**
