### PR TITLE
Setup Mermaid for Docusaurus

### PR DESCRIPTION
**Pull request by tcvan0707**
## Issue This PR Addresses

Fixes issue #2960 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR is going to set up [Mermaid](https://github.com/sjwall/mdx-mermaid) for our Docusaurus. The picture below is a sample to proof that Mermaid is working in our docs
image

## Steps to test the PR

- Change the current directory to `src/docs`: `cd src/docs/`
- Run `pnpm start`
- Go to `localhost:4631` on the web browser

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by cindyledev — APPROVED** [review]
I've been waiting for this! You have no idea.

After following your steps, I added

````md
```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
````

to `src/docs/docs/overview.md` just to test it out and it worked!
2022-03-09 12_52_11-Window

I can finally unblock #2880 now

**Comment by tcvan0707** [comment]
> I've been waiting for this! You have no idea.
> 
> After following your steps, I added
> 
> ```lisp
> ```mermaid
> graph TD;
>     A-->B;
>     A-->C;
>     B-->D;
>     C-->D;
> ```
> ```
> 
> to `src/docs/docs/overview.md` just to test it out and it worked! 2022-03-09 12_52_11-Window
> 
> I can finally unblock #2880 now

If we want to make a graph, there is a keyword `graph` we have to specify, along with the `TD` is the direction where the graph will go, TD is **Top Down** I believe, I also tried `LR` (Left to Right) and `RL` (Right to Left). Hope this will help you!! 😊

**Comment by tpmai22** [comment]
@tcvan0707 thank you for throwing those information in. That absolutely help me if I want to contribute in the future !

**Review by menghif — APPROVED** [review]
Very useful!

**Review by Kevan-Y — APPROVED** [review]
Nice feature

**Pull request merged**
