### PR TITLE
Fix: 2229 Updating  src/api/posts/Readme.md to fix typo

### LINKED ISSUE #2229: Post microservice's README has "Image Service" as title
The [README](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/posts/README.md) document in the `Posts` microservice has **Image Service** as title. This should be changed to **Posts Service**.

### PR DESCRIPTION
**Pull request by shubhammehra4**
## Issue This PR Addresses
Fixes #2229 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Fixed a typo from "Image Service to Posts Service" in the Readme file.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by PedroFonsecaDEV** [comment]
Hi @shubhammehra4 
Thanks for the PR. 
Please, next time, reach us commenting on the issue you are willing to solve before submitting a PR. To avoid more than one person working on the same issue.
Thanks.

**Review by PedroFonsecaDEV — APPROVED** [review]
LGTM.

**Comment by shubhammehra4** [comment]
@PedroFonsecaDEV surely I will

**Review by manekenpix — APPROVED** [review]
LGTM :+1:

**Pull request merged**
