### PR TITLE
Fix #44: Added Github Actions CI for redis run, npm install and test

### LINKED ISSUE #44: Set up CI/CD pipeline (GH Actions)
Set up the base pipeline as per comment (https://github.com/Seneca-CDOT/telescope/issues/6#issuecomment-549646158) at Github actions.

### PR DESCRIPTION
**Pull request by sukhbeersingh**
This PR adds a basic Github Action to do the following

1. Checkout the code from git
2. Run docker image of redis
3. Run basic npm commands: `npm ci`, `npm run eslint` and `npm run jest`

This is triggered every time someone makes a push to the master branch. I think that should be enough for now. We can probably add checks on each pull request made to the master, I am not sure if that'd be too much. Thoughts?

I tested on my repo. The telescope repo doesn't show an Actions tab. It is be free for all public repositories. Maybe when the code is pushed the button appears?

### CODE REVIEW

**Comment by kartik-budhiraja** [comment]
@sukhbeersingh  As GH actions is in beta stage, we have to sign up for it and then GH sends an email for confirmation and the actions tab shows up.
I guess you would need admin access for signing up. 
cc:@humphd can help us out here.

**Comment by humphd** [comment]
@sukhbeersingh @kartik-budhiraja I tried today to sign up with this CDOT org, and it complained.  I've asked on twitter for clarification about what's up with this account type--we may not be able to do it without a personal account during the beta.  Let's hope that's wrong...

**Comment by humphd** [comment]
@sukhbeersingh I spoke with GitHub support, and the account type that CDOT has can't be used with the GitHub Actions Beta program :(

I'm going to close this, but honour your work toward the project (please submit as part of your 0.3).  Did you want to try working on another CI provider?

**Comment by sukhbeersingh** [comment]
@humphd I see that this repo now has the Actions tab. Do we want to try setting up Github Actions then?

**Comment by humphd** [comment]
@sukhbeersingh I clicked on the link, and here is what I see:

Screen Shot 2019-11-16 at 1 01 49 PM

:(

**Pull request closed without merging**
