### PR TITLE
Fixes #1841 - Fetch all contributors and fix contribution count plural

### LINKED ISSUE #1841: The about page only shows a certain number of contributors.
**What happened**:
The contribution hook only fetches 29 contributors. 
**What should have happened**:
Telescope right now has 111 contributors

### PR DESCRIPTION
**Pull request by DukeManh**
## Issue This PR Addresses
Fixes #1841

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by birtony — CHANGES_REQUESTED** [review]
Your PR looks good to me @DukeManh! Could you, please, use a `fixes #1841` keyword in the PR description to link it to the issue it fixes? It would also be nice to set appropriate labels, which would allow categorizing this PR in our changelog when we do the next release.

**Comment by DukeManh** [comment]
@birtony +1 Thank you for the review.

**Comment by birtony** [comment]
> 
> 
> @birtony +1 Thank you for the review.

The keyword needs to go into the PR description @DukeManh

**Review by birtony — APPROVED** [review]
I've just updated it for you this time. This keyword only has a special meaning when it's used in the PR description, keep it in mind for your future PRs 👍

**Review by PedroFonsecaDEV — CHANGES_REQUESTED** [review]
Waiting for @birtony requirements to be met.

**Review by PedroFonsecaDEV — DISMISSED** [review]

**Comment by DukeManh** [comment]
Thank you @PedroFonsecaDEV && @birtony.

**Review by birtony — APPROVED** [review]

**Review by PedroFonsecaDEV — APPROVED** [review]

**Comment by humphd** [comment]
Let's get a new issue to fix the use of useSWRIntinite and the `any` type, both of which shouldn't be in this code.

**Pull request merged**
