### PR TITLE
Supabase docs

### LINKED ISSUE #2966: [X-Post][Satellite] Document JWT_SECRET with more information (README.md)
**Where is the problem?**

- [ ] Link **comment/file/somewhere else**
- [ ] Screenshot

**What exactly is wrong:**
We need to document more info about our recently updated JWT_SECRET and how it integrates with Supabase on telescope/satellite

**What should it be instead:**

### PR DESCRIPTION
**Pull request by joelazwar**
## Issue This PR Addresses
Fixes #2966

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Started initial docs for Supabase.

WIP !! more info to be added soon

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by cindyledev** [comment]
Can we also include stuff from the wiki? https://github.com/Seneca-CDOT/telescope/wiki/Supabase-documentation

**Comment by humphd** [comment]
The wiki was @sirinoks's idea for creating a staging area for docs, where we could iterate more quickly.  People have been extremely slow to help with this, but that was the idea.  The end goal is to move that doc over to `src/docs`, yes.

**Comment by humphd** [comment]
This feels stalled, can we reboot it?

**Comment by tcvan0707** [comment]
@joelazwar are you okay if i am going to pick this up?

**Comment by joelazwar** [comment]
@tcvan0707 go for it. you could pick up the work from my branch if you'd like

**Comment by JerryHue** [comment]
If @tcvan0707 is going to pick this up, should we close this and let him open a new PR?

cc @joelazwar

**Comment by tcvan0707** [comment]
> If @tcvan0707 is going to pick this up, should we close this and let him open a new PR?
> 
> cc @joelazwar

We can close this one, I will get all the changes from Joel, and open the new PR.

**Pull request closed without merging**
