### PR TITLE
Issue 3428: Search by Title in Advanced Search

### LINKED ISSUE #3428: Add Title field for Advance Search
**What would you like to be added**:
search by title UI

**Why would you like this to be added**:
We already have the backend for the title in the advanced search. We should add the UI for this and wire it up so our users can utilize the option when searching.

### PR DESCRIPTION
**Pull request by AmasiaNalbandian**
## Issue This PR Addresses
Fixes #3428 

## Type of Change
- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Added the input UI for title in the advanced search tray. In addition, I added code to allow the search by title. 

## Steps to test the PR
1. `pnpm i`
2. `cp config/env.staging .env`
3. `pnpm run dev`

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by TDDR — APPROVED** [review]
Works great. I'm curious what part takes care of the ordering of the search results? I like how it gives the most exact suggestion at the top and then matches single keywords as well. 

image

image

image

**Review by rclee91 — APPROVED** [review]
Tested locally.
image

**Comment by rclee91** [comment]
> Works great. I'm curious what part takes care of the ordering of the search results? I like how it gives the most exact suggestion at the top and then matches single keywords as well.

ElasticSearch does that. it gives its results a score based on relevancy and puts the top scorers at the front

**Comment by AmasiaNalbandian** [comment]
> > Works great. I'm curious what part takes care of the ordering of the search results? I like how it gives the most exact suggestion at the top and then matches single keywords as well.
> 
> ElasticSearch does that. it gives its results a score based on relevancy and puts the top scorers at the front

@TDDR @rclee91 Roxanne is correct - however we could manipulate it so that we say how to order it. Before it was order by date, but now because we have more of an AND then OR operation going, it does that order instead.

**Pull request merged**
