### PR TITLE
Fixes #1009 Switch to 403 from 401 for login failed check

### LINKED ISSUE #1009: Switch to 403 from 401 for login failed check
In Login.jsx:

```js
        if (!response.ok) {
          // Not an error, we're just not authenticated
          if (response.status === 401) {
            return;
          }
          throw new Error(response.statusText);
```
We spam the console with an error if you're not logged in because we're checking for 401 vs. 403.

### PR DESCRIPTION
**Pull request by Metropass**
## Issue This PR Addresses
Fixes #1009

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Changed from Status Code 401, to Status Code 403 within Login.jsx

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by Grommers00** [comment]
Hey Metropass, great  job on the PR :D. Do you have the issue # it's supposed to be attached too?

**Comment by c3ho** [comment]
Hi @Metropass, thank you for your PR. A few things I want to address
We have a template when submitting a PR, which makes the whole process a lot easier when we're reviewing the PR:
- When submitting this PR its best to title it `Closes #(issue number here)` or `Fixes #(issue number here)` that way it will automatically link to the issue request. At the moment I have no idea which this fixes or I'll have to go through all the issues to find more information on the particular issue this PR addresses
- Please give a quick description of the issue this PR addresses to give us an overview of the issue at hand 
- Please fill out the description to describe the fix you implemented to address the issue
- Lastly please check off the Checklist for things that apply to this PR or why they do not.

So for example: 
1. instead of `Updated Login.jsx, fixed 401 issue` It should be `Fixes #1009 Switch to 403 from 401 for login failed check`. 
2. Then in the `Issue this PR Addresses` area just say `Fixes #1009`. 
3. Mark off `Bugfix`. 
4. In `Description` Changed 401 code to 403 in Login.jsx. 
5. Perhaps even include a screenshot of the old error vs new error. 
6. Mark off `Quality` and `Screenshots(if you included screenshots)`

**Comment by Metropass** [comment]
> 
> 
> Hey Metropass, great job on the PR :D. Do you have the issue # it's supposed to be attached too?

Oh yes! Sorry, it's issue #1009!

**Comment by Grommers00** [comment]
> > Hey Metropass, great job on the PR :D. Do you have the issue # it's supposed to be attached too?
> 
> Oh yes! Sorry, it's issue #1009!

Perfect :). So yeah to add to what you c3ho said above, if you look at how you commented the "#1009" it actually linked the issue to this PR. So if you add it to the title of your pull request git hub does this neat thing where it gives us (the reviewer) ability to track what issue you were able to fix :). 

You just have to put an 'x' in the box in the template as well when creating the PR and it shows up as a marked checkbox, (uses markdown). 

Awesome job though! were you able to run telescope locally?

**Comment by Metropass** [comment]
> 
> 
> > > Hey Metropass, great job on the PR :D. Do you have the issue # it's supposed to be attached too?
> > 
> > 
> > Oh yes! Sorry, it's issue #1009!
> 
> Perfect :). So yeah to add to what you c3ho said above, if you look at how you commented the "#1009" it actually linked the issue to this PR. So if you add it to the title of your pull request git hub does this neat thing where it gives us (the reviewer) ability to track what issue you were able to fix :).
> 
> You just have to put an 'x' in the box in the template as well when creating the PR and it shows up as a marked checkbox, (uses markdown).
> 
> Awesome job though! were you able to run telescope locally?

Yes! It ran locally on my machine, and I fixed the comments just like you guys mentioned. Thank you so much for the help, I'm still new to this :)

**Comment by c3ho** [comment]
I'm going to edit a few things, could you include a screenshot of the before error and a screenshot of the after(with your fix) as well?

**Comment by Metropass** [comment]
> 
> 
> I'm going to edit a few things, could you include a screenshot of the before error and a screenshot of the after(with your fix) as well?

Yes, I'll do so later tonight, and include the screenshots, thanks again :)

**Comment by c3ho** [comment]
Np, thanks for the PR!

**Review by Grommers00 — APPROVED** [review]
Looks good!

**Review by manekenpix — APPROVED** [review]
:+1:

**Review by humphd — APPROVED** [review]
This is great, welcome to Telescope, Mo!  One thing I'll get you to do differently next time is to do this work on a branch vs. your `master`.  We'll talk more about that next week.

Until then, looks good to me.

**Review by cindyledev — APPROVED** [review]
Congratulations on your first PR here, @Metropass !

**Pull request merged**
