### PR TITLE
Fixes #2039: BlogSpot images are scaled down the same as inline images

### LINKED ISSUE #2039: BlogSpot images are scaled down the same as inline images
**What happened**:
Blogspot post images are scaled down to 32px along with inline images.
The latest iteration of our solution (see PR [here](https://github.com/Seneca-CDOT/telescope/pull/1910)) for issues: #1791 and #1412 works as intended (reduce the size of inline images without affecting the rest of the images in the post) except for Blogspot post images; *all* the images within a Blogspot post are being reduced to 32px.

**What should have happened**:
Blogspot post images should be unaffected, yet at the same time, inline images should be scaled down to 32px.

From my understanding after working on #1791, both Blogspot images and regular inline images both are structured like so:  
`div > a > img` - which means that if you apply CSS to scale down inline images, you would also affect Blogspot images and vice versa. 

**How to reproduce it (as precise as possible)**:
To see the *intended effect* of scaled-down inline images, navigate to the SearchPage and select the filter type `post` and search for "validation.js". Here you will see Tony Vu's GitHub avatar scaled down and inline with his GitHub profile link.

To see the bug, navigate to the SearchPage and select the filter type `author` and view Krystyna Lopez's BlogSpot blogs. Here you will see all the images within her post unintentionally scaled down to 32px.

**Anything else we need to know?**:
As Huy Nguyen mentions [here ](https://github.com/Seneca-CDOT/telescope/issues/1791#issuecomment-784429056) and [here](https://github.com/Seneca-CDOT/telescope/pull/1910#issuecomment-797540783), "Using `telescope-post-content div` will also affect those blogs from Blogspot."

**Environment**:
- OS: Windows
- Browser: Chrome

### PR DESCRIPTION
**Pull request by rjayroso**
## Issue This PR Addresses
Fixes #2039 

## Type of Change
- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Added custom styling for blogspot images

Small CSS addition to fix the thorn that is the BlogSpot issue (images being scaled down to fit inline for BlogSpot blogs). I have added CSS to style **only** the BS images with the new element decorators via `.telescope-post-content.is-blogspot img { ... }`

| Before |
| :---: |
| image |
| **After** |
| image |

## How to Test
1. Check files changed for syntax errors and/or improvements to the code
2. View the deployment and quickly preview the homepage timeline for any possible visual styling bugs
3. Navigate to the search page
4. Search the term `validation.js` under the `Post` filter
    - Make note that the inline images are still inline (working as intended)
5. Search the name "Krystyna" under the `author` filter (she uses the BlogSpot platform)
    - See how the images are no longer inline and are now being displayed as intended

## Checklist
- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by HyperTHD — DISMISSED** [review]
Looks and works great

**Review by PedroFonsecaDEV — DISMISSED** [review]
LGTM.

**Review by humphd — APPROVED** [review]
Awesome to see this happening.  A long journey to get to this solution, but I think it's going to be so useful for lots of bugs.

**Comment by rjayroso** [comment]
Squashed and rebased

**Review by humphd — APPROVED** [review]

**Pull request merged**
