### PR TITLE
Add autodeployment server to the status checks

### LINKED ISSUE #2663: Add autodeployment server to Status list for services
Right now the autodeployment server is down (https://dev.telescope.cdot.systems/deploy is 502).  If I go to https://dev.api.telescope.cdot.systems/v1/status, at the bottom, we have a bunch of status checks for our services.  However, the autodeployment server isn't there.

Let's add it so we can see when it fails.

### PR DESCRIPTION
**Pull request by JiaHua-Zou**
## Issue This PR Addresses
Fixes #2663 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Add an status checks for the auto deployment server.

## Screenshot
image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by Kevan-Y — APPROVED** [review]
LGTM

**Review by tcvan0707 — DISMISSED** [review]
I just tested this locally, it seems to work fine on my machine.

**Comment by humphd** [comment]
@JiaHua-Zou I want to have you all avoid merging `master` into your branch.  See how you now have 2 commits? https://github.com/Seneca-CDOT/telescope/pull/2670/commits. One of them is a merge commit, which we don't want.  Instead, you need to rebase on `master`.

Please read https://github.com/Seneca-CDOT/telescope/blob/master/docs/git-workflow.md#squashing-commits and fix.

**Review by humphd — CHANGES_REQUESTED** [review]
Waiting on proper rebase/squash, code looks great.

**Review by Andrewnt219 — APPROVED** [review]
Tested on local 👍.

**Review by tcvan0707 — APPROVED** [review]

**Review by Andrewnt219 — APPROVED** [review]

**Review by humphd — APPROVED** [review]

**Pull request merged**
