### PR TITLE
Input Validated with Ajv

### LINKED ISSUE #1277: Validate input on REST APIs with Ajv
We don't currently validate input properly to our REST API endpoints.  Let's add [Ajv](https://ajv.js.org/) to our routes that accept data, and get schema-based validation happening on the data.

Our search is one place where we accept data, and others I can think of include:

- https://github.com/Seneca-CDOT/telescope/blob/d358f2e0950d071cbf854f1e6e02dd959380456d/src/backend/web/routes/feeds.js#L76

- https://github.com/Seneca-CDOT/telescope/blob/d358f2e0950d071cbf854f1e6e02dd959380456d/src/backend/web/routes/feeds.js#L55

- https://github.com/Seneca-CDOT/telescope/blob/d358f2e0950d071cbf854f1e6e02dd959380456d/src/backend/web/routes/feeds.js#L99

### PR DESCRIPTION
**Pull request by jiyoungsin**
Thanks for sending a pull request!
- if this is your first time, please ensure you have read through our contributor guide: https://github.com/Seneca-CDOT/telescope/blob/master/docs/CONTRIBUTING.md

## Issue This PR Addresses

1. Automatically close the issue when this PR is merged
    USAGE: Fixes #1277 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This new feature uses the library Ajv, Another JSON schema Validator, to validate the body of the request.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
Is this a multi PR to address the issue? I thought this was assigned to @tonyvugithub

**Comment by jiyoungsin** [comment]
@c3ho yes, thank you for pointing this out. I was just about to ask if I can give it a shot as well.

**Comment by c3ho** [comment]
@jiyoungsin you should speak with @tonyvugithub about that either on slack or on issue. There's a few routes... so if he hasn't worked on all of them yet, perhaps you guys could split it. I would highly suggest submitting PRs for only things you are assigned to or asked to work on.

**Comment by tonyvugithub** [comment]
@c3ho : I completed it but have not submitted a PR yet.  I think @jiyoungsin need to look elsewhere as there's not much to split.

**Comment by c3ho** [comment]
@tonyvugithub No worries. I'll be closing this PR then. @jiyoungsin You mentioned you wanted to work on https://github.com/Seneca-CDOT/telescope/issues/1286. I would suggest concentrating on that or another issue that hasn't been taken yet.

**Comment by jiyoungsin** [comment]
This issue seemed like a quick fix that could test my abilities and thought I would give it a try. Seems like some of my test are failing anyways. Thanks for keeping me updated of the situation guys, Happy Hacking 👍

**Comment by tonyvugithub** [comment]
@jiyoungsin : thank you for understanding. My PR just passed the CI tests so this issue should be taken care of.

**Pull request closed without merging**
