### PR TITLE
remove telescope mobile app

### PR DESCRIPTION
**Pull request by manekenpix**
## Issue This PR Addresses

Part of #3800 

## Description
This PR removes Telescope's mobile app.

## Steps to test the PR

N/A

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by cindyledev — DISMISSED** [review]

**Review by humphd — APPROVED** [review]
Getting slimmer every day, love it!

**Comment by humphd** [comment]
There is probably some mobile app setup/build/project I can delete now, right?  I don't remember the details.  Anyone remember what I setup?

**Review by Kevan-Y — APPROVED** [review]
Approved.
Some deployments secretly token with EXPO in GitHub action (I think) can be deleted.
The Expo project that was hosting the app.

**Comment by humphd** [comment]
I've deleted the Expo project and secret, thanks @Kevan-Y!

**Pull request merged**
