### PR TITLE
Fixes #530: Adding list of domains to docs

### LINKED ISSUE #530: Create domains for staging and production
**What would you like to be added**:

We need domains for hosting our staging and production deployments.  @ctyler has said we can run these off of the cdot.systems domain.  We need to create both of:

1. telescope.cdot.systems for production
1. dev.telescope.cdot.systems for staging

**Why would you like this to be added**:

We're hoping to get things deployed during January, and we need a way to get at our systems via a domain.  We also need to get moving on SSL, which will require public domain names. #519 is related to this.

@ctyler what needs to happen for this to move ahead?  @manekenpix, do you have sufficient rights, or does Chris need to do it?

### PR DESCRIPTION
**Pull request by cindyledev**
## Issue This PR Addresses
Fixes #530 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR adds the staging and production domains, and original Planet URL to our docs. Feel free to let me know what other domains or URLs we should add. Maybe this can be morphed to add endpoints as well.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by manekenpix** [comment]
@humphd yes, let's do that. Once #649 lands, we can have deployment documentation that'll include information about all the domains related to Telescope.

**Comment by cindyledev** [comment]
This is turning out to not be a 5 minute fix

**Comment by humphd** [comment]
@cindyledev your part of this is 5 mins.  I'm saying to @manekenpix that he can take over this document and change it into our deployment docs when he and @miggs125 do that later.  This lets you land this sooner, and we'll deal with it be orphaned that way.

**Comment by humphd** [comment]
So to be clear: let's add the missing domains from Zeit to this list, and login, and we can merge this.

**Comment by cindyledev** [comment]
I made the changes requested and removed the OG Planet URL because it's dead
RIP Planet O7

**Pull request merged**
