### PR TITLE
Fixes 2618 - Refactored search to use advanced route

### LINKED ISSUE #2618: Refactor the search to use the advanced search route
**What would you like to be added**:
[The advanced search route backend is being implemented](https://github.com/Seneca-CDOT/telescope/pull/2617). However the react context written for the search needs to be refactored to change the route we push. Right now it's very static and not too flexible.  

**Why would you like this to be added**:
Refactor all of the search queries to use the one query we have. the new advancedsearch is quite flexible in what we can search for posts.

### PR DESCRIPTION
**Pull request by AmasiaNalbandian**
## Issue This PR Addresses
Fixes #2618 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
In https://github.com/Seneca-CDOT/telescope/pull/2617 we added an advanced route. The advanced route is more flexible for search terms and capabilities. In this PR I changed the route used in the search results so that we use the new "advanced" route. In another PR I will clean up the regular search as we are now leveraging the more advanced route - and will be the main route meaning no more `/advanced` it will be `/`

## Steps to test the PR
- `cp config/env.development .env`
- `docker-compose --env-file ./config/env.development up --build search elasticsearch redis posts nginx planet`

1. Go to search and select author search an author - look in the network tab for dev tools, you will see the results coming from the new route.
2. Do the same with posts.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by rclee91 — COMMENTED** [review]
Is this PR needed? Cause I noticed you have `SearchResults.tsx` changed in #3164 as well

**Comment by AmasiaNalbandian** [comment]
> Is this PR needed? Cause I noticed you have `SearchResults.tsx` changed in #3164 as well

This is the smaller version of 3164.... This PR just changes the route to use, the other PR also ends up changing the route because we clean up all the other route and make advanced the main route.

**Comment by rclee91** [comment]
> > Is this PR needed? Cause I noticed you have `SearchResults.tsx` changed in #3164 as well
> 
> This is the smaller version of 3164.... This PR just changes the route to use, the other PR also ends up changing the route because we clean up all the other route and make advanced the main route.

It still doesn't make sense to me why we can't do the change in just one PR. 
I'd like the opinion of another reviewer.

**Comment by tpmai22** [comment]
This seem arguable @Kevan-Y what do you think about this ?

**Comment by AmasiaNalbandian** [comment]
closing this - will just resolve in the other PR

**Pull request closed without merging**
