### PR TITLE
Fix issue #339 and improve CSS

### PR DESCRIPTION
**Pull request by aprilllllllll**
What changed:
- Based on suggestions from issue #339 
- Update styles for menu bar.
- Changed paddings for some elements.
- Changed font family for content.

### CODE REVIEW

**Comment by cindyledev** [comment]
Also, I noticed you have this on your master branch and it's currently passing both checks. Ideally, I would ask you to put this on its own branch and request to push to master but something is wrong with our master branch and if you create a new branch for this, it will fail the tests...

**Comment by aprilllllllll** [comment]
Sorry, I think I did something wrong when it shows conflict.

**Comment by aprilllllllll** [comment]
> Also, I noticed you have this on your master branch and it's currently passing both checks. Ideally, I would ask you to put this on its own branch and request to push to master but something is wrong with our master branch and if you create a new branch for this, it will fail the tests...

Sorry, I think I did something wrong to dismiss the review

**Comment by humphd** [comment]
Why is this coming from your `master` branch vs. a topic branch?

Also, I don't think it's doing everything that I discussed in #339, for example, constraining the width when the window is really wide.  Also the titles/headings seem to have been affected by these changes.

Screen Shot 2019-12-05 at 7 32 05 PM

**Comment by aprilllllllll** [comment]
this PR has some issues so I move it to #473

**Pull request closed without merging**
