### PR TITLE
Issue 2691 - Build dashboard error resizing

### LINKED ISSUE #2691: Resizing Build Dashboard window causes error
When I resize the build dashboard window, I get this error:

```
Uncaught TypeError: Cannot read properties of null (reading 'classList')
    at navbarColorOnResize (material-dashboard.min.js?v=3.0.0:413:24)
```

Screen Shot 2022-01-20 at 9 53 24 AM

### PR DESCRIPTION
**Pull request by AmasiaNalbandian**
## Issue This PR Addresses
Fixes #2691 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
When you resize the window some of the css that's applied through javascript is looking for a value that's not there. To avoid the issue I used optional chaining. If the classList does not exists, it will not show the error and skip over it.

image

## Steps to test the PR
1. `cp config/env.staging .env`
2. `cd ./src/api/status`
3. `pnpm dev`
4. Navigate to [port ](http://localhost:1111/v1/status/build)
5. To replicate the issue, you resize the page here, please open your dev tools and navigate to console to check the error is no longer there. 

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by aserputov** [comment]
I checked this on my local machine, and yes, it looks like this fixes the issue.

**Comment by aserputov** [comment]
@AmasiaNalbandian rebase it please and I will approve.

**Comment by humphd** [comment]
Why don't you fix it upstream while you're at it?

https://github.com/creativetimofficial/material-dashboard/blob/66716686d10a8f1ed754f93bb52b3a922db1ffcf/assets/js/material-dashboard.js#L626

**Comment by humphd** [comment]
@AmasiaNalbandian please rebase this so it doesn't include a merge of `master`.

**Review by aserputov — APPROVED** [review]

**Review by manekenpix — APPROVED** [review]

**Comment by AmasiaNalbandian** [comment]
> Why don't you fix it upstream while you're at it?
> 
> https://github.com/creativetimofficial/material-dashboard/blob/66716686d10a8f1ed754f93bb52b3a922db1ffcf/assets/js/material-dashboard.js#L626
filed: 
https://github.com/creativetimofficial/material-dashboard/issues/183

**Pull request merged**
