### PR TITLE
Add missing environment var

### LINKED ISSUE #3645: Supabase console can't connect to backend
I'm trying to use the Supabase console at https://supabase.telescope.cdot.systems.  It's not able to connect to the backend:

Screen Shot 2022-09-05 at 9 10 31 AM

In the logs, I notice that it's trying to hit http://localhost:8000/rest/v1/, which is obviously wrong.  There must be some new config setting that needs to be updated?

### PR DESCRIPTION
**Pull request by Kevan-Y**
## Issue This PR Addresses
Fixes #3645

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Could be related to the change on Supabase side, since we are pulling the latest image. Now we might need to provide `SUPABASE_REST_URL`
see discussion: https://github.com/Seneca-CDOT/telescope/issues/3645#issuecomment-1238761872

Might be the solution for this, or not😅

### Note: 
Not sure if testable locally. 

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — APPROVED** [review]
This makes sense to me, let's try it.

Thanks for jumping on this @Kevan-Y!

**Review by cindyledev — APPROVED** [review]

**Comment by humphd** [comment]
I'll file a follow-up on the Vercel failure, which looks unrelated to this.  @Kevan-Y go ahead and merge this when you are ready, and let's see what Staging does with it.

**Comment by humphd** [comment]
Filed https://github.com/Seneca-CDOT/telescope/issues/3650

**Comment by humphd** [comment]
I notice that others had this issue too, and https://github.com/supabase/supabase/pull/7824 seems to be one fix.  Do we have this version of the studio container deployed?

**Pull request merged**
