### PR TITLE
Fix: issue 1588 - Update bull board and highlight.js dep

### PR DESCRIPTION
**Pull request by yuanLeeMidori**
## Issue This PR Addresses

Fixes: #1588 
Related: #1592 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

bull-board 0.9.0 has highlight version 9 dependency. To fix issue #1588, we need to update bull-board.

image

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by birtony** [comment]
highlight.js is already updated @yuanLeeMidori :)

**Review by birtony — APPROVED** [review]
LGTM

**Review by humphd — APPROVED** [review]

**Review by birtony — CHANGES_REQUESTED** [review]
@yuanLeeMidori you need to do a rebase instead of merging the master branch in, please

**Comment by yuanLeeMidori** [comment]
@birtony sorry, I didn't wanna dismiss the reviews so I use `rebase` button on github UI. Should I do rebase on my local instead?

**Review by birtony — APPROVED** [review]

**Review by chrispinkney — APPROVED** [review]

**Pull request merged**
