### PR TITLE
 XML to JSON parser #16

### PR DESCRIPTION
**Pull request by ImmutableBox**
**DO NOT MERGE WITHOUT THE APPROVAL OF** @c3ho. @c3ho is the person who originally wanted to work on this [issue](https://github.com/Seneca-CDOT/telescope/issues/16) first.
  
This code converts XML blog feeds to JSON. The purpose of this code is to get something started, this code is not concrete. Hopefully will be edited or trash by @c3ho (Waiting on feedback).

How to run the parser:
`npm install rss-to-json`
`node parser.js`

### CODE REVIEW

**Comment by humphd** [comment]
I like how you've jumped in and got something working that let's us move forward.  Good job.

I wonder if rss-to-json is the best choice for this.  It has no tests, and parsing RSS and ATOM feeds is tricky to get right.  I wonder if we should evaluate some other libs as well, maybe https://www.npmjs.com/package/feedparser, https://www.npmjs.com/package/rss-parser, https://www.npmjs.com/package/htmlparser2, etc.  I think the usual suggested one to use is https://www.npmjs.com/package/feedparser, which also provides streaming support (i.e., better for memory consumption).

**Comment by ImmutableBox** [comment]
Possible packages for parsing (I will be updating this list as more feedback comes in):
  
| Packages        | Note | Recommend? :x: :heavy_check_mark: |
| ------------- |:-------------:| -----:|
| [rss-parser](https://www.npmjs.com/package/rss-parser)    | I found the package rss-parser doesn't show all the contents of the blog (Link to my blog for more information: https://wordpress.com/block-editor/post/paulopensourceblog.wordpress.com/1137) It would be great if someone was able to get it working but it didn't for me @ImmutableBox |:x:|
| [rss-to-json](https://www.npmjs.com/package/rss-to-json)      | Does not work with ATOM feeds @ImmutableBox |  :x: |
| [feedparser](https://www.npmjs.com/package/feedparser) | Needs researching. (Feel free to contribute)     |   |
| [htmlparser2](https://www.npmjs.com/package/htmlparser2)| Needs researching. (Feel free to contribute) | |

Reviewing the code I committed https://github.com/Seneca-CDOT/telescope/commit/9fb7b34d91b6986cdfd64f257b6870a52872cccc, I found that package [rss-to-json](https://www.npmjs.com/package/rss-to-json) does not work with ATOM feeds, I will try researching the other packages suggested.

**Comment by c3ho** [comment]
@ImmutableBox I put up a simple PR with the prof's suggested library. Feel free to review it here #37, welcome any changes. 

I wrote a simple test.js file using the code below which you can use to play around.
```
const feedParser = require('./feed-parser.js');
const feed = feedParser('https://c3ho.blogspot.com/feeds/posts/default/-/open-source');
console.log(feed);
```

At the moment in the feed-parser.js file I put down console.log(items) , but it can also tracks metadata which you can check out with console.log(meta). The list is pretty exhaustive and can be found at the bottom of this document [here](https://www.npmjs.com/package/feedparser)

**Comment by humphd** [comment]
@ImmutableBox now that #37 is up, maybe we should close this, and iterate there?

**Comment by ImmutableBox** [comment]
Yup, I will close the pull request. Reference https://github.com/Seneca-CDOT/telescope/pull/37 for continuation.

**Pull request closed without merging**
