### PR TITLE
Commented Sign up button as a bandaid solution

### PR DESCRIPTION
**Pull request by Meneguini**
## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Bandaid solution until #2294 gets fixed.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by Meneguini** [comment]
@DukeManh @manekenpix @humphd

**Review by DukeManh — APPROVED** [review]

**Review by yuanLeeMidori — APPROVED** [review]
Author names are now correct.

**Comment by humphd** [comment]
Thanks.  I've filed #2296 to undo this once we get things sorted out.

**Comment by manekenpix** [comment]
I wonder if we should do a small release to add this to `prod`

**Pull request merged**
