### PR TITLE
Fixes #1270: Make searches sharable via URL

### LINKED ISSUE #1270: Make searches sharable via URL
Today I needed to go and look for blog posts students have written on Pandas.  I did a search, and got back my results.  Now I want to share that search and the results with a colleague.  There is no way to do this without telling them how to recreate the search.

A better solution would be to use the React routing and History API to push some state into the URL, so you get something like `https://telescope.cdot.systems/search?q=pandas` or something.  As I type, it should update the URL so it stays in sync with my search, but not in an annoying way so that we break the Back button.

When the search page is rendered, we should read out params from the URL if present, too.

### PR DESCRIPTION
**Pull request by jossiey**
## Issue This PR Addresses
fix #1270 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
feature1: URL synchronizes with keyword when typing in search page. After being submitted, URL shows https://telescope.cdot.systems/search?q=keyword&f=author
feature2:  When someone browser to the URL  https://telescope.cdot.systems/search?q=keyword&f=author, params: keyword and author are shown on the search box, and do a search.
The affection is shown here: https://jyangblogs.files.wordpress.com/2020/11/telescope-issue1270-author.gif?w=812

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by humphd** [comment]
It looks like this is failing to build:

```
failed Building static HTML for pages - 15.326s
--
00:14:36.174 | error Building static HTML failed for path "/search/"
00:14:36.187 | 6 \|     }
00:14:36.187 | 7 \|     if (isProduction) {
00:14:36.187 | >  8 \|         throw new Error(prefix);
00:14:36.187 | \| ^
00:14:36.187 | 9 \|     }
00:14:36.187 | 10 \|     throw new Error(prefix + ": " + (message \|\| ''));
00:14:36.187 | 11 \| }
```

You can test the build locally with `npm run build`.

**Review by humphd — COMMENTED** [review]
I think you'll need to use Gatsby's router vs. introducing a new one, see https://www.gatsbyjs.com/docs/routing/

**Comment by jossiey** [comment]
I added react-router-dom that I can use browserHistory, useHistory, and useLocation. I didn't find similar hook in Gatsby. And another thing is I think we are moving from Gatsby to Next.js,  is it better to use react-router-dom?

**Comment by humphd** [comment]
I think you do it via plugin in GatsbyJS, see https://www.gatsbyjs.com/plugins/gatsby-plugin-use-query-params/ and https://github.com/pbeshai/use-query-params.

Let's do this in GatsbyJS, and we'll find a parallel solution in next.js later.

**Pull request closed without merging**
