### PR TITLE
Fix #1496: Port GitHub Contributor Card to NextJS

### LINKED ISSUE #1496: [next] Port GitHubContributorCard/ to NextJS
https://github.com/Seneca-CDOT/telescope/tree/master/src/frontend/gatsby/src/components/GitHubContributorCard
**What would you like to be added**:
Port all components in GitHubContributorCard/ to NextJS
**Why would you like this to be added**:
Porting reason

### PR DESCRIPTION
**Pull request by joelazwar**
## Issue This PR Addresses

Fixes #1496  

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI
- [x] **Next**: Porting to NextJS

## Description

Ports GithubContributorCard Component from Gatsby to Next

Note: This Component is dependent on the hooks/use-telescope-contributor.js file (#1502)

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by tonyvugithub** [comment]
@joelazwar : Hi there, we are in the process of reviewing these migrated to Next PRs. Just wonder if you are still interested to work on this as we would like you to make some changes to your PR. Please let us know in case you decided to drop this then we can assign the issue to others. Thank you.

**Comment by joelazwar** [comment]
@tonyvugithub Hi Tony, currently occupied at the moment, feel free to assign this issue to others. same with #1529

**Comment by humphd** [comment]
https://github.com/Seneca-CDOT/telescope/pull/1555 adds the hook for this, so this should be straightforward to fix once that lands.

**Comment by tonyvugithub** [comment]
Closed due to merge of https://github.com/Seneca-CDOT/telescope/pull/1556

**Pull request closed without merging**
