### PR TITLE
Improved build log page for issue 2622

### LINKED ISSUE #2622: Build log claims to not be able to get build status when no build running
When there's no current build running, the build log page shows an error message:

Screen Shot 2021-12-16 at 9 54 31 AM

However, the problem isn't that it can't get build status, it's just that there is no `current` build running.  Let's improve this.

Also, ideally we should be showing details about the previous build, so if you come and the build finished 5 mins ago, it shows you that instead of nothing.

### PR DESCRIPTION
**Pull request by nguyenhung15913**
## Issue This PR Addresses
fixes #2622 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

- Made the message more clear if there is no current or previous build
- Displaying the previous build if there is one and there is no current build

## Screenshot
- No current or previous build
no-build
- No current build but there is a previous build
previous-build
- If there is a current build
current-build

## How to test locally
From the root directory
- Fetch these links <code>https://dev.telescope.cdot.systems/deploy/status</code> or <code>https://telescope.cdot.systems/deploy/status</code> instead of  <code>autodeploymentUrl('status')</code> in the<code>checkBuildStatus()</code> in <code>src/api/status/public/js/build-log/api.js</code>
- Copy the chosen link above to the array of <code>connectSrc</code> in <code>src\api\status\src\server.js</code> so that it won't have error related to CSP
- <code>cd ./src/api/status</code> and <code>pnpm run dev</code>. Then go to http://localhost:1111/v1/status/build.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — DISMISSED** [review]
I'm reworking this code in #2653 too, so we can take this and I can incorporate it into mine.

**Review by DukeManh — DISMISSED** [review]
I think this and #2665 will be improved in @humphd's PR.

**Review by TDDR — APPROVED** [review]
Just needs a rebase and you are good to merge

**Review by humphd — APPROVED** [review]

**Review by DukeManh — APPROVED** [review]

**Comment by nguyenhung15913** [comment]
Hi everyone, I just pressed the "update branch" something and it create this commit "23b0064", "Merge branch 'master' into issue-2622". is there any issue with it ? @humphd @DukeManh @TDDR

**Comment by humphd** [comment]
@nguyenhung15913 correct, we don't want to do this.  It creates a new merge commit, merging `master` _into_ your branch.  We never want to do this.  We want to merge your branch _into_ master.  To do this, we prefer rebasing and squashing.

**Comment by humphd** [comment]
See https://github.com/Seneca-CDOT/telescope/blob/master/docs/git-workflow.md#squashing-commits

**Comment by nguyenhung15913** [comment]
> @nguyenhung15913 correct, we don't want to do this. It creates a new merge commit, merging `master` _into_ your branch. We never want to do this. We want to merge your branch _into_ master. To do this, we prefer rebasing and squashing.

So now I have to revert the commit and rebase right ?

**Comment by humphd** [comment]
If you rebase, it should get rid of the merge commit.  But yes, you could also revert and then rebase.

**Comment by nguyenhung15913** [comment]
> 

awesome

**Review by humphd — APPROVED** [review]
Nice job

**Review by DukeManh — APPROVED** [review]

**Pull request merged**
