### PR TITLE
Fixes #1693: Audit of all asynchronous routes in backend folder

### LINKED ISSUE #1693: Fix async express middleware to properly handle error cases
We have a lot of express end-points that use `async` functions:

```
$ rg "async \(req"
src/backend/web/routes/stats.js
8:const statsRoute = (statsPeriod) => async (req, res) => {

src/backend/web/routes/planet.js
63:router.get('/', async (req, res) => {

src/backend/web/routes/query.js
9:router.get('/', validateQuery(), async (req, res) => {

src/backend/web/routes/user.js
19:router.get('/feeds', protect(), async (req, res) => {

src/backend/web/routes/posts.js
10:posts.get('/', validatePostsQuery(), async (req, res) => {
76:posts.get('/:id', validatePostsIdParam(), async (req, res) => {

src/backend/web/routes/feed.js
29:const feedRoute = (type) => async (req, res) => {
110:router.get('/opml', async (req, res) => {
145:router.get('/wiki', async (req, res) => {

src/backend/web/validation.js
5:  return async (req, res, next) => {

src/backend/web/routes/feeds.js
11:feeds.get('/', async (req, res) => {
35:feeds.get('/:id', validateFeedsIdParam(), async (req, res) => {
56:feeds.put('/:id/flag', protectAdmin(), validateFeedsIdParam(), async (req, res) => {
77:feeds.post('/', protect(), validateNewFeed(), async (req, res) => {
100:feeds.delete('/cache', protectAdmin(true), async (req, res) => {
112:feeds.delete('/:id', validateFeedsIdParam(), protect(), async (req, res) => {
133:feeds.delete('/:id/flag', protectAdmin(), validateFeedsIdParam(), async (req, res) => {
```

Express 4.x doesn't quite do `async` properly, in that you have to manually deal with the error case and call `next(err)` manually so that errors propagate down the middleware chain to the eventual default error handler.

The trick is to turn code like this:

```js
router.get('/:id', async (req, res) => {
  const { id } = req.params;
  const data = await getSomething(id);
  res.json(data);
});
```

into something like this:

```js
router.get('/:id', async (req, res, next) => {
  try {
    const { id } = req.params;
    const data = await getSomething(id);
    res.json(data);
  } catch(err) {
    next(err);
  }
});
```

Basically, we have to either deal with the error case in the route (i.e., don't let it go further in any code path), or call `next(err)` ourselves when things blow up.  I haven't looked at all of our routes to see if they need changing, so this is a bug to audit things.

### LINKED ISSUE #1928: Refactor all microservices error code to use Satellite's createError()
In #1927, we're going to expose `createError()` on Satellite.  Let's modify all of our Microservices code to use it vs. creating their own errors, and also remove `create-error` from their deps.

### PR DESCRIPTION
**Pull request by HyperTHD**
## Issue This PR Addresses
This PR closes #1693
This PR closes #1928 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

I've been wanting to close #1693 once we got our microservices fully launched, however, since the parser service won't be ready to launch yet, this issue is still relevant. I did an audit of all our asynchronous routes in our backend and had them all call the next middleware, passing in the error as well. Let me know if I missed any async routes and I'll update them quickly.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — COMMENTED** [review]
I don't think this PR is a good idea at this stage, since we're porting this code over to services (have done so already in most cases), and `src/backend` is going away.

**Comment by HyperTHD** [comment]
> I don't think this PR is a good idea at this stage, since we're porting this code over to services (have done so already in most cases), and `src/backend` is going away.

I thought so too, but until the parser tests are ready and the parser service is active, this PR is still relevant. The backend code will only get removed once that service is running

**Comment by chrispinkney** [comment]
Triage Meeting: If we're going to do this we should ensure that the changes that occur in the new microserivces also reflect the changes of this PR.

**Comment by humphd** [comment]
@HyperTHD as discussed on Tuesday, I don't want to land this without a follow-up issue/PR that makes sure we port these changes over to the new microservices, which share a lot of this code.  Can you update us on that so we can get this merged?

**Comment by HyperTHD** [comment]
@humphd @chrispinkney I did an audit of all the async routes in our microservices and many of them already use createError().

I did not update the user service's routes because I believe they use celebrate's errors. The parser service uses bull-board's route. Image, Auth, and Post services already uses createError(). Status and feed-discovery has no async routes. This left search, which I'm sending in a new commit. Our services are good atm and this can be merged

**Review by humphd — CHANGES_REQUESTED** [review]
Let's also change the image and feed-discovery services to remove `http-error` as a dep, and use `createError` from Satellite.

**Review by humphd — APPROVED** [review]

**Review by chrispinkney — APPROVED** [review]

**Pull request merged**
