### PR TITLE
Add link colors to palette; change link color in dark mode about page

### PR DESCRIPTION
**Pull request by yuanLeeMidori**
## Issue This PR Addresses
Fixes: #2048 
Related to: #2047 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Before: 
Screenshot_2021-04-05 About Telescope
Screenshot_2021-04-05 About Telescope(2)
After:
Screenshot_2021-04-05 About Telescope(1)
Screenshot_2021-04-05 About Telescope(3)

Basically, they're now using the same colors as posts, both light mode and dark mode. Please let me know if you prefer original colors for light mode about page.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by PedroFonsecaDEV** [comment]
@DukeManh  @izhuravlev Could you please review this one?

**Review by rjayroso — APPROVED** [review]
LGTM. Can definitely see the links/active links in dark mode better, IMO

**Comment by HyperTHD** [comment]
Dark mode looks good, but it's so difficult to see the links in light mode with the new link colors. If you could switch that back to what we had before, that'd be great

**Comment by yuanLeeMidori** [comment]
@HyperTHD Which one? Visited or unvisited one? They actually both pass WCAG AAA rating. Maybe I should make the font bolder?

**Comment by HyperTHD** [comment]
> @HyperTHD Which one? Visited or unvisited one? They actually both pass WCAG AAA rating. Maybe I should make the font bolder?

It's the not-visited color. It's very difficult for me to see without zooming up the page

**Review by birtony — COMMENTED** [review]
I also find the visited link colour on the light mode to be hard to see. Maybe we should use different colours for dark/light mode? @yuanLeeMidori

**Comment by yuanLeeMidori** [comment]
I've updated the link colors for light mode. This also affect post in timeline.

Post:
Screenshot_2021-04-06 Telescope

About:
Screenshot_2021-04-06 About Telescope

Please let me know your thoughts! @HyperTHD @birtony @PedroFonsecaDEV @rjayroso

**Review by HyperTHD — APPROVED** [review]
Much better. 
Nice job, @yuanLeeMidori. Get this rebased and you can merge

**Review by PedroFonsecaDEV — APPROVED** [review]

**Pull request merged**
