### PR TITLE
Custom onboarding Renovate configure

### LINKED ISSUE #2609: Switch to Renovate from Dependabot for pnpm support
Every dependabot PR is breaking, due to pnpm.  [Until dependabot has pnpm support, let's try renovate](https://github.com/dependabot/dependabot-core/issues/1736#issuecomment-950607617).

### PR DESCRIPTION
**Pull request by DukeManh**
Closes #2609, Renovate can be installed to Telescope [here](https://github.com/marketplace/renovate).

[WhiteSource Renovate](https://renovatebot.com)

Welcome to [Renovate](https://togithub.com/renovatebot/renovate)! This is an onboarding PR to help you understand and configure settings before regular Pull Requests begin.

🚦 To activate Renovate, merge this Pull Request. To disable Renovate, simply close this Pull Request unmerged.

---
### Detected Package Files

 * `docker/docker-compose.yml` (docker-compose)
 * `.gitpod.Dockerfile` (dockerfile)
 * `Dockerfile` (dockerfile)
 * `src/api/auth/Dockerfile` (dockerfile)
 * `src/api/feed-discovery/Dockerfile` (dockerfile)
 * `src/api/image/Dockerfile` (dockerfile)
 * `src/api/parser/Dockerfile` (dockerfile)
 * `src/api/planet/Dockerfile` (dockerfile)
 * `src/api/posts/Dockerfile` (dockerfile)
 * `src/api/search/Dockerfile` (dockerfile)
 * `src/api/status/Dockerfile` (dockerfile)
 * `src/api/users/Dockerfile` (dockerfile)
 * `src/web/Dockerfile` (dockerfile)
 * `tools/logrotate/Dockerfile` (dockerfile)
 * `.github/workflows/e2e-tests-ci.yml` (github-actions)
 * `.github/workflows/eslint-ci.yml` (github-actions)
 * `.github/workflows/node-js-ci.yml` (github-actions)
 * `.github/workflows/prettier-ci.yml` (github-actions)
 * `.github/workflows/release.yml` (github-actions)
 * `.github/workflows/unit-tests-ci.yml` (github-actions)
 * `package.json` (npm)
 * `src/api/auth/package.json` (npm)
 * `src/api/feed-discovery/package.json` (npm)
 * `src/api/image/package.json` (npm)
 * `src/api/parser/package.json` (npm)
 * `src/api/planet/package.json` (npm)
 * `src/api/posts/package.json` (npm)
 * `src/api/search/package.json` (npm)
 * `src/api/status/package.json` (npm)
 * `src/api/users/package.json` (npm)
 * `src/web/package.json` (npm)
 * `tools/autodeployment/package.json` (npm)
 * `tools/migrate/package.json` (npm)

### Configuration Summary

Based on the default config's presets, Renovate will:

  - Start dependency updates only once this onboarding PR is merged
  - Enable Renovate Dependency Dashboard creation
  - If semantic commits detected, use semantic commit type <code>fix</code> for dependencies and <code>chore</code> for all others
  - Ignore `node_modules`, `bower_components`, `vendor` and various test/tests directories
  - Autodetect whether to pin dependencies or maintain ranges
  - Rate limit PR creation to a maximum of two per hour
  - Weekly schedule on early monday mornings
  - Limit to maximum 1 open PR at any time
  - Group known monorepo packages together
  - Use curated list of recommended non-monorepo package groupings
  - Fix some problems with very old Maven commons versions
  - Ignore spring cloud 1.x releases
  - Ignore http4s digest-based 1.x milestones
  - Use node versioning for @types/node
  - Limit concurrent requests to reduce load on Repology servers until we can fix this properly, see issue 10133

🔡 Would you like to change the way Renovate is upgrading your dependencies? Simply edit the `renovate.json` in this branch with your custom config and the list of Pull Requests in the "What to Expect" section below will be updated the next time Renovate runs.

---

### What to Expect

With your current configuration, Renovate will create 20 Pull Requests:

<details>
<summary>chore(deps): pin dependencies</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/pin-dependencies`
  - Merge into: `master`
  - Pin [@babel/core](https://togithub.com/babel/babel) to `7.16.5`
  - Pin [@babel/plugin-transform-runtime](https://togithub.com/babel/babel) to `7.16.5`
  - Pin [@babel/preset-env](https://togithub.com/babel/babel) to `7.16.5`
  - Pin [@babel/preset-react](https://togithub.com/babel/babel) to `7.16.5`
  - Pin [@babel/preset-typescript](https://togithub.com/babel/babel) to `7.16.5`
  - Pin [@bull-board/api](https://togithub.com/felixmosh/bull-board) to `3.8.1`
  - Pin [@bull-board/express](https://togithub.com/felixmosh/bull-board) to `3.8.1`
  - Pin [@elastic/elasticsearch](https://togithub.com/elastic/elasticsearch-js) to `7.16.0`
  - Pin [@elastic/elasticsearch-mock](https://togithub.com/elastic/elasticsearch-js-mock) to `0.3.1`
  - Pin [@firebase/rules-unit-testing](https://togithub.com/firebase/firebase-js-sdk) to `2.0.1`
  - Pin [@fontsource/pt-serif](https://togithub.com/fontsource/fontsource) to `4.5.0`
  - Pin [@fontsource/spartan](https://togithub.com/fontsource/fontsource) to `4.5.1`
  - Pin [@material-ui/core](https://togithub.com/mui-org/material-ui) to `4.12.3`
  - Pin [@material-ui/icons](https://togithub.com/mui-org/material-ui) to `4.11.2`
  - Pin [@mdx-js/loader](https://togithub.com/mdx-js/mdx) to `1.6.22`
  - Pin [@mdx-js/mdx](https://togithub.com/mdx-js/mdx) to `1.6.22`
  - Pin [@next/mdx](https://togithub.com/vercel/next.js) to `12.0.7`
  - Pin [@senecacdot/satellite](https://togithub.com/Seneca-CDOT/satellite) to `1.17.0`
  - Pin [@testing-library/react](https://togithub.com/testing-library/react-testing-library) to `12.1.2`
  - Pin [@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped) to `16.11.17`
  - Pin [@types/react](https://togithub.com/DefinitelyTyped/DefinitelyTyped) to `17.0.38`
  - Pin [@types/smoothscroll-polyfill](https://togithub.com/DefinitelyTyped/DefinitelyTyped) to `0.3.1`
  - Pin [@types/yup](https://togithub.com/DefinitelyTyped/DefinitelyTyped) to `0.29.13`
  - Pin [@typescript-eslint/eslint-plugin](https://togithub.com/typescript-eslint/typescript-eslint) to `4.33.0`
  - Pin [@typescript-eslint/parser](https://togithub.com/typescript-eslint/typescript-eslint) to `4.33.0`
  - Pin [@vercel/node](https://togithub.com/vercel/vercel) to `1.12.1`
  - Pin [@wordpress/wordcount](https://togithub.com/WordPress/gutenberg) to `2.15.2`
  - Pin [babel-jest](https://togithub.com/facebook/jest) to `27.4.5`
  - Pin [babel-loader](https://togithub.com/babel/babel-loader) to `8.2.3`
  - Pin [babel-preset-next](https://togithub.com/cuining/babel-preset-next) to `1.4.0`
  - Pin [bull](https://togithub.com/OptimalBits/bull) to `3.29.3`
  - Pin [bull-board](https://togithub.com/felixmosh/bull-board) to `2.1.3`
  - Pin [celebrate](https://togithub.com/arb/celebrate) to `15.0.0`
  - Pin [cheerio](https://togithub.com/cheeriojs/cheerio) to `1.0.0-rc.10`
  - Pin clean-whitespace to `0.1.2`
  - Pin [clsx](https://togithub.com/lukeed/clsx) to `1.1.1`
  - Pin [connect-redis](https://togithub.com/visionmedia/connect-redis) to `6.0.0`
  - Pin [cors](https://togithub.com/expressjs/cors) to `2.8.5`
  - Pin [cross-env](https://togithub.com/kentcdodds/cross-env) to `7.0.3`
  - Pin [date-fns](https://togithub.com/date-fns/date-fns) to `2.27.0`
  - Pin [del-cli](https://togithub.com/sindresorhus/del-cli) to `4.0.1`
  - Pin [docker-compose](https://togithub.com/PDMLab/docker-compose) to `0.23.14`
  - Pin [dotenv](https://togithub.com/motdotla/dotenv) to `10.0.0`
  - Pin [entities](https://togithub.com/fb55/entities) to `3.0.1`
  - Pin [env-cmd](https://togithub.com/toddbluhm/env-cmd) to `10.1.0`
  - Pin [eslint](https://togithub.com/eslint/eslint) to `7.32.0`
  - Pin [eslint-config-airbnb](https://togithub.com/airbnb/javascript) to `18.2.1`
  - Pin [eslint-config-prettier](https://togithub.com/prettier/eslint-config-prettier) to `8.3.0`
  - Pin [eslint-plugin-anti-trojan-source](https://togithub.com/lirantal/eslint-plugin-anti-trojan-source) to `1.0.6`
  - Pin [eslint-plugin-import](https://togithub.com/import-js/eslint-plugin-import) to `2.25.3`
  - Pin [eslint-plugin-jest](https://togithub.com/jest-community/eslint-plugin-jest) to `25.3.0`
  - Pin [eslint-plugin-jest-playwright](https://togithub.com/mxschmitt/eslint-plugin-playwright) to `0.2.1`
  - Pin [eslint-plugin-jsx-a11y](https://togithub.com/jsx-eslint/eslint-plugin-jsx-a11y) to `6.5.1`
  - Pin [eslint-plugin-prettier](https://togithub.com/prettier/eslint-plugin-prettier) to `3.4.1`
  - Pin [eslint-plugin-promise](https://togithub.com/xjamundx/eslint-plugin-promise) to `5.2.0`
  - Pin [eslint-plugin-react](https://togithub.com/yannickcr/eslint-plugin-react) to `7.28.0`
  - Pin [eslint-plugin-react-hooks](https://togithub.com/facebook/react) to `4.3.0`
  - Pin [express](https://togithub.com/expressjs/express) to `4.17.2`
  - Pin [express-handlebars](https://togithub.com/express-handlebars/express-handlebars) to `6.0.2`
  - Pin [express-handlebars](https://togithub.com/express-handlebars/express-handlebars) to `5.3.5`
  - Pin [express-healthcheck](https://togithub.com/lennym/express-healthcheck) to `0.1.0`
  - Pin [express-pino-logger](https://togithub.com/pinojs/express-pino-logger) to `6.0.0`
  - Pin [express-session](https://togithub.com/expressjs/session) to `1.17.2`
  - Pin [express-validator](https://togithub.com/express-validator/express-validator) to `6.14.0`
  - Pin [fast-xml-parser](https://togithub.com/NaturalIntelligence/fast-xml-parser) to `3.21.1`
  - Pin [feed](https://togithub.com/jpmonette/feed) to `4.2.2`
  - Pin [firebase-admin](https://togithub.com/firebase/firebase-admin-node) to `10.0.1`
  - Pin [firebase-tools](https://togithub.com/firebase/firebase-tools) to `9.23.3`
  - Pin [formik](https://togithub.com/formium/formik) to `2.2.9`
  - Pin [got](https://togithub.com/sindresorhus/got) to `11.8.3`
  - Pin [helmet](https://togithub.com/helmetjs/helmet) to `4.6.0`
  - Pin [highlight.js](https://togithub.com/highlightjs/highlight.js) to `11.3.1`
  - Pin [http-link-header](https://togithub.com/jhermsmeier/node-http-link-header) to `1.0.3`
  - Pin [http-proxy-middleware](https://togithub.com/chimurai/http-proxy-middleware) to `2.0.1`
  - Pin [husky](https://togithub.com/typicode/husky) to `7.0.4`
  - Pin [ioredis](https://togithub.com/luin/ioredis) to `4.28.2`
  - Pin [ioredis-mock](https://togithub.com/stipsan/ioredis-mock) to `5.8.1`
  - Pin [jest](https://togithub.com/facebook/jest) to `27.4.5`
  - Pin [jest-fetch-mock](https://togithub.com/jefflau/jest-fetch-mock) to `3.0.3`
  - Pin [jest-playwright-preset](https://togithub.com/playwright-community/jest-playwright) to `1.7.0`
  - Pin [jsdom](https://togithub.com/jsdom/jsdom) to `18.1.1`
  - Pin [jsonwebtoken](https://togithub.com/auth0/node-jsonwebtoken) to `8.5.1`
  - Pin [jwt-decode](https://togithub.com/auth0/jwt-decode) to `3.1.2`
  - Pin [minimatch](https://togithub.com/isaacs/minimatch) to `3.0.4`
  - Pin [nanoid](https://togithub.com/ai/nanoid) to `3.1.30`
  - Pin [next](https://togithub.com/vercel/next.js) to `12.0.7`
  - Pin [next-compose-plugins](https://togithub.com/cyrilwanner/next-compose-plugins) to `2.2.1`
  - Pin [next-pwa](https://togithub.com/shadowwalker/next-pwa) to `5.4.4`
  - Pin [nock](https://togithub.com/nock/nock) to `13.2.1`
  - Pin [node-fetch](https://togithub.com/node-fetch/node-fetch) to `2.6.6`
  - Pin [nodemon](https://togithub.com/remy/nodemon) to `2.0.15`
  - Pin [normalize-url](https://togithub.com/sindresorhus/normalize-url) to `6.1.0`
  - Pin [npm-run-all](https://togithub.com/mysticatea/npm-run-all) to `4.1.5`
  - Pin [opml-generator](https://togithub.com/azu/opml-generator) to `1.1.1`
  - Pin [passport](https://togithub.com/jaredhanson/passport) to `0.5.2`
  - Pin [passport-saml](https://togithub.com/node-saml/passport-saml) to `3.2.0`
  - Pin [pino](https://togithub.com/pinojs/pino) to `7.6.0`
  - Pin [pino-elasticsearch](https://togithub.com/pinojs/pino-elasticsearch) to `6.2.0`
  - Pin [pino-pretty](https://togithub.com/pinojs/pino-pretty) to `7.3.0`
  - Pin [playwright](https://togithub.com/Microsoft/playwright) to `1.17.1`
  - Pin [pretty-quick](https://togithub.com/azz/pretty-quick) to `3.1.3`
  - Pin [react](https://togithub.com/facebook/react) to `17.0.2`
  - Pin [react-dom](https://togithub.com/facebook/react) to `17.0.2`
  - Pin [react-icons](https://togithub.com/react-icons/react-icons) to `4.3.1`
  - Pin [react-transition-group](https://togithub.com/reactjs/react-transition-group) to `4.4.2`
  - Pin [react-use](https://togithub.com/streamich/react-use) to `17.3.1`
  - Pin [rss-parser](https://togithub.com/bobby-brennan/rss-parser) to `3.12.0`
  - Pin [run.env](https://togithub.com/palanik/run.env) to `1.1.0`
  - Pin [sanitize-html](https://togithub.com/apostrophecms/sanitize-html) to `2.6.1`
  - Pin [sass](https://togithub.com/sass/dart-sass) to `1.45.1`
  - Pin [set-interval-async](https://togithub.com/ealmansi/set-interval-async) to `2.0.3`
  - Pin [sharp](https://togithub.com/lovell/sharp) to `0.29.3`
  - Pin [smoothscroll-polyfill](https://togithub.com/iamdustan/smoothscroll) to `0.4.4`
  - Pin [stoppable](https://togithub.com/hunterloftis/stoppable) to `1.1.0`
  - Pin [supertest](https://togithub.com/visionmedia/supertest) to `6.1.6`
  - Pin [swr](https://togithub.com/vercel/swr) to `1.1.1`
  - Pin [terser-webpack-plugin](https://togithub.com/webpack-contrib/terser-webpack-plugin) to `5.3.0`
  - Pin [ts-jest](https://togithub.com/kulshekhar/ts-jest) to `27.1.2`
  - Pin [typescript](https://togithub.com/Microsoft/TypeScript) to `4.5.4`
  - Pin [yup](https://togithub.com/jquense/yup) to `0.32.11`

</details>

<details>
<summary>chore(deps): pin dependency @&#8203;types/jest to 27.0.3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/jest-monorepo`
  - Merge into: `master`
  - Pin [@types/jest](https://togithub.com/DefinitelyTyped/DefinitelyTyped) to `27.0.3`

</details>

<details>
<summary>chore(deps): update docker.elastic.co/elasticsearch/elasticsearch docker tag to v7.16.2</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/docker.elastic.co-elasticsearch-elasticsearch-7.x`
  - Merge into: `master`
  - Upgrade [docker.elastic.co/elasticsearch/elasticsearch](https://togithub.com/elastic/elasticsearch) to `7.16.2`

</details>

<details>
<summary>chore(deps): update traefik docker tag to v2.5.6</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/traefik-2.x`
  - Merge into: `master`
  - Upgrade [traefik](https://togithub.com/containous/traefik) to `v2.5.6`

</details>

<details>
<summary>chore(deps): update dependency eslint-plugin-jest-playwright to v0.7.1</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/eslint-plugin-jest-playwright-0.x`
  - Merge into: `master`
  - Upgrade [eslint-plugin-jest-playwright](https://togithub.com/mxschmitt/eslint-plugin-playwright) to `0.7.1`

</details>

<details>
<summary>chore(deps): update dependency prettier to v2.5.1</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/prettier-2.x`
  - Merge into: `master`
  - Upgrade [prettier](https://togithub.com/prettier/prettier) to `2.5.1`

</details>

<details>
<summary>chore(deps): update dependency eslint to v8</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/eslint-8.x`
  - Merge into: `master`
  - Upgrade [eslint](https://togithub.com/eslint/eslint) to `8.5.0`

</details>

<details>
<summary>chore(deps): update dependency eslint-config-airbnb to v19</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/eslint-config-airbnb-19.x`
  - Merge into: `master`
  - Upgrade [eslint-config-airbnb](https://togithub.com/airbnb/javascript) to `19.0.2`

</details>

<details>
<summary>chore(deps): update dependency eslint-plugin-prettier to v4</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/eslint-plugin-prettier-4.x`
  - Merge into: `master`
  - Upgrade [eslint-plugin-prettier](https://togithub.com/prettier/eslint-plugin-prettier) to `4.0.0`

</details>

<details>
<summary>chore(deps): update dependency eslint-plugin-promise to v6</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/eslint-plugin-promise-6.x`
  - Merge into: `master`
  - Upgrade [eslint-plugin-promise](https://togithub.com/xjamundx/eslint-plugin-promise) to `6.0.0`

</details>

<details>
<summary>chore(deps): update dependency firebase-tools to v10</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/firebase-tools-10.x`
  - Merge into: `master`
  - Upgrade [firebase-tools](https://togithub.com/firebase/firebase-tools) to `10.0.1`

</details>

<details>
<summary>chore(deps): update typescript-eslint monorepo to v5 (major)</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/major-typescript-eslint-monorepo`
  - Merge into: `master`
  - Upgrade [@typescript-eslint/eslint-plugin](https://togithub.com/typescript-eslint/typescript-eslint) to `5.8.0`
  - Upgrade [@typescript-eslint/parser](https://togithub.com/typescript-eslint/typescript-eslint) to `5.8.0`

</details>

<details>
<summary>fix(deps): update dependency @&#8203;wordpress/wordcount to v3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/major-wordpress-monorepo`
  - Merge into: `master`
  - Upgrade [@wordpress/wordcount](https://togithub.com/WordPress/gutenberg) to `3.2.3`

</details>

<details>
<summary>fix(deps): update dependency bull to v4</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/bull-4.x`
  - Merge into: `master`
  - Upgrade [bull](https://togithub.com/OptimalBits/bull) to `4.2.0`

</details>

<details>
<summary>fix(deps): update dependency express-handlebars to v6</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/express-handlebars-6.x`
  - Merge into: `master`
  - Upgrade [express-handlebars](https://togithub.com/express-handlebars/express-handlebars) to `6.0.2`

</details>

<details>
<summary>fix(deps): update dependency express-pino-logger to v7</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/express-pino-logger-7.x`
  - Merge into: `master`
  - Upgrade [express-pino-logger](https://togithub.com/pinojs/express-pino-logger) to `7.0.0`

</details>

<details>
<summary>fix(deps): update dependency got to v12</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/got-12.x`
  - Merge into: `master`
  - Upgrade [got](https://togithub.com/sindresorhus/got) to `12.0.0`

</details>

<details>
<summary>fix(deps): update dependency jsdom to v19</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/jsdom-19.x`
  - Merge into: `master`
  - Upgrade [jsdom](https://togithub.com/jsdom/jsdom) to `^19.0.0`
  - Upgrade [jsdom](https://togithub.com/jsdom/jsdom) to `19.0.0`

</details>

<details>
<summary>fix(deps): update dependency node-fetch to v3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/node-fetch-3.x`
  - Merge into: `master`
  - Upgrade [node-fetch](https://togithub.com/node-fetch/node-fetch) to `^3.0.0`
  - Upgrade [node-fetch](https://togithub.com/node-fetch/node-fetch) to `3.1.0`

</details>

<details>
<summary>fix(deps): update dependency normalize-url to v7</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/normalize-url-7.x`
  - Merge into: `master`
  - Upgrade [normalize-url](https://togithub.com/sindresorhus/normalize-url) to `7.0.2`

</details>

<br />

🚸 Branch creation will be limited to maximum 2 per hour, so it doesn't swamp any CI resources or spam the project. See docs for `prhourlylimit` for details.

---

❓ Got questions? Check out Renovate's [Docs](https://docs.renovatebot.com/), particularly the Getting Started section.
If you need any further assistance then you can also [request help here](https://togithub.com/renovatebot/renovate/discussions).

---

This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#{{platform}}/{{repository}}).

### CODE REVIEW

**Comment by humphd** [comment]
> - Rate limit PR creation to a maximum of two per hour
> - Limit to maximum 10 open PRs at any time

Can we further reduce these?  We've had issues in the past with Dependabot overloading our build minutes on CI with tons of PRs.  We don't need to live on the cutting edge with updates, they can trickle in.

**Comment by DukeManh** [comment]
I forgot to update the description, I've re-configured it to 1 open PR at a Time.

> Rate limit PR creation to a maximum of two per hour

This limits 2 PRs an hour. Should we limit more?

**Comment by humphd** [comment]
(2 per hour) x (24 hours) x (~13 mins) = 624 build minutes.  Next, you factor in rebases, which is what killed us with Dependabot, where one PR gets merged, triggering a cascade of rebasing on other PRs, and you run out of build minutes in no time.

In theory it sounds great to update your deps all the time, in real-time, but in practice it's not realistic.  I'd start with a 2 per day or week, and we turn up the volume from there, once we understand what the bot will actually do.

**Comment by DukeManh** [comment]
That's a good analysis, thanks for that. So no`auto-rebase` as well?

**Comment by humphd** [comment]
100% no to `auto-rebase`, it's the killer.

**Comment by DukeManh** [comment]
With this, Renovate is allowed to work every Monday morning, limited to 1 open PR at a time and 1 PR created per hour.

**Review by humphd — APPROVED** [review]
This seems reasonable to me.  I'd prefer to not land this while everyone is on holidays, though, since I know I won't be monitoring things for a while.

Thanks for making this happen.  It's great to have updates being managed again.

**Comment by humphd** [comment]
@DukeManh should we try this now?  I'm happy for you to merge this whenever is good for you, as long as you're around to help me with any fallout we experience.

**Comment by DukeManh** [comment]
Yes, I'll be around, let's get this in and see what happens.

**Comment by humphd** [comment]
OK, here we go

**Comment by DukeManh** [comment]
@humphd After installing Renovate, it should trigger some actions. Could you confirm it in the [dashboard](https://app.renovatebot.com/dashboard)?

**Comment by humphd** [comment]
Two things:

- it looks like this has to be installed, but it wants me to install it at the org vs. repo level.  Can you guide me on how I get this installed just for Telescope?
- we're failing unit tests for some reason, possibly snapshots just need to get updated based on version changes? https://github.com/Seneca-CDOT/telescope/runs/4693402584?check_suite_focus=true

**Comment by DukeManh** [comment]
I'm not familiar with org account, for my own project, I installed it to my account and then configure access to the repo I want.

> we're failing unit tests for some reason, possibly snapshots just need to get updated based on version changes? 

oh no the snapshot is failing because we hardcode the year 2021 in the snapshot.

**Comment by humphd** [comment]
@DukeManh can you see https://app.renovatebot.com/dashboard#github/Seneca-CDOT/telescope ?

Also, lol at 2021 hard-coded into it.  Our very own year-2022 bug!

**Comment by DukeManh** [comment]
Looks like it's working well. We should get the Dependency Pinning PR in first. #2638

**Pull request merged**
