### PR TITLE
Issue 1224 Reposition search button for search UI

### LINKED ISSUE #1224: Show all posts for an author sorted by date when searching by Author
When I search "by Author" I really want to see all the posts we have for this user.  It would be great to either replace what we have now with a timeline of their posts, sorted by date (newest to oldest), or add that to what we have now.

### PR DESCRIPTION
**Pull request by strawberries73**
## Issue This PR Addresses
Fixes  #1224

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Moved the Icon search button (magnifying glass) down into the right of the input text box.  Works for all devices.

image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by agarcia-caicedo** [comment]
This is a small nit, but can you center it more between the end of the text box and the edge of the container?

**Comment by strawberries73** [comment]
@agarcia-caicedo I will work on that.

**Comment by c3ho** [comment]
Can we edit the title of this PR?

**Review by agarcia-caicedo — DISMISSED** [review]

**Comment by strawberries73** [comment]
@agarcia-caicedo I centered the icon button.

**Review by humphd — CHANGES_REQUESTED** [review]
This is working well at large widths, but fails at narrower widths and on mobile.

search-button-overlap

**Comment by strawberries73** [comment]
@humphd  I am trying to figure this one out.

**Comment by strawberries73** [comment]
@humphd  fulfilled request, it now works on small windows.

**Review by humphd — CHANGES_REQUESTED** [review]
This is a lot better.  There's still an issue on mobile, though:

Screen Shot 2020-11-18 at 9 33 06 AM

**Comment by strawberries73** [comment]
I notice this too.  
image
The problem is that I do not know how to do this part.  
image

**Review by humphd — CHANGES_REQUESTED** [review]
It's getting cropped on mobile, you need to allow a more flexible size on the input so it makes room vs. pushing it off the screen.

Screen Shot 2020-11-18 at 2 33 07 PM

**Comment by agarcia-caicedo** [comment]
A suggestion, but in mobile screens, rather than have the filter and the search input take up two lines, like it currently does, we can shrink the filter so it takes up less space and have both the filter and search in one line.

That way there could be space for the search button

**Comment by VietnameZe** [comment]
@agarcia-caicedo  @humphd @strawberries73 I tried to use [Input Adornments](https://material-ui.com/components/text-fields/#input-adornments) for the Textfield and It works pretty nice

**Comment by strawberries73** [comment]
@VietnameZe I like it personally.  How does it look on mobile?

**Comment by VietnameZe** [comment]
> @VietnameZe I like it personally. How does it look on mobile?

Same as the gif above

**Comment by agarcia-caicedo** [comment]
@VietnameZe I think that's a viable solution. I'm not a fan of how the button looks with the fix, but that could be a follow up issue, since it's more of a purely aesthetic nit

**Comment by VietnameZe** [comment]
> @VietnameZe I think that's a viable solution. I'm not a fan of how the button looks with the fix, but that could be a follow up issue, since it's more of a purely aesthetic nit

@agarcia-caicedo That's why I prefered the search icon to be in grey color, the blue doesn't look nice.

**Comment by agarcia-caicedo** [comment]
> > @VietnameZe I think that's a viable solution. I'm not a fan of how the button looks with the fix, but that could be a follow up issue, since it's more of a purely aesthetic nit
> 
> @agarcia-caicedo That's why I prefered the search icon to be in grey color, the blue doesn't look nice. it doesn't need to be stand out too much since people more likely to hit 'enter' than press the button
> 
> 

I do remember @humphd wanting a button that looks like a button, so that's why I'm not ready to make it less noticeable and more like decoration

**Comment by strawberries73** [comment]
@agarcia-caicedo I was able to put the changes in that @VietnameZe suggested.  Personally I like the blue search button.  :)

**Review by humphd — CHANGES_REQUESTED** [review]
OK, I think this direction will work.  In a follow-up we can revisit the actual look and feel, I'm not sure the blue is ideal here, but it doesn't need to block things.

However, your branch management has undone a number of things on `master` when you did `Merge branch 'master' into Issue-1224` with commit `f291f8d`.  For example, clicking the adornment no longer does a search, and we get errors in the console.  Please make sure you re-read the git workflow document I linked on Blackboard: https://github.com/Seneca-CDOT/telescope/blob/master/docs/git-workflow.md.

If you're able to rebase and correct these merge conflicts, that would be good.  If not, please close this and open a new PR that only changes the code related to the new `<InputAdornment>`.

**Pull request closed without merging**
