### PR TITLE
Add RLS for new Supabase tables (Github, Quotes)

### LINKED ISSUE #3408: Add RLS for existing Postgres tables
We currently have [6 SQL tables](https://dev.supabase.telescope.cdot.systems/project/default/editor) and 4 don't have RLS enabled. To protect our data, we should add RLS to all of them.

For `quotes` table, we should allow read access to everyone and disable update/delete access. 

For how to write RLS, see https://github.com/Seneca-CDOT/telescope/blob/ec33441c3b34a28e5e816ba57103465b546ac4be/docker/supabase/volumes/db/init/04-telescope-schema.sql#L53

### PR DESCRIPTION
**Pull request by joelazwar**
## Issue This PR Addresses
fix #3408 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Adds read level functionality, and restricts altering and updating for all users (github-* tables, and quotes table)

## Steps to test the PR

- `pnpm services:start`
- navigate to http://localhost:8910
- check tables for new RLS policies

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by joelazwar** [comment]
@JerryHue @DukeManh could you guys help me test this? I can't get the init scripts to work. (the github tables arent showing up either in my local supabase)

**Comment by JerryHue** [comment]
> @JerryHue @DukeManh could you guys help me test this? I can't get the init scripts to work. (even the github tables arent showing up in my local supabase)

You need to delete the whole volume for the `init` scripts to actually execute. That means that you need to delete the folder `docker/supabase/volumes/db/data`. You might need to use admin privileges in your computer because `docker` created the volume itself.

It is kind of cumbersome, but hey, it is what it is 😅

If you want, you can open an issue that could address this situation. We would need to discuss on how to actually approach this.

**Comment by DukeManh** [comment]
@joelazwar, we have a meeting at 1 on Teams about migrations with Prisma to talk about how to edit the existing schema. To add RLS with it, you would make a migration file and put your RLS into it and apply the migration. 

The init scripts won't be run again because the DB has already been initialized. I doubt that the volumes data can be deleted.

**Comment by joelazwar** [comment]
Sorry, I missed the meeting, I was afk. So should we just add the RLS policies manually in the our dev Supabase environments?

**Comment by joelazwar** [comment]
Going to close this in favor of #3418

**Comment by humphd** [comment]
Why did we close this?  We still need to run this migration I think, right?

**Comment by joelazwar** [comment]
Reopened with migration script for Prisma

**Review by DukeManh — COMMENTED** [review]
We introduce `_prisma_migrations` table used by Prisma in #3418, I think you can enable RLS on that too with no select and update for all because only Prisma uses it and it has a password to access the DB.

**Review by DukeManh — DISMISSED** [review]
@joelazwar, I see, there is no underlying `_migrations` table to enable RLS on. We can enable RLS manually using the studio on staging/production if we need to.

**Review by DukeManh — APPROVED** [review]

**Review by JerryHue — APPROVED** [review]

**Review by humphd — APPROVED** [review]

**Review by DukeManh — APPROVED** [review]

**Pull request merged**
