### PR TITLE
[Can be shipped] Docusaurus home page

### LINKED ISSUE #2987: Home Page for Docusaurus needs to be updated
Our current Docusuarus home page looks like this:

Screenshot 2022-02-18 at 14-34-55 Hello from Telescope Telescope

Could probably use fewer dinosaurs and more telescopes? Suggestions are open.

cc @sirinoks because she has mentioned interest in this on Slack and https://github.com/Seneca-CDOT/telescope/issues/2924#issuecomment-1039885003

### PR DESCRIPTION
**Pull request by sirinoks**
## Issue This PR Addresses
Fixes #2987 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Adding an SVG layered image for the home page. Later to be converted to have a parallax effect

## Steps to test the PR

- `cd src/web/docusaurus`
- `pnpm start`
- localhost:4631

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — APPROVED** [review]

**Comment by TueeNguyen** [comment]
Are you gonna add it the home page? Right now it's only svgs

**Comment by JerryHue** [comment]
> Are you gonna add it the home page? Right now it's only svgs

I think this is in progress. Remember that this marked as a draft PR.

**Comment by sirinoks** [comment]
Base stage is complete. The image shows up and works. Next step would be to reproduce the parallax effect, might or might not have time for that. 

Not sure what's up with that failed jest test, if anyone knows - let me know.

**Comment by sirinoks** [comment]
Nvm it failed for no reason

**Review by humphd — DISMISSED** [review]
Let's not show all the edges of these different SVGs, and fill the available space vs. having whitespace around the background.

I think this should fill the entire middle section of the page, tight to the edges.

Screen Shot 2022-04-19 at 8 56 59 AM

Also, you talked about doing parallax, but I don't see it here.  Is that coming in a follow-up?

**Comment by sirinoks** [comment]
> Also, you talked about doing parallax, but I don't see it here. Is that coming in a follow-up?

Yes. I am putting this up here just so we have this stage ready, so it's at least something.

**Comment by sirinoks** [comment]
This was decided to be shipped in its current state, since we have more important issues to prioritise. 

I suggest having to remove the large button of "5 min tutorial" be made into a separate issue for hacktoberfest, as it is a "good first issue". Or having it move below the image. Unless it's fine where it is.

**Review by TueeNguyen — APPROVED** [review]

**Review by JiaHua-Zou — APPROVED** [review]

**Pull request merged**
