### PR TITLE
Fixes: 1672 - [next] Investigate bugs related to Fonts.

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
Fixes: #1672

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
The font on the PR #1667 before and after the fix:
BEFORE:
Screen Shot 2021-02-08 at 6 06 17 AM

AFTER:
Screen Shot 2021-02-08 at 6 02 48 AM

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — APPROVED** [review]
Nice catch.

**Review by birtony — CHANGES_REQUESTED** [review]
I have looked up the `typeface-roboto` package and it looks like `typeface` has been deprecated: https://github.com/KyleAMathews/typefaces/blob/master/packages/roboto/README.md. Could we use `fontsource-roboto` instead? @PedroFonsecaDEV

**Comment by humphd** [comment]
> The Typefaces project is now deprecated.

NO!!!!!!!  I loved this project.  Thanks for spotting this, @birtony.

**Comment by PedroFonsecaDEV** [comment]
Screen Shot 2021-02-09 at 1 15 20 AM

The new font has a different weight. 
I think we can land this to have the same font as gatsby, then we move to a non-deprecated font on the new UI.

**Comment by birtony** [comment]
@PedroFonsecaDEV do you think we could set the default font-weight in our global CSS styles and stick to `fontsource-roboto`?

**Comment by PedroFonsecaDEV** [comment]
Hey @birtony,
Since all our styles (including the font) are about to change, my advice will be to keep the old font until there. Because if we change it, it will change globally. Some texts will be impacted, like our header fonts.

**Comment by birtony** [comment]
> 
> 
> Hey @birtony,
> Since all our styles (including the font) are about to change, my advice will be to keep the old font until there. Because if we change it, it will change globally. Some texts will be impacted, like our header fonts.

Okay, that makes sense. In this case, could you, please, file an issue regarding the deprecated dependency before we merge this PR @PedroFonsecaDEV?

**Comment by PedroFonsecaDEV** [comment]
> > Hey @birtony,
> > Since all our styles (including the font) are about to change, my advice will be to keep the old font until there. Because if we change it, it will change globally. Some texts will be impacted, like our header fonts.
> 
> Okay, that makes sense. In this case, could you, please, file an issue regarding the deprecated dependency before we merge this PR @PedroFonsecaDEV?

Sure. 
Follow the issue: https://github.com/Seneca-CDOT/telescope/issues/1686

**Review by birtony — APPROVED** [review]

**Pull request merged**
