### PR TITLE
Fix: 2224 Removed add-feed link from docs & package.json 

### LINKED ISSUE #2224: add-feed link in tools README points to nothing
**What happened**:
We must have removed this file from the tools directory at some point, because the link here still points to the file, which doesn't exist in the repo anymore

url-in-question

[This is the link that developers will see](https://github.com/Seneca-CDOT/telescope/blob/master/tools/add-feed.js). This should be removed from the README for the tools directory if it's not being used anymore

### PR DESCRIPTION
**Pull request by shubhammehra4**
## Issue This PR Addresses
Fix #2224 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Removed links to add-feed link from tools/README.md , docs/git-workflow.md & package.json

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by PedroFonsecaDEV** [comment]
Failing on `Prettier`: 
```
> @senecacdot/telescope@2.0.0 prettier-check /home/runner/work/telescope/telescope
> prettier --check "./**/*.{md,jsx,json,html,css,js,yml}"

Checking formatting...
[warn] tools/README.md
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
cc @HyperTHD

**Comment by shubhammehra4** [comment]
@PedroFonsecaDEV I can't seem to understand why that unit test is failing 😅

**Comment by PedroFonsecaDEV** [comment]
> @PedroFonsecaDEV I can't seem to understand why that unit test is failing 😅

@shubhammehra4, Prettier is a tool that formats our code according to rules that we set, so even the code being written by more than one person we can have more consistency in our code style, you can check an example [here](https://prettier.io/playground/).
I suggested you set up a local Telescope and install all of our extensions; if you are using Vscode, you will receive some messages when opening the project for the first time to allow Prettier to format the code every time you save a file.

Another option is to run our Prettier script manually: 
Try this one first to check which file is failing on the test:
`npm run prettier-check`
Then you can run the following command to format the files 
`npm run prettier`

Let me know if it works.
Thanks.

**Comment by shubhammehra4** [comment]
Thanks for your reply,
But I already pushed a commit that resolved the prettier test, I was referencing the failed unit test on macOS14.x the only files I edited were the markdown files and package.json(only the "bin" object didn't touch any deps), I think they are not related to the unit tests so I'm a little confused

**Review by PedroFonsecaDEV — APPROVED** [review]
LGTM

**Review by manekenpix — APPROVED** [review]

**Pull request merged**
