### PR TITLE
Issue #1225 Repositioned the search button

### LINKED ISSUE #1225: Reposition search button for search UI
Our frontend kicks off searches every time you start typing.  I'd love to see us:

- add a button so it doesn't happen until I click or press 'enter'
- and/or debounce this keyboard event so it doesn't start happening until I finish typing

If you type something like, it will fire and re-fire the query on every letter.  That's bad UI, and it overloads the network and React.

### PR DESCRIPTION
**Pull request by strawberries73**
## Issue This PR Addresses
Fixes #1225 

## Type of Change
Repositioned the search button down to the right side of the text box

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Search button stays in the search box for full screen, mobile and inspect screen.

image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
This is undoing the work that @MSTEWARDSON did to separate the input field using the `<SearchInput>` component.  You'll have to put this adornment in the new `<AuthorSearchInput>` and `<PostSearchInput>` components vs. doing it in the old `<TextField>`, which doesn't exist in `master` now.

**Comment by strawberries73** [comment]
I don't know what happed.  This is weird, I didn't even click on the PR.  I was trying to do a draft.

**Comment by MLJBrackett** [comment]
Seems the latest deployment is broken on my end (Maybe its just me?) 



~~Also clicking on the button doesn't actually search anymore... This is probably caused by the overlapping of the two elements.~~

Actually it does search but once you click on the text box it changes the url. Once you put in a entry into the text box then click on search, it doesn't actually change the url again. Weirdly enough this issue only occurs when I am using 'Post' as the filter, otherwise the functionality of the search bar still works, but the css is still overlapping.

**Comment by strawberries73** [comment]
@MLJBrackett  I am actually almost done fixing this. I should be done before the end of the week.

**Pull request closed without merging**
