### PR TITLE
[Docs] Add template for an ongoing project

### LINKED ISSUE #2802: Template for an ongoing Project
Make a detailed template on what information has to be included in the main issue of a project. 

You might have noticed a new project template already exists. The difference will be that the active project should already have a bunch of information available, as opposed to a vague and limited new project. Eventually such an issue, once the project is completed will be put in the docs without many changes needed, since the issue will get updated as new information becomes available.

I have an idea what it should be like, adding this issue for the sake of keeping a trail.

### PR DESCRIPTION
**Pull request by sirinoks**
## Issue This PR Addresses

Fixes #2802 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Adds a new template that will help documenting projects.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by cindyledev** [comment]
@sirinoks you should tag people who would be interested in reviewing this

**Comment by humphd** [comment]
@joelazwar, @Kevan-Y this needs reviewers, can you two get this moving?

**Comment by Kevan-Y** [comment]
I'm not too sure of what kind of situation we need this.
Could you provide an example of it?

**Comment by sirinoks** [comment]
So for any current project we have, they will eventually get to that stage. I think React Native and Supabase are getting there.
 
Every project that has enough information needs a parent issue. The issue that will describe what the project is about, who to ask and other details. Once the project is complete, that issue information can easily be copied to docs, without much need to rewrite things, since the parent issue will be updated as the project develops. 

So imagine a new student interested in getting into react native. Where would they go? They could ask people on slack (but who to ask?), google things, read official documentation, ask how to run it, look for our own documentation.. Many steps. There isn't a single place with all the needed information - that is what parent issues are for. To have all the info in one place. 

Does that answer your question @Kevan-Y ?

**Comment by Kevan-Y** [comment]
> So for any current project we have, they will eventually get to that stage. I think React Native and Supabase are getting there.
> 
> Every project that has enough information needs a parent issue. The issue that will describe what the project is about, who to ask and other details. Once the project is complete, that issue information can easily be copied to docs, without much need to rewrite things, since the parent issue will be updated as the project develops.
> 
> So imagine a new student interested in getting into react native. Where would they go? They could ask people on slack (but who to ask?), google things, read official documentation, ask how to run it, look for our own documentation.. Many steps. There isn't a single place with all the needed information - that is what parent issues are for. To have all the info in one place.
> 
> Does that answer your question @Kevan-Y ?

Basically, use the issue as documentation, and also kind of refers to Epic where it has a bunch of subtasks to complete the project?

**Comment by sirinoks** [comment]
Yes. Documentation, referral, subtasks, discussion. @Kevan-Y

**Review by Kevan-Y — DISMISSED** [review]

**Review by cindyledev — DISMISSED** [review]

**Review by Kevan-Y — APPROVED** [review]

**Review by cindyledev — APPROVED** [review]

**Pull request merged**
