### PR TITLE
Use stale lock-file from release 2.8.3

### PR DESCRIPTION
**Pull request by JerryHue**
This PR is used to trigger the CI.

DO NOT MERGE!!! If you do, Dave will kill me. 😢

### CODE REVIEW

**Comment by humphd** [comment]
```
Lockfile is up-to-date, resolution step is skipped
 ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up-to-date with src/api/parser/package.json
```

It already does what you want.

**Comment by JerryHue** [comment]
@humphd, so if CI fails when the lock-file is stale, then what happened with Tue's PR? Why it did not fail?

**Comment by humphd** [comment]
Who knows?  GitHub Actions is having a bad week, maybe something failed on the infra?  The way we have things, it should work as expect (i.e., error when something isn't updated).

**Comment by JerryHue** [comment]
I think it may fail when the lock-file is broken, not when it is stale

**Comment by humphd** [comment]
```
 WARN  Ignoring broken lockfile at /home/runner/work/telescope/telescope: The lockfile at "/home/runner/work/telescope/telescope/pnpm-lock.yaml" is broken: duplicated mapping key (1041:3)
```

**Comment by JerryHue** [comment]
> I think it may fail when the lock-file is broken, not when it is stale

Sorry, I meant the opposite: I think CI may fail when the lock-file is stale, not when it is broken

> ```
>  WARN  Ignoring broken lockfile at /home/runner/work/telescope/telescope: The lockfile at "/home/runner/work/telescope/telescope/pnpm-lock.yaml" is broken: duplicated mapping key (1041:3)
> ```

Yeah, it only warns about this. `pnpm install` does not care that the lockfile is broken because it repairs it anyway. However, we want the CI to check for real, so I think we should add another job that checks this.

**Comment by JerryHue** [comment]
Very well, now that we know the actual reason, we can submit a PR that addresses this. If we want to discuss more, let's do it in #3311.

**Pull request closed without merging**
