### PR TITLE
Fixes #2461: Build Log dashboard should use same layout/CSS as rest of Dashboard

### LINKED ISSUE #2461: Build Log dashboard should use same layout/CSS as rest of Dashboard
The [new Dashboard build log](https://dev.api.telescope.cdot.systems/v1/status) doesn't look like the rest of the Dashboard:

Screen Shot 2021-11-11 at 9 55 06 PM

vs. 

Screen Shot 2021-11-11 at 9 55 46 PM

Let's use the same sidebar, header, footer, etc. and just fill the available space with the terminal.

### PR DESCRIPTION
**Pull request by mqnguyen5**
## Type of Change

- [x] **UI**: Change which improves UI

## Description

This issue updates the Build Log dashboard to have the same layout/CSS as the rest of the Telescope dashboard.

Changes:

- Added header and sidebar
- Replaced Material UI logo with Telescope's logo and changed sidebar title to "Telescope Dashboard"
- Updated the Telescope logo inside the sidebar to redirect to `./`

Results:

Screen Shot 2021-11-17 at 12 04 51 AM

Screen Shot 2021-11-17 at 12 05 17 AM

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2480"></a>

### CODE REVIEW

**Comment by mqnguyen5** [comment]
Currently, this PR is not fully completed, as I still have some stuff to discuss in #2472.

**Comment by humphd** [comment]
> Currently, this PR is not fully completed, as I still have some stuff to discuss in #2472.

What's the status of this?  Also, please post a screenshot of it running.

**Comment by mqnguyen5** [comment]
@humphd I'll push the rest of the changes up by today.

**Comment by humphd** [comment]
@mqnguyen5 can you do a single screenshot of the whole thing, which is really want we want to see here?

**Comment by mqnguyen5** [comment]
Here it is:

Screen Shot 2021-11-18 at 6 11 49 PM

**Comment by humphd** [comment]
Let's add a left margin to the terminal so it has some breathing room next to the sidebar.  Also, let's have it go higher in the page (don't waste so much space above it).  I think it can be aligned with the top of the sidebar.  Let's also have it fill the available space vertically.

**Comment by mqnguyen5** [comment]
If that's the case, should I remove the "Build Log" `<h1>` above the terminal?

**Comment by humphd** [comment]
I think so, since the sidebar acts as the anchoring navigational element (we don't need a title).

**Comment by mqnguyen5** [comment]
Currently, the page looks like this after remove the title and adjust the padding to make it closer to the top:

Screen Shot 2021-11-18 at 6 44 42 PM

I'm not sure how I can add a margin when opening the sidenav and remove it when closing the sidenav. Is there a way to do it with Material UI?

**Comment by mqnguyen5** [comment]
@Andrewnt219, @menghif you have any suggestions on this?

**Comment by Andrewnt219** [comment]
@mqnguyen5 one quick way is you copy everything in the `index.html`, paste it on the build.html. Open Devtools, start deleting all the unrelated stuffs, copy the elemtn from the Devtools and paste it back to your IDE. Finally, just add the tag `div.id="termminal"` to main content area.

**Comment by Andrewnt219** [comment]
> I'm not sure how I can add a margin when opening the sidenav and remove it when closing the sidenav. Is there a way to do it with Material UI?

That sounds like JS magic. But why do you want to do this?

This is just Bootstrap 5 with vanilla JS btw, not the same as Material UI on Telescope.

**Comment by mqnguyen5** [comment]
After looking around, I managed to find out what is wrong. I didn't not realized that I had been showing screenshots of the site when opening in small window instead of going full screen.

Screen Shot 2021-11-19 at 4 01 10 PM

I also adjusted the padding on the terminal per @humphd suggestion, so it should take less space from the top now.

**Review by drew5494 — APPROVED** [review]
Tested and looks good on my end.

**Review by humphd — APPROVED** [review]

**Pull request merged**
