### PR TITLE
set MAX_POSTS_PER_PAGE=5

### LINKED ISSUE #1351: Reduce number of posts per page we load
Now that we have infinite scrolling (#1332), we don't need to load as many posts for the timeline to be usable.  Let's go down from 10 to 5 and see how that feels.

The change needs to happen in all these:

https://github.com/Seneca-CDOT/telescope/search?q=MAX_POSTS_PER_PAGE

### PR DESCRIPTION
**Pull request by yzwdroid**
## Issue This PR Addresses
Fixes #1351 

## Type of Change
changed max posts per page to 5.

le name is shown
- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
I changed the variable MAX_POSTS_PER_PAGE=5, from three different env file.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — APPROVED** [review]

**Review by manekenpix — CHANGES_REQUESTED** [review]
Thanks for this. Just one things, can you explain in the description what you changed for this PR?

**Review by PedroFonsecaDEV — CHANGES_REQUESTED** [review]
Screen Shot 2020-11-15 at 12 42 55 AM

It seems to me that we are still requesting 10 posts.

**Comment by humphd** [comment]
@PedroFonsecaDEV did you modify your `.env` to take these new changes?  Also, we'll have to do this manually on staging when this merges I think (cc @manekenpix)

**Comment by PedroFonsecaDEV** [comment]
@humphd This screenshot is from Vercel build.
So this PR will only make an effect when merged?

**Comment by humphd** [comment]
Yeah, it's using the current backend on dev, which Vercel uses but doesn't get updated until we merge on `master`.

**Review by manekenpix — APPROVED** [review]

**Review by PedroFonsecaDEV — APPROVED** [review]

**Pull request merged**
