### PR TITLE
Bulgarian translation of overview page

### LINKED ISSUE #3697: Translate about page to Bulgarian
Related to: #2962 
If you would like to contribute to our translations, please visit the above issue and comment with the language you wish to translate in! (provided it isn't taken yet)

Translate About us page from English to Bulgarian

### PR DESCRIPTION
**Pull request by IvaniGabrovsky**
Fixes #3697

## Type of Change

- [x] **New Feature**: I have created an about page in Bulgarian language.

## Description
The about page is in Bulgarian language, for Bulgarian speakers to being able to get a brief understand of the Telescope project and how everything works. 

    Example:
    - Go to '/src/web/docusaurus'
    - `pnpm install`
    - `pnpm run start`
    - Open URL 'http://localhost:4631/docs/overview'
    - Click on English drop down menu
    - Click on Български

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by sirinoks** [comment]
@humphd I'm sorry I don't know Bulgarian :(

I can check if it at least displays and runs correctly

**Comment by humphd** [comment]
@sirinoks we're all in the same boat, I think.  Hopefully @IvaniGabrovsky can get a technically-aware Bulgarian reader to review the language itself.  We can review the rest.

I do see that the `src/web/docusaurus/docusaurus.config.js` file is out of date and needs to be rebased.

**Comment by IvaniGabrovsky** [comment]
> @sirinoks we're all in the same boat, I think. Hopefully @IvaniGabrovsky can get a technically-aware Bulgarian reader to review the language itself. We can review the rest.
> 
> I do see that the `src/web/docusaurus/docusaurus.config.js` file is out of date and needs to be rebased.

I have rebased this branch with master.

**Comment by IvaniGabrovsky** [comment]
> @sirinoks we're all in the same boat, I think. Hopefully @IvaniGabrovsky can get a technically-aware Bulgarian reader to review the language itself. We can review the rest.
> 
> I do see that the `src/web/docusaurus/docusaurus.config.js` file is out of date and needs to be rebased.

I got someone to proof read and correct any grammer mistakes. All is good now from my end.

**Comment by sirinoks** [comment]
@humphd On it

**Review by sirinoks — DISMISSED** [review]
Looks good to me. Works.

There seems to be a bug now in our docusaurus translations mechanic, but it's not this PR's fault, I will make an issue

**Comment by humphd** [comment]
@IvaniGabrovsky this needs to be a single commit, rebased on `master`.  See https://telescope.cdot.systems/docs/contributing/git-workflow for tips on how to do it.  Once you've fixed that, we can merge this.

**Comment by mnosov622** [comment]
Hi !

I know Bulgarian. Let me know if I can help in reviewing this PR in terms of language.

**Comment by humphd** [comment]
@mnosov622 yes please, can you read the translation @IvaniGabrovsky has done and give feedback?

**Comment by mnosov622** [comment]
Sure !

**Comment by mnosov622** [comment]
Translation look very clear and understandable for me ! Great job @IvaniGabrovsky :)

**Comment by manekenpix** [comment]
What's the status of this PR? It seems it was reviewed. but the history is not ready. @IvaniGabrovsky can you fix the commit history? we need your changes in a single commit on top of the current `upstream/master`, with no merges of master into your branch.

**Comment by IvaniGabrovsky** [comment]
> What's the status of this PR? It seems it was reviewed. but the history is not ready. @IvaniGabrovsky can you fix the commit history? we need your changes in a single commit on top of the current `upstream/master`, with no merges of master into your branch.

I know what you mean. I am not sure how to squash mutiple commits into 1 commit. Could you give me an instruction how to do that?

**Review by humphd — APPROVED** [review]

**Pull request merged**
