### PR TITLE
Refactor dependency-discovery dockerfile

### LINKED ISSUE #1668: Apply Dockerfile best practices from Snyk recommendations
I saw a nice post today from Synk about best practices for securing node apps in Docker:

https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/

Screen Shot 2021-02-07 at 9 41 11 AM

We should apply as many of these as makes sense for us to our existing Dockerfiles, and also the new ones happening in #1636 for microservices.

### PR DESCRIPTION
**Pull request by Kevan-Y**
## Issue This PR Addresses
Fixes #1668

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
- Add multi-staging layers
- Add Docker Healthcheck

```bash
❯ docker images | grep refactor/dep
refactor/dependency-discovery                   old                d8f8d2d83153   2 hours ago      145MB
refactor/dependency-discovery                   new                96d9269317c7   4 hours ago      146MB
```

## Steps to test the PR
- `cd src/api/dependency-discovery`
- `docker build -t dependency-discovery:test .`
- `docker run --rm -p 10500:10500 dependency-discovery:test`

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by TDDR — APPROVED** [review]
Just so I better understand, a stage is a layer that takes on a task and you each new stage is triggered by a new `FROM` declaration?

**Comment by Kevan-Y** [comment]
> a task and you each new stage is triggered

Yeah a Stage is declared by `FROM`

In this PR I have 3 stages.
Base stage:
- Declare the basic stuff such as environment to run on, stuff to be installed. 
Dependencies stage:
- we reuse base stage which setup for us already node, pnpm and workdir. 
- This stage is for downloading dependencies.
Production stage
- we also reuse base stage.
- we copy all code from build context to our filesystem of the image, and copy node_moduless from dependencies stage to our filesystem of the image. 
- Set env default port
- Add a [Docker healthcheck ](https://docs.docker.com/engine/reference/builder/#healthcheck)
- Add CMD

**Comment by cindyledev** [comment]
Can we keep to the convention used for [SSO Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/sso/Dockerfile) so

`# Stage base #` is called `## Base...` layer because I fear `Stage base` can easily be mistaken for `Staging`, which is something different.

and `# Stage dependencies #` is called `## Production...` layer.

`# Stage production #` layer is a little bit confusing to me because it looks like you're taking the base layer to start the production layer, but the `RUN pnpm install --prod` command is in the `# Stage dependencies` layer, so I don't understand the purpose of the `# Stage dependencies` layer

I may be wrong, but `ENV PORT=10500` is probably meant for development? I don't think end-users would be accessing any ports in prod.

**Comment by Kevan-Y** [comment]
> Can we keep to the convention used for [SSO Dockerfile](https://github.com/Seneca-CDOT/telescope/blob/master/src/api/sso/Dockerfile) so
> 
> `# Stage base #` is called `## Base...` layer because I fear `Stage base` can easily be mistaken for `Staging`, which is something different.
> 
> and `# Stage dependencies #` is called `## Production...` layer.
> 
> `# Stage production #` layer is a little bit confusing to me because it looks like you're taking the base layer to start the production layer, but the `RUN pnpm install --prod` command is in the `# Stage dependencies` layer, so I don't understand the purpose of the `# Stage dependencies` layer
> 
> I may be wrong, but `ENV PORT=10500` is probably meant for development? I don't think end-users would be accessing any ports in prod.

Noted, I will make those changes in this #3239, then once this is merged I will fix this PR and the others Dockerfile already in PR.

Stage dependencies is the layer to download dependencies, and stage production is where we actually run our code.

`ENV PORT=10500`  is the default port for development also it is used in our healthcheck. I don't think setting ENV here will expose that port in production.

**Comment by cindyledev** [comment]
I followed your instructions and got this as a return

```
{
	"level": 30,
	"time": 1647558634528,
	"pid": 1,
	"hostname": "146a0f98126f",
	"req":
	{
		"id": 1,
		"method": "GET",
		"url": "/",
		"query":
		{},
		"params":
		{},
		"headers":
		{
			"host": "localhost:10500",
			"connection": "keep-alive",
			"dnt": "1",
			"upgrade-insecure-requests": "1",
			"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36",
			"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
			"sec-gpc": "1",
			"sec-fetch-site": "none",
			"sec-fetch-mode": "navigate",
			"sec-fetch-user": "?1",
			"sec-fetch-dest": "document",
			"accept-encoding": "gzip, deflate, br",
			"accept-language": "en-CA,en-GB;q=0.9,en-US;q=0.8,en;q=0.7"
		},
		"remoteAddress": "::ffff:172.17.0.1",
		"remotePort": 37652
	},
	"res":
	{
		"statusCode": 404,
		"headers":
		{
			"content-security-policy": "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
			"cross-origin-embedder-policy": "require-corp",
			"cross-origin-opener-policy": "same-origin",
			"cross-origin-resource-policy": "same-origin",
			"x-dns-prefetch-control": "off",
			"expect-ct": "max-age=0",
			"x-frame-options": "SAMEORIGIN",
			"strict-transport-security": "max-age=15552000; includeSubDomains",
			"x-download-options": "noopen",
			"x-content-type-options": "nosniff",
			"origin-agent-cluster": "?1",
			"x-permitted-cross-domain-policies": "none",
			"referrer-policy": "no-referrer",
			"x-xss-protection": "0",
			"access-control-allow-origin": "*",
			"content-type": "text/html; charset=utf-8",
			"content-length": "36",
			"etag": "W/\"24-q/4XQd6XBghuZW34zMh+HzLuxqU\""
		}
	},
	"responseTime": 5,
	"msg": "request completed"
}
```

Is this what I'm supposed to see? Sorry, I'm unfamiliar with this microservice.

**Review by cindyledev — DISMISSED** [review]
Okay so I did the following:
- cd src/api/dependency-discovery
- pnpm start

Yielded the same output as I mentioned above.

**Comment by Kevan-Y** [comment]
> atusCode": 404,
> 		"headers":
> 		{
> 			"content-security-policy": "default-src 'self';base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests",
> 			"cross-origin-embedder-policy": "require-corp",
> 			"cross-origin-opener-policy": "same-origin",
> 			"cross-origin-resource-policy": "same-origin",
> 			"x-dns-prefetch-control": "off",
> 			"expect-ct": "max-age=0",
> 			"x-frame-options": "SAMEORIGIN",
> 			"strict-transport-security": "max-age=15552000; includeSubDomains",
> 			"x-download-options": "noopen",
> 			"x-content-type-options": "nosniff",
> 			"origin-agent-cluster": "?1",
> 			"x-permitted-cross-domain-policies": "none",
> 			"referrer-policy": "no-referrer",
> 			"x-xss-protection": "0",
> 			"access-control-allow-origin": "*",
> 			"content-type": "text/html; charset=utf-8",
> 			"content-length": "36",
> 			"etag": "W/\"24-q/4XQd6XBghuZW34zMh+Hz

Oh yes it should give 404 since there is no `/` route.
This microservices has `/projects`, `/projects/:namespace/:name?`, and `/healthcheck`

**Review by cindyledev — DISMISSED** [review]

**Review by JiaHua-Zou — APPROVED** [review]

**Review by joelazwar — APPROVED** [review]

**Comment by cindyledev** [comment]
Master branch was merged into here

**Review by joelazwar — APPROVED** [review]

**Review by rclee91 — APPROVED** [review]

**Pull request merged**
