### PR TITLE
Modified regex to match user only

### LINKED ISSUE #2707: GitHub Users tagged in posts are not showing under user/organization
**What happened**:
My github profile was linked in Luigi's post, but I do not see my avatar under user/organization
image

**What should have happened**:
I should see my avatar for GitHub under the user/organization. Like this post: 
image

**How to reproduce it (as precise as possible)**:
If you add a blog with a link to a github profile, it will not show up. If you add a repository owned by a user (not organization), the user will show up under user/orgs. This is confusing, the reference was to the repository, which already has its own section on the side. 

**Anything else we need to know?**:

The posts are different because the correct one includes a link to open parliament `https://github.com/michaelmulley/openparliament`, however when we look at the user/orgs we are directed to Michael Mulley's GitHub Page... This can be a bit confusing because I think that Michael Mulley is involved in the post, not his repository (the repo is already in the repository section).

Can we look into whether the users are the repositories for the users, or the actual users' page? It would be cool if we can tag each other's GitHub in the posts. I was considering this when writing mine, but wasn't too sure if it picks up on Telescope... (it doesn't). 

**Environment**:

- OS:
- Browser:

### PR DESCRIPTION
**Pull request by Kevan-Y**
## Issue This PR Addresses
Fixes #2707

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Modified the regex that filters GitHub URL to find GitHub Users tagged in posts to be shown under user/organization
### Before
image 
### After 
image
## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by AmasiaNalbandian — DISMISSED** [review]
Great Work @Kevan-Y  💯 

Look at this: 
The link I hover on here is from michaels repository (you can see link at bottom left):
chrome_8NfDKNEFw6

That link adds both himself under users, and his repository under respository.
chrome_FUDZFwUFP4

**Comment by Kevan-Y** [comment]
Edge case found,
```
Example:
https://github.com/issues
https://github.com/marketplace
https://github.com/features/codespaces
```
Those will still be able to display in the Github info.

**Review by humphd — COMMENTED** [review]
This is the sort of thing that is so easy to test, we should add some for `filterGitHubUrls` in a follow-up.

**Comment by Kevan-Y** [comment]
Don't very have a good solution right now besides hardcoded. Like have a list of reserved names, and do a check before adding the list of repo or org.

The second solution is to call GitHub API to check one by one but might run out of the limit in a sec.

**Comment by humphd** [comment]
I don't think we should call the GitHub API.  Having a list of ones we know are static endpoints would work.  It doesn't need to be perfect, just "better".

**Review by aserputov — APPROVED** [review]

**Review by AmasiaNalbandian — APPROVED** [review]

**Comment by aserputov** [comment]
@humphd can we merge this one ?

**Review by aserputov — APPROVED** [review]

**Pull request merged**
