### PR TITLE
removed photo1.jpg - fixes issue #965

### LINKED ISSUE #965: Remove stray photo1.jpg
**What happened**:
#896 accidentally added `telescope/src/frontend/src/images/photo1.jpg` and forgot to remove it. Please remove the picture. Thanks.

### PR DESCRIPTION
**Pull request by chrispinkney**
## Issue This PR Addresses
Fixes #965 

## Type of Change

- [X] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
This PR removes the unnecessary `photo1.jpg`. I couldn't find any instances of the photo being used anywhere so I think it's safe to say it can be removed.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by manekenpix — CHANGES_REQUESTED** [review]
It seems there's a reference to the `backgrounds` directory somewhere in the code:
```sh

11:43:45.725 | success createSchemaCustomization - 0.007s
-- | --
11:43:45.805 | error
11:43:45.806 | The path passed to gatsby-source-filesystem does not exist on your file system:
11:43:45.806 | src/images/backgrounds
11:43:45.806 | Please pick a path to an existing directory.
```

**Review by humphd — CHANGES_REQUESTED** [review]
Looks like this broke our Gatsby build for the frontend:

```

11:43:45.805 | error
-- | --
11:43:45.806 | The path passed to gatsby-source-filesystem does not exist on your file system:
11:43:45.806 | src/images/backgrounds
11:43:45.806 | Please pick a path to an existing directory.
11:43:45.806 | See docs here - https://www.gatsbyjs.org/packages/gatsby-source-filesystem/
11:43:45.806 |  
11:43:45.808 | not finished source and transform nodes - 0.082s
11:43:46.623 | npm ERR! code ELIFECYCLE
11:43:46.623 | npm ERR! errno 1
11:43:46.625 | npm ERR! @seneca/telescope-frontend@ build: `gatsby build`
11:43:46.625 | npm ERR! Exit status 1
11:43:46.625 | npm ERR!
11:43:46.625 | npm ERR! Failed at the @seneca/telescope-frontend@ build script.
11:43:46.625 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
11:43:46.630 | npm ERR! A complete log of this run can be found in:
11:43:46.630 | npm ERR!     /vercel/.npm/_logs/2020-10-02T15_43_46_626Z-debug.log
11:43:46.635 | npm ERR! code ELIFECYCLE
11:43:46.635 | npm ERR! errno 1
11:43:46.637 | npm ERR! @seneca/telescope@1.2.0 build: `npm run build --prefix src/frontend --`
11:43:46.637 | npm ERR! Exit status 1
```

I guess this file is needed after all?  cc @raygervais, who likely knows.

**Comment by manekenpix** [comment]
@chrispinkney after making changes, run `npm run build` to make sure that your changes don't break the front-end.

**Comment by raygervais** [comment]
Regarding `/src/images/background`, the frontend processes them here: https://github.com/Seneca-CDOT/telescope/blob/543f5aa8caae0c5b5051e34a8a0e88e917c8ccb3/src/frontend/gatsby-config.js#L65

The `stray` image is there to ensure the file structure exists and that we have a default placeholder image since Vercel doesn't download from Unsplash the collection. Thoughts on if we should improve this @humphd ?

**Comment by humphd** [comment]
This is my fault for saying "go ahead and fix this."  Sorry for the confusion.

Question: is what we have now sufficiently documented to avoid this happening in the future?  Maybe this is a docs or code-comment fix instead.

**Comment by chrispinkney** [comment]
Can the folder not just exist empty by itself without a stray image there?

**Comment by chrispinkney** [comment]
Either way I can document this.. somewhere, not sure where. Or maybe replace the stray image with a single pixel picture to save space?

**Comment by raygervais** [comment]
Not having a placeholder / default image would break the `DynamicBackgroundContainer` component I imagine @chrispinkney.

**Comment by manekenpix** [comment]
Does it have to be an image? Otherwise we could go with [this](https://www.git-tower.com/learn/git/faq/add-empty-folder-to-version-control/)

**Comment by chrispinkney** [comment]
That's what I was thinking too, and if so I imagine 1 pixel image work instead. I can try it on my end if you like.

**Comment by raygervais** [comment]
Sure, try it @chrispinkney .

**Comment by chrispinkney** [comment]
So `npm run test` passes with a 1 pixel image but not with only a `.keep` file 👎. Does anyone have any suggestions on how to further approach this?

**Pull request closed without merging**
