### PR TITLE
Fixes #974: Remove className="..." from Header.jsx

### LINKED ISSUE #974: Remove className="..." from Header.jsx
In src/frontend/src/components/Header/Header.jsx, we're using unnecessary `className` attributes.  They can be removed:

```js
 {matches ? <MobileHeader className="mobile-header" /> : <DesktopHeader className="header" />}
```

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
Fixes #974 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

className attributes removed.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by PedroFonsecaDEV** [comment]
Please let me know if everything is good.
Thanks.

**Review by manekenpix — CHANGES_REQUESTED** [review]
@PedroFonsecaDEV it seems there're issues with formatting:

```sh
> @seneca/telescope@1.2.0 prettier-check /home/circleci/telescope
> prettier --check "./**/*.{md,jsx,json,html,css,js,yml}"

Checking formatting...
[warn] src/frontend/src/components/Header/Header.jsx
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

**Comment by PedroFonsecaDEV** [comment]
I hope prettier has been set to your preferences.

**Review by manekenpix — APPROVED** [review]
:+1:

**Review by raygervais — APPROVED** [review]

**Pull request merged**
