### PR TITLE
fixes issue-2446

### PR DESCRIPTION
**Pull request by ycechungAI**
## Issue This PR Addresses
#2446

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

All the new Github links that we added open in a new page but clicking on the blogger's name or the date opens links in the current.
## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

<a href="https://gitpod.io/#https://github.com/Seneca-CDOT/telescope/pull/2459"></a>

### CODE REVIEW

**Review by humphd — APPROVED** [review]

**Comment by humphd** [comment]
@ycechungAI NOTE: we typically want 2 reviews before we marge things.

**Comment by humphd** [comment]
The reason for this is so that we spread knowledge of a change over more devs on the team.

**Comment by ycechungAI** [comment]
is there a way to undo this? or reopen it for another reviewer?

**Comment by humphd** [comment]
Don't worry, it's OK.  We could `git revert` anything we don't want to merge, but it's best to over communicate when landing things, since sometimes order matters, sometimes we need to wait on other things to land first, sometimes we need to fix commit history before landing, etc.

**Pull request merged**
