### PR TITLE
Fixes #2610: update swr to 1.1.2-beta.0

### LINKED ISSUE #2610: Update swr to 1.1.1 in order to pick up Andrew's feature work
One of my goals for 2022 is that we start to become more outward facing in our Telescope contributions, and find ways to give back to the projects that we depend upon.  Christmas came early and we have one of our first examples of what this looks like.  One of our favourite front-end dependencies is Vercel's [swr](https://swr.vercel.app/), and our colleague @Andrewnt219 has been on an epic journey adding a new feature to it:

- https://github.com/vercel/swr/pull/1690
- https://github.com/vercel/swr/pull/1691
- https://github.com/vercel/swr-site/pull/190

This work has been shipped upstream in v1.1.1.  Let's update in order to get the benefits in Telescope!

### PR DESCRIPTION
**Pull request by Andrewnt219**
## Issue This PR Addresses
Closes #2610 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Update `swr` to 1.1.2-beta.0.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by humphd** [comment]
This is doing way more than what it says above.  Why update everything?  Also, I'm surprised this doesn't require a lock file update too.

**Comment by Andrewnt219** [comment]
I'm a bit confused too. When I ran `pnpm update swr` it updated all the dependencies. Thought that was the right way. I'll go with `pnpm install` then.

**Comment by humphd** [comment]
cc @menghif: what's the correct workflow for updating a dep?

**Comment by menghif** [comment]
From `src/web` you can run `pnpm update swr@^1.1.1`. This will update `pnpm-lock.yaml` as well.

https://pnpm.io/cli/update

**Comment by Andrewnt219** [comment]
> From src/web you can run pnpm update swr@^1.1.1. This will update pnpm-lock.yaml as well.

It still updated everything.

> When used without arguments, updates all dependencies. You can use patterns to update specific dependencies.

So the options are 
- `--dev` update this and devDependencies
- `--prod` update this and dependencies + optionalDependencies
- `--no-optional` update this and dependencies + devDependencies

Currently, only `pnpm install swr@^1.1.1` updates swr only.

**Review by humphd — APPROVED** [review]

**Comment by Andrewnt219** [comment]
Oh, I forgot I reset my commit locally, so this PR is closed automatically because there aren't any changes. Reopen it in #2630.

**Pull request closed without merging**
