### PR TITLE
Issue 2525: Fix lint errors

### LINKED ISSUE #2525: Linter was not running the whole time
I was looking at a PR and noticed an unused variable was not detected by `npm run lint`
**Shocking discovery 🙃**

Our linting script `eslint --config .eslintrc.js` does not provide a glob pattern to ESLint and no files are linted.

Developers only notice problems found by ESLint if they have installed the VSCode ESLint extension because the extension puts squiggly underlines on them. Otherwise, running `npm run lint` doesn't show any linting problems.

Plus, we use some Eslint plugins that are not listed in `package.json`. We don't notice this because npm run lint was not running the whole time.

This can explain [the comment](https://github.com/Seneca-CDOT/telescope/pull/2420#pullrequestreview-793706259) by @humphd why the new dashboard passed all eslint tests.

### PR DESCRIPTION
**Pull request by DukeManh**
## Issue This PR Addresses
Fixes #2525 

This fixes some linting errors that were left out due to Eslint not being provided with a target files pattern.

These are some common errors in the code.
1. Using \<a target=“_blank”\> without rel=“referrer” is a [security risk](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/noreferrer)
2. Empty components are self-closing
3. [Prevent invalid characters from appearing in markup](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md#prevent-invalid-characters-from-appearing-in-markup-reactno-unescaped-entities)
4. [No useless escape](https://eslint.org/docs/rules/no-useless-escape)
5. [Disallow continue statements](https://eslint.org/docs/rules/no-continue)
6. [Avoid for..of loop in favor of array iterator](https://medium.com/@paul.beynon/thanks-for-taking-the-time-to-write-the-article-i-enjoyed-it-db916026647)
7. [Consistent return, either always or never](https://eslint.org/docs/rules/consistent-return#require-return-statements-to-either-always-or-never-specify-values-consistent-return)
8. [No restricted globals](https://eslint.org/docs/rules/no-restricted-globals#disallow-specific-global-variables-no-restricted-globals)
9. [No use before define](https://eslint.org/docs/rules/no-use-before-define#disallow-early-use-no-use-before-define)
10. No multiple chained assignment
11. No unused variables
12. [React Hooks must not be called conditionally](https://reactjs.org/docs/hooks-rules.html)

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by DukeManh** [comment]
There is one `Unresolved import` error I didn't fix in `src/api/parser/src/feed/worker.js`:
https://github.com/Seneca-CDOT/telescope/blob/261daa85d1157f2dfa74dc7ff109c681067d625d/src/api/parser/src/feed/worker.js#L6

`waitOnReady` is defined in `src/api/backend/utils/` but is imported in `src/api/parser/src/feed/worker.js`. I don't know why it still worked.
If I change the import from `('../utils/indexer')` to `('../../../../backend/utils/indexer')`, would it affect docker build?.

**Comment by manekenpix** [comment]
@DukeManh the parser microservice is stil WIP (production and staging are not using it), that's why "it works".

> f I change the import from ('../utils/indexer') to ('../../../../backend/utils/indexer'), would it affect docker build?

Yes, it would. In the build process, every service runs isolated in its own container, and doesn't have access to any other service's code (so parser won't be able to use anything outside of `api/parser`.

**Comment by DukeManh** [comment]
So I can disable the rule at that line, right?

**Comment by manekenpix** [comment]
@DukeManh Yes, you can make all the necessary changes to fix linting errors. The `parser` microservice needs a full rework anyway (it's the last service in the legacy back-end, once it's ready, we'll be able to get rid of `src/backend`

**Comment by DukeManh** [comment]
I'm closing this to make another as I was using Seneca's Telescope repo instead of my fork.

**Pull request closed without merging**
