### PR TITLE
Extract Elasticsearch from Satellite for Search

### PR DESCRIPTION
**Pull request by rclee91**
## Issue This PR Addresses
Part of #2578. This PR only extracts Elasticsearch for the Search service

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
- Extracted Elasticsearch from Satellite for Search. 
- Removed `elastic.js`
- Removed `@elastic/elasticsearch'`and `@elastic/elasticsearch-mock` from `package.json`

- All docker containers ran normally using `pnpm services:start `
- The local telescope instance ran normally using `pnpm start`

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — COMMENTED** [review]
Code changes look right, nice work!  Since we have no tests for this, I want to pull this and build it locally to see.  I'll report back with my findings.

**Review by humphd — DISMISSED** [review]
This works great.  I also found another bug while testing it, see https://github.com/Seneca-CDOT/telescope/issues/2755

**Review by JiaHua-Zou — APPROVED** [review]

**Comment by humphd** [comment]
@rclee91 do you want to rebase this and merge?

```
git checkout master
git pull upstream master
git checkout issue#2578
git rebase master
git push origin issue#2578 -f
```

**Comment by rclee91** [comment]
> @rclee91 do you want to rebase this and merge?
> 
> ```
> git checkout master
> git pull upstream master
> git checkout issue#2578
> git rebase master
> git push origin issue#2578 -f
> ```

I'm wondering if its ok to press the big red button down there
image

Or would we want another set of reviews after I rebase?

**Comment by humphd** [comment]
You can do either, but I want to make sure you know the way to do it with the cli, since if you need to squash, you'll have to use it.

**Review by humphd — APPROVED** [review]

**Comment by humphd** [comment]
@rclee91 get another review from @JiaHua-Zou and then hit `Rebase and merge`

**Review by JiaHua-Zou — APPROVED** [review]

**Comment by humphd** [comment]
Good stuff, you two!

**Pull request merged**
