### PR TITLE
All the Elastic APM code from our docker/compose files, envs, logging, Satellite, docs, etc., is cleaned.

### PR DESCRIPTION
**Pull request by aserputov**
Issue: #2498 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
Can you remove https://github.com/Seneca-CDOT/telescope/blob/667b0d80f17a785889a46c6ed09b3976e3ae51e6/docker/production.yml#L211, https://github.com/Seneca-CDOT/telescope/blob/e9d694aba068d8db4f890544b51dabef332e148f/src/api/readme.md#L67 as well?

**Review by humphd — CHANGES_REQUESTED** [review]
You're failing Prettier:

```
Checking formatting...
[warn] docker/production.yml
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

Please set up your environment properly so it auto-formats your code in your editor and when you commit.

**Review by humphd — APPROVED** [review]

**Comment by AmasiaNalbandian** [comment]
@aserputov we got a conflict!!! :) Let me know if you need help.

**Review by AmasiaNalbandian — APPROVED** [review]

**Comment by humphd** [comment]
No to this:

Screen Shot 2022-01-24 at 5 47 59 PM

Please squash and rebase, see https://github.com/Seneca-CDOT/telescope/blob/master/docs/git-workflow.md#squashing-commits

**Review by humphd — CHANGES_REQUESTED** [review]
You lost your changes with this rebase.  Please bring back your previous branch changes.

**Review by humphd — CHANGES_REQUESTED** [review]
You only need 1 of the 3 commits:

```sh
$ git checkout -B issue-2498 fcf1e5758e057326ec220b3fd9c364971cba9089
$ git push origin issue-2498 -f
```

**Comment by aserputov** [comment]
Why did do we use this commit "fcf1e5758e057326ec220b3fd9c364971cba9089" ?

**Comment by humphd** [comment]
The other 2 are not really part of this fix.

**Review by humphd — APPROVED** [review]
Excellent

**Comment by AmasiaNalbandian** [comment]
Were there not more files here before? Can you confirm this was all? @aserputov

**Comment by aserputov** [comment]
@AmasiaNalbandian, yes, you are right. There were more files before, but to clean `pnpm-lock.yaml` I will need to create a pull request to Satellite.

**Review by TueeNguyen — APPROVED** [review]
Nit: maybe we can change the title to `'Cleaning All the Elastic APM...'`

**Review by AmasiaNalbandian — APPROVED** [review]

**Pull request merged**
