### PR TITLE
Fix unclickable logo in [next] desktop and mobile header

### PR DESCRIPTION
**Pull request by yuanLeeMidori**
## Issue This PR Addresses
Fixes: #1661 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by manekenpix — CHANGES_REQUESTED** [review]
Tested locally :+1:.
 Should we add this to the mobile header as well?

**Review by humphd — CHANGES_REQUESTED** [review]
Looks good, let's do the same on the mobile header.

**Review by manekenpix — APPROVED** [review]
LGTM :+1:

**Comment by yuanLeeMidori** [comment]
@manekenpix that's fast! thank you for the review~

**Comment by manekenpix** [comment]
we should probably avoid this in the future

image

I think it's better to rebase than merging `master` into your branch

**Comment by yuanLeeMidori** [comment]
@manekenpix will do, thank you for the reminder!

**Review by humphd — APPROVED** [review]

**Pull request merged**
