### PR TITLE
Add SwaggerUI middleware and document feed.js

### PR DESCRIPTION
**Pull request by c3ho**
## Issue This PR Addresses
Progress towards #203 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Adding SwaggerUI so there's better documentation of params/queries in our REST APIs for our routes

Still a work in progress for now, having issue getting Swagger to even see any of the routes... which was not happening in the example I was learning with.

To test:
1. `npm start`
2. go to `http://localhost:<port>/api-docs`

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
I've been following this [example](https://blog.logrocket.com/documenting-your-express-api-with-swagger/) when learning how to  use Swagger, I was able to get the tutorial working... However trying the same things here didn't work out as well. For some reason Swagger can't see the feeds route no matter what I do.

**Comment by humphd** [comment]
@c3ho can we get an update on this?  Is this ready for review?  Are you still working on it?

**Comment by c3ho** [comment]
Hi @humphd , this will probably have to wait until the weekend as I'll be fixing my component PR tonight first. Sorry!

**Comment by humphd** [comment]
Fantastic.  If you're willing to focus on the next.js port, that's our priority this week for sure.

**Comment by chrispinkney** [comment]
Closed via Calvin's request

**Pull request closed without merging**
