### PR TITLE
Closes #2334: bull-board has been deprecated, update to use @bull-board/* packages

### LINKED ISSUE #2334: bull-board has been deprecated, update to use @bull-board/* packages
We [use bull-board](https://github.com/Seneca-CDOT/telescope/search?q=bull-board) to visualize our parser feed queue.  The [package we use is no longer supported](https://www.npmjs.com/package/bull-board), and they have [split things up into a bunch of smaller packages](https://www.npmjs.com/search?q=%40bull-board).

We should update our use of bull-board to use the new packages.

### PR DESCRIPTION
**Pull request by manekenpix**
## Issue This PR Addresses

Closes #2334 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR removes the deprecated `bull-board` package and adds the new versions structured as `@bull-board/*`.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by humphd** [comment]
> @humphd I'll file an issue.

Perfect, thank you!

**Comment by humphd** [comment]
@manekenpix how would you feel about rebasing to pick up #2344 and throwing it on staging so we can test?

**Comment by manekenpix** [comment]
@humphd Done!

**Comment by humphd** [comment]
I think we could consider landing this, and fixing the static asset loading and redirect admin issue in follow ups.  What do you think?

**Comment by humphd** [comment]
The script loading error is interesting:

- https://dev.telescope.cdot.systems/admin/queues/static/images/logo.svg is 200
- https://dev.telescope.cdot.systems/admin/queues/static/main.d02819a4e1fb5b798137.css is 404

Is this a webpack failure somehow, with it not building the bundle correctly?

**Comment by humphd** [comment]
I don't think it's CSP, because the browser would warn about a CSP violation.  This looks like a routing or simple 404 issue.  I suspect it's nginx/traefik somehow.

**Comment by manekenpix** [comment]
I get a CSP warning:
image

@humphd can you confirm that you also get this warning when you try with your user?

**Comment by humphd** [comment]
@manekenpix does https://dev.telescope.cdot.systems/admin/queues/static/vendor.e6df5f52c81b99d9f88f.js actually exist on the server?  Is it possible that our build isn't passing through the `NODE_ENV` as `production` and it's building it without hashing, but then at runtime expects hashed versions?

**Comment by manekenpix** [comment]
@humphd I noticed this:

`dev`
image

`local`
image

Not sure why the URIs are different. Maybe this is why it can't find the file?

**Comment by humphd** [comment]
@manekenpix go ahead and merge this, and we can solve the CORS/404 stuff later.

**Pull request merged**
