### PR TITLE
Fix #190: Create an template for email-sender

### LINKED ISSUE #190: Create an Email Templates for NodeMailer
I created a basic email sender in issue #25. In this issue I would like to create a email template to make it easier to send emails/ will be more visually appealing than plain text.

### PR DESCRIPTION
**Pull request by RyanWils**
I created a template for the email-sender, this will make it easier for the users to identify the errors that are coming in from the Telescope project. 

Currently when you send an email, it would send plain text for the message that is passed. 
image

The functionality for the email sender did not change, but is displayed in the following format
image

I created the email template using HTML Table elements and made a simplistic design which will make it easier for the code to be maintained/changed if necessary.

### CODE REVIEW

**Comment by cindyledev** [comment]
I'm unfamiliar with Nodemailer and the email-sender.js, how do I go about testing this and sending an email?

**Comment by RyanWils** [comment]
Hi Cindy,

Since we currently have no decided on an SMTP server. If you want to test nodemailer with an SMTP server you can use the following, this is the one I've been testing it with. You will have to change a some parameters to work with the googlemail SMTP servers. 
image
```
let transporter = nodemailer.createTransport({
        host: 'smtp.googlemail.com', // Gmail Host
        port: 465, // Port
        secure: true, // this is true as port is 465
        auth: {
            user: 'GMAIL_USERNAME', //Gmail username
            pass: 'GMAIL_PASSWORD' // Gmail password
        }
    });
```
I usually test it in the index.js, include the following.
const sendEmail = require('./email-sender') 

Currently you have to call this function.
sendEmail.sendMessage('who you want to send it to example student@hotmail.com','Subject Line','\<p>Message Body\</p>') <- Have to use an html tag

With the changes I have included to call the function 
sendEmail.sendMessage('who you want to send it to example student@hotmail.com','Subject Sentence','Message Body') <- You dont need to include the html tag

**Comment by cindyledev** [comment]
Sorry, you're gonna have to dummy it down for me some more @_@

So I changed the security settings (turned on the access thing) in my gmail account like how you did it in your screenshot.

Changed the variables in `env.example`
Annotation 2019-12-02 000901

Added this to `index.js`
Annotation 2019-12-02 000901_

Annotation 2019-12-02 000901__

Changed the port and secure values in `email-sender.js`
Annotation 2019-12-02 000901____

Then I run `npm start` (I've also ran `node index.js`) and get this
Annotation 2019-12-02 000901___

I tried both port `465` and `25`, and secure `true` and `false`

**Comment by RyanWils** [comment]
Hi Cindy,
Sorry my explanation could of used some work. Although we have these .env variables, I don't think the .env configuration is called so for testing purposes just hardcode the variables instead of the .environment variables

**Comment by cindyledev** [comment]
Good news! I hardcoded the variables as you said but I was getting another error regarding `Self signed certificate in certificate chain`. I figured it out though, I just needed to add the `tls` part
```
let transporter = nodemailer.createTransport({
        host: 'smtp.googlemail.com', // Gmail Host
        port: 465, // Port
        secure: true, // this is true as port is 465
        auth: {
            user: 'GMAIL_USERNAME', //Gmail username
            pass: 'GMAIL_PASSWORD' // Gmail password
        },
        tls: {
            rejectUnauthorized: false,
        }
    });
```

**Comment by RyanWils** [comment]
Glad you liked it and got it to work :). I really appreciate the supportive feedback, 1 more review and we can hopefully get this merged.

**Comment by RyanWils** [comment]
Hi Karla, 
It seems you approved these changes, but didn't leave a comment. 
I assume you tested it and it looks fine.
I will proceed with the merge, if this is true.

**Pull request merged**
