### PR TITLE
Enabling cache for actions/setup-node

### LINKED ISSUE #2537: Stop using actions/cache in GitHub Actions Workflows
See https://github.com/Seneca-CDOT/telescope/pull/2536#issuecomment-981127629.  Let's try using the built-in npm `cache` facility of the setup-node action and remove the actions/cache.

### PR DESCRIPTION
**Pull request by dhillonks**
## Issue This PR Addresses
Closes #2537 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [X] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Currently, the workflows use `actions/cache`, but `actions/node-setup` now has optional functionality to [cache and restore dependencies](https://github.com/actions/setup-node#caching-packages-dependencies). Following changes were made to `node-js-ci` and `release` workflow:

- Removed `actions/cache`
- Enabled cache for `actions/setup-node`

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: N/A
- [X] **Documentation**: N/A

### CODE REVIEW

**Comment by humphd** [comment]
This is going to get updated by #2545, but in the mean time, its a good change for us to take.

**Review by humphd — CHANGES_REQUESTED** [review]
This isn't passing CI, can you get it working there?

**Comment by dhillonks** [comment]
> This isn't passing CI, can you get it working there?

Yes, looking into the failure right now

**Comment by dhillonks** [comment]
The runs are failing as there is no lock file (such as `package-lock.json`) since the project is using `save-exact`. This seems like a limitation of the built-in cache functionality in [actions/setup-node](https://github.com/actions/setup-node#caching-packages-dependencies), there doesn't seem to be any option for projects without lock files.

As a workaround, I've added a step to generate a `lock` file using:
```
npm install --package-lock-only
```
This seems to have fixed the lock file issue and the `prettier` and `eslint` runs are now passing. Still looking into the `test` run failures.

**Comment by dhillonks** [comment]
The `unit` test runs were failing due to `postinstall` running `run-s install:*` on windows in `package-lock.json generation step`, causing an error as no packages had yet been installed. To fix this, I added a `--ignore-scripts` to the lock file generation step.

All CI runs are now passing and the cache seems to be working (except in the unit test runs as they were failing earlier and ran for the very first time)
image

@humphd Could you please take a look?

**Comment by humphd** [comment]
Spoke with @dhillonks about folding this work into #2545 instead, and he's going to help review and get that landed.

**Pull request closed without merging**
