### PR TITLE
Fixed #1327: Added Social Media Sharing Buttons to Post.jsx with functions

### LINKED ISSUE #1327: Suggest new feature to share a blog post to personal social media from Telescope.
**What would you like to be added**:
Viewers has the ability to share the blog that they enjoy reading to their personal social medias. The actually link shared will be the original url

**Why would you like this to be added**:
It would help to increase the exposure of the blog writers to more audiences.

### PR DESCRIPTION
**Pull request by tonyvugithub**
## Issue This PR Addresses
Fixed #1327 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Added social media sharing buttons to post. 

Desktop
image
Mobile
image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by PedroFonsecaDEV — CHANGES_REQUESTED** [review]
1) What happens to admin buttons if you face a big title? 
Screen Shot 2020-11-15 at 2 36 32 PM
note: I'm not logged as admin in this photo.

2) The buttons do not have the same size and so on.

3) If we are using icons without text for admin buttons, we should use only icons without text to social media too. 

4) react-social-sharing doesn't seem to be the best solution for us.

**Comment by tonyvugithub** [comment]
@PedroFonsecaDEV : I can make them all icon. Let me check what would happen to admins button when there is very long title

**Comment by humphd** [comment]
I also think this is something you probably only need to see on hover vs. all the time.

**Comment by tonyvugithub** [comment]
@humphd : I am listening. Maybe when you hover the header?

**Comment by humphd** [comment]
Right onhover over post header.  I don't want to see this all the time, if we do this at all.

**Comment by tonyvugithub** [comment]
@PedroFonsecaDEV : This is what happened to admin buttons when the title is long 
image

**Comment by PedroFonsecaDEV** [comment]
@tonyvugithub 
So the better approach is to create a container(hover) with all buttons (social media + admin) and insert it where your social media buttons are.

FA09358D-67E8-44A1-9660-ED9C304056A0_4_5005_c

I think this PR needs to run as a draft right now. We still need to think if we need this feature and when we need these features.

**Comment by tonyvugithub** [comment]
@PedroFonsecaDEV: at the moment we dont really use the admin buttons hence the inconsitent styling. I also agree that this is an extra feature that would not be significant to Telescope. So if we really dont want to have social sharing feature on the site, I can close this isue.

**Comment by PedroFonsecaDEV** [comment]
Make this PR as a draft. So you can work on it in the future, at the right moment.

**Pull request closed without merging**
