### PR TITLE
feat: New Logo

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
Fixes: #1664 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Screen Shot 2021-02-05 at 8 04 05 PM

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by Metropass — APPROVED** [review]
Absolutely Stunning. I really like the new logo. Minimalism, the Telescope looks like a T. 
Well done!

**Review by birtony — CHANGES_REQUESTED** [review]
The new logo looks great @PedroFonsecaDEV! Could you also optimize it with https://jakearchibald.github.io/svgomg/, please?

**Comment by HyperTHD** [comment]
Agree with Anton. Other than that, looks amazing

**Review by yuanLeeMidori — DISMISSED** [review]
Thank you Pedro for the hard work, this is amazing :smile:

**Comment by PedroFonsecaDEV** [comment]
@birtony @HyperTHD @yuanLeeMidori @Metropass 
Sorry guys I had a bad time dealing with the SVG file, but now the SVG is good and optimized.

**Review by humphd — CHANGES_REQUESTED** [review]
Love this.

Can we take this opportunity to generate all the icon sizes and types we'll need?  Instead of the logo2.0.png you have now, let's do all the sizes based on this new one.

Tools like https://app-manifest.firebaseapp.com/ or https://www.pwabuilder.com/ can help do this, or we could add a script to our build with something like https://www.npmjs.com/package/pwa-asset-generator.

We end up needing like 12 different sizes and types by the time we are done, especially for #801.

**Comment by PedroFonsecaDEV** [comment]
> Love this.
> 
> Can we take this opportunity to generate all the icon sizes and types we'll need? Instead of the logo2.0.png you have now, let's do all the sizes based on this new one.
> 
> Tools like https://app-manifest.firebaseapp.com/ or https://www.pwabuilder.com/ can help do this, or we could add a script to our build with something like https://www.npmjs.com/package/pwa-asset-generator.
> 
> We end up needing like 12 different sizes and types by the time we are done, especially for #801.

Done!

**Review by yuanLeeMidori — APPROVED** [review]

**Comment by cindyledev** [comment]
Silly question but why are the images called 'apple-*'? Is that an image convention? And I could be wrong but I think we will need an actual .svg file for icons or favicons too

**Comment by PedroFonsecaDEV** [comment]
> Silly question but why are the images called 'apple-*'? Is that an image convention? And I could be wrong but I think we will need an actual .svg file for icons or favicons too

Hey @cindyledev we have the SVG file, but these images are related to PWA conventions. 
"When you build a PWA with a goal of providing native-like experiences on multiple platforms and stores, you need to meet with the criteria of those platforms and stores with your PWA assets; icon sizes and splash screens." 
you can check for more information: [pwa-asset-generator](https://github.com/onderceylan/pwa-asset-generator)

**Comment by cindyledev** [comment]
> > Silly question but why are the images called 'apple-*'? Is that an image convention? And I could be wrong but I think we will need an actual .svg file for icons or favicons too
> 
> Hey @cindyledev we have the SVG file, but these images are related to PWA conventions.
> "When you build a PWA with a goal of providing native-like experiences on multiple platforms and stores, you need to meet with the criteria of those platforms and stores with your PWA assets; icon sizes and splash screens."
> you can check for more information: [pwa-asset-generator](https://github.com/onderceylan/pwa-asset-generator)

Thank you, I understand now :)

**Comment by birtony** [comment]
Wow, that's a lot of additions since last time I reviewed! 👍🏼@PedroFonsecaDEV I'm sorry for late response, had computer detox yesterday

**Pull request merged**
