### PR TITLE
Exclude Satellite from pnpm workspace

### PR DESCRIPTION
**Pull request by DukeManh**
Exclude Satellite from pnpm workspaces.

I think we misunderstood the purpose of `pnpm-workspace.yaml`. The file exists to tell pnpm to link packages from the workspace if the available packages match the declared ranges.

So if we do not want to use the local Satellite, for example, we should not list it in `pnpm-worksapce`.

Better fix of #3191

### CODE REVIEW

**Comment by DukeManh** [comment]
I updated the description.

**Comment by rclee91** [comment]
I thought we didn't want the services to use local Satellite though

**Comment by DukeManh** [comment]
@rclee91, my bad, I updated the description again, s/do/do not/

**Comment by rclee91** [comment]
In this case, do we still use `pnpm install` to get the right dependencies inside of Satellite?

**Comment by cindyledev** [comment]
I guess we're giving Satellite the same treatment as React Native so they're both living in the same repository as the rest of the services but they functioning like introverted roommates that don't explicitly communicate with the other services unless we want them to by doing this?

<path/to/service>/package.json
```
"@senecadot/satellite: workspace:^"
```

**Comment by DukeManh** [comment]
> In this case, do we still use pnpm install to get the right dependencies inside of Satellite?

yes

**Review by rclee91 — APPROVED** [review]

**Comment by DukeManh** [comment]
Wait, I'm wrong.

**Comment by rclee91** [comment]
> > In this case, do we still use pnpm install to get the right dependencies inside of Satellite?
> 
> yes

Sorry, have you tried deleting all the `node_modules` and doing `pnpm install` to see what happens to the `node_modules`? Including the ones in `src/satellite`
Taking out Satellite in the `pnpm workspace` was a part of the "hack" in #3191 , I seem to remember it won't create `node_modules` in `src/satellite`
I could try this again, but my potato laptop takes a long time to test. Just wondering if you had tried.

**Comment by cindyledev** [comment]
We probably have to do the same thing we do with React Native with `postinstall`,

    "postinstall": "cd src/mobile && npm install"

**Comment by DukeManh** [comment]
> We probably have to do the same thing we do with React Native with postinstall,

Yes, probably, either we have to figure out how to link Satellite or do that.
We could use the `workspace:protocol` but it makes Vercel deployment fails here https://github.com/Seneca-CDOT/telescope/runs/5576676664?check_suite_focus=true

**Comment by DukeManh** [comment]
This is probably a bug in pnpm https://github.com/pnpm/pnpm/issues/3561

**Comment by rclee91** [comment]
Is this something that is still needed, even after the merge of #3247 ?

**Comment by DukeManh** [comment]
@rclee91 we don't need this anymore. I'm gonna close it.

**Pull request closed without merging**
