### PR TITLE
Fix #33 - Create a logo for CDOT's Telescope

### LINKED ISSUE #33: Branding: we need a logo!
Is anyone good at drawing logos?  We could use one, so we can put it in our README.

### PR DESCRIPTION
**Pull request by brucremo**
### Have I seen this somewhere?
If you are familiar with Seneca CDOT (which I hope that you are) you will quickly notice the resemblance with its logo. Telescope is an important part of CDOT and collaboration within it, so I decided to keep CDOT's visual identity in this logo, while adding features that are also specific to the project.

### The Telescope
I hope you enjoy things about space as much as I do, but even if you don't you probably noticed that the telescope chosen to be in this logo is the Hubble! You might ask ok Bruno, but why the Hubble? Did you know that "Hubble is the only telescope designed to be maintained in space by astronauts. Five Space Shuttle missions have repaired, upgraded, and replaced systems on the telescope, including all five of the main instruments" ([Wikipedia](https://en.wikipedia.org/wiki/Hubble_Space_Telescope)). Doesn't this also sound familiar to you? The Hubble is also all about collaboration! 

Also, this [hubble sketch](https://www.deviantart.com/terisa-san/art/Looking-at-the-stars-Hubble-Space-Telescope-779048537) has been magnificently drawn by Devianart's user [Terisa-san](https://www.deviantart.com/terisa-san)! Her drawing was part of a challenge and she published it as a [Creative Commons Attribution-Noncommercial-No Derivative Works 3.0 License](https://creativecommons.org/licenses/by-nc-nd/3.0/), and since we are not using it for commercial purposes it is also free to share in any medium! Her original image was not changed itself and it was only added into our logo as it is.

The icons around the main circle are icons of some of the main blogging platforms that exist today, Medium, Blogger and Wordpress. These icons represent all the blogs that are in CDOT's orbit in a sense that our Telescope will be "watching them".

### Building the Logo
This logo has also been built with only open source features but I have also tried to stick to this idea while creating it, so I have used [GIMP](https://www.gimp.org/), which is also created by the open source community, to manipulate the images for this logo.

### CODE REVIEW

**Comment by manekenpix** [comment]
- telescope-logo-136px.png
telescope-logo-136px

- telescope-logo-full.png
telescope-logo-full

**Comment by agarcia-caicedo** [comment]
I noticed that you've used several logos inside our logo, this is what each company has to say about the usage of their logos:

[Wordpress:](http://wordpressfoundation.org/trademark-policy/)
> Similarly, it’s OK to use the WordPress or WordCamp logo as part of a page that describes your products or services, but it is not OK to use it as part of your company or product logo or branding itself.

[Blogger:](https://www.google.com/permissions/logos-trademarks/)

> First things first: you’ll need our permission to use our logos or trademarks.

> Don’t lock up the Google logo with your own logo.

[Medium](https://medium.design/logos-and-brand-guidelines-f1a01a733592)

> Clearspace and Positioning
The wordmark should always be surrounded by generous white space. The diagram below defines the minimum amount of clear space needed, which is based on the x-height in the wordmark.

Even though the logos are not copyrighted, they still fall under trademark and have very specific guidelines on how they can be used.

**Comment by lucacataldo** [comment]
I agree with @Grommers00 , looks good but proper credit would also have to be given to the original author in addition to the fact that this might still be considered a derivative work considering it's been merged with the CDOT Logo (which also doesn't really have a specific license that I see attached to it which may be problematic)

**Comment by brucremo** [comment]
Thanks for the feedback @agarcia-caicedo, @lucacataldo and @Grommers00! I will adapt the logo to fit the recommendations, especially regarding proper credits to the author, in the case this design is kept and the blogging platform's logos

**Comment by manekenpix** [comment]
telescope-logo-136px
telescope-logo

**Comment by brucremo** [comment]
Good night everyone! I have fixed the logo, removing any copyrighted content from it. The new Hubble image has been edited by myself and it comes from [NASA's website](https://apod.nasa.gov/apod/image/0211/hst_sts82_big.jpg), whose [contents are public domain](https://www.nasa.gov/multimedia/guidelines/index.html).

The fixed logo is as follows:

**Comment by Grommers00** [comment]
Looks good!

**Comment by humphd** [comment]
This has 2 reviews, so I'll merge.  If people want to iterate on this or go in other directions later, we can do that in follow-ups.

One thing I'd expect for a logo are files people can edit vs. assets that are built from it.  Vectors, SVG, or something you can edit, but this is only rendered PNG.  Hard to work with these.

Let's address it in follow-ups.

**Pull request merged**
