### PR TITLE
SearchBar (new PR)

### LINKED ISSUE #1912: SearchBar re-design
Since I found UI problem with the current searchbar, I suggest a new design for it.

Any suggestion?
Thanks.

### PR DESCRIPTION
**Pull request by huyxgit**
Closes #1912 

Screen Shot 2021-04-19 at 10 38 10 PM

### CODE REVIEW

**Comment by huynguyez** [comment]
@HyperTHD  @PedroFonsecaDEV @izhuravlev @rjayroso @humphd

**Review by DukeManh — DISMISSED** [review]

**Review by izhuravlev — COMMENTED** [review]
I mentioned that there is a slight movement of the whole SearchBar when you hover over the search and clear buttons. We might want to fix this and make the Search and Clear buttons more clickable.

Other than this I can approve this PR

**Comment by huynguyez** [comment]
@izhuravlev what movement? you meant outline? the 'focus' event's more important, as long as it stay on a click, 'hover' making some 'move' you said, however, this isn't negative. In term of visibility of search/clear button. it 'submit' when user hit 'enter' then no need to highlight the search button.

**Comment by chrispinkney** [comment]
Blocked until we get the advanced search stuff.

**Comment by HyperTHD** [comment]
@chrispinkney Advanced search was supposed to always go in another PR. 
Not sure why the other one was closed, but this is GTM

**Comment by huynguyez** [comment]
@chrispinkney @HyperTHD  Same, I wasn't really get this, because the advanced search will be in a separate PR, why do I need to wait for that to merge this PR? combining both into one?

**Comment by humphd** [comment]
@huynguyez we want these changes to land as a pair, since they depend on each other.  If we land this and don't do the advanced search, we regress the search feature we have now.

You can make a branch off of this work to do the advanced bits, and then once we land, rebase on master.

**Comment by izhuravlev** [comment]
@huynguyez Do you need reviews for this now? Is it ready?

**Comment by AmasiaNalbandian** [comment]
There is work in progress on the branch right here: 
https://github.com/AmasiaNalbandian/telescope/tree/issue-2110-advancedsearch

I am going to close this PR as it is abandoned, and I have picked up the issue.

**Pull request closed without merging**
