### PR TITLE
Link to Telescope documentation bug fix

### PR DESCRIPTION
**Pull request by mnosov622**
Issue #3675
 
 # Overview
 
 Link to Telescope documentation fix
 
 Sorry for any inconvenience, this is my first experience contributing to big projects :)

### CODE REVIEW

**Comment by humphd** [comment]
The Vercel build is failing, not sure what this is, but [this](https://stackoverflow.com/questions/52486219/unable-to-resolve-module-babel-runtime-helpers-interoprequiredefault) claims we need to add `@babel/runtime` as a dep and/or upgrade it:

```
[22:49:10.092] Cloning github.com/Seneca-CDOT/telescope (Branch: master, Commit: 5b86777)
[22:49:12.419] Cloning completed: 2.327s
[22:49:12.986] Looking up build cache...
[22:49:19.703] Build cache downloaded [79.80 MB]: 6494.167ms
[22:49:19.760] Running "vercel build"
[22:49:20.503] Vercel CLI 28.4.6
[22:49:20.935] Running "install" command: `pnpm install`...
[22:49:22.035] Progress: resolved 1, reused 0, downloaded 0, added 0
[22:49:23.038] Progress: resolved 12, reused 0, downloaded 8, added 0
[22:49:24.043] Progress: resolved 23, reused 0, downloaded 18, added 0
[22:49:25.056] Progress: resolved 33, reused 0, downloaded 27, added 0
[22:49:26.069] Progress: resolved 38, reused 0, downloaded 33, added 0
[22:49:27.069] Progress: resolved 41, reused 0, downloaded 39, added 0
[22:49:28.099] Progress: resolved 43, reused 0, downloaded 41, added 0
[22:49:29.082] Progress: resolved 45, reused 0, downloaded 44, added 0
[22:49:30.105] Progress: resolved 46, reused 0, downloaded 44, added 0
[22:49:31.093] Progress: resolved 46, reused 0, downloaded 45, added 0
[22:49:32.138] Progress: resolved 47, reused 0, downloaded 45, added 0
[22:49:34.256] Progress: resolved 47, reused 0, downloaded 46, added 0
[22:49:35.393] Progress: resolved 48, reused 0, downloaded 46, added 0
[22:49:36.393] Progress: resolved 49, reused 0, downloaded 46, added 0
[22:49:37.393] Progress: resolved 49, reused 0, downloaded 47, added 0
[22:49:38.401] Progress: resolved 64, reused 0, downloaded 48, added 0
[22:49:39.409] Progress: resolved 127, reused 0, downloaded 105, added 0
[22:49:40.416] Progress: resolved 186, reused 0, downloaded 165, added 0
[22:49:41.416] Progress: resolved 236, reused 0, downloaded 216, added 0
[22:49:42.419] Progress: resolved 267, reused 0, downloaded 247, added 0
[22:49:43.420] Progress: resolved 321, reused 0, downloaded 304, added 0
[22:49:44.654] Progress: resolved 426, reused 0, downloaded 411, added 0
[22:49:44.757] Already up-to-date
[22:49:45.654] Progress: resolved 426, reused 0, downloaded 413, added 0, done
[22:49:46.149] 
[22:49:46.181] Detected Next.js version: 12.1.6
[22:49:46.261] Running "pnpm run build"
[22:49:46.933] 
[22:49:46.933] > @senecacdot/telescope-frontend@3.0.0 build /vercel/path1
[22:49:46.933] > next build && next export
[22:49:46.933] 
[22:49:48.829] Trying to load missing ENV variables from /.env
[22:49:48.830] Trying to load missing ENV variables from /config/env.development
[22:49:48.831] Using NEXT_PUBLIC_WEB_URL=https://telescope-68ci4dj5s-humphd.vercel.app
[22:49:48.831] Using NEXT_PUBLIC_IMAGE_URL=https://dev.api.telescope.cdot.systems/v1/image
[22:49:48.831] Using NEXT_PUBLIC_POSTS_URL=https://dev.api.telescope.cdot.systems/v1/posts
[22:49:48.832] Using NEXT_PUBLIC_SSO_URL=https://dev.api.telescope.cdot.systems/v1/auth
[22:49:48.832] Using NEXT_PUBLIC_SEARCH_URL=https://dev.api.telescope.cdot.systems/v1/search
[22:49:48.832] Using NEXT_PUBLIC_FEED_DISCOVERY_URL=https://dev.api.telescope.cdot.systems/v1/feed-discovery
[22:49:48.832] Using NEXT_PUBLIC_STATUS_URL=https://dev.api.telescope.cdot.systems/v1/status
[22:49:48.832] Using NEXT_PUBLIC_GIT_COMMIT=undefined
[22:49:48.832] Using NEXT_PUBLIC_SUPABASE_URL=https://dev.api.telescope.cdot.systems/v1/supabase
[22:49:48.833] Using NEXT_PUBLIC_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
[22:49:48.833] Using NEXT_PUBLIC_DEPENDENCY_DISCOVERY_URL=https://dev.api.telescope.cdot.systems/v1/dependency-discovery
[22:49:48.835] warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
[22:49:48.898] info  - Checking validity of types...
[22:49:55.571] error - ESLint: Failed to load plugin 'react' declared in '.eslintrc.js » @senecacdot/eslint-config-telescope': Cannot find module 'eslint-plugin-react' Require stack: - /vercel/path1/__placeholder__.js Referenced from: /vercel/path1/node_modules/.pnpm/@senecacdot+eslint-config-telescope@1.1.0_eslint@7.32.0/node_modules/@senecacdot/eslint-config-telescope/index.js
[22:49:55.579] info  - Creating an optimized production build...
[22:49:55.640] > [PWA] Compile client (static)
[22:49:55.641] > [PWA] Auto register service worker with: /vercel/path1/node_modules/.pnpm/next-pwa@5.4.6_b9348bf848bb7cd32c9b4304596174f6/node_modules/next-pwa/register.js
[22:49:55.641] > [PWA] Service worker: /vercel/path1/public/sw.js
[22:49:55.641] > [PWA]   url: /sw.js
[22:49:55.642] > [PWA]   scope: /
[22:49:55.925] > [PWA] Compile server
[22:49:55.930] > [PWA] Compile server
[22:50:18.137] info  - Compiled successfully
[22:50:18.137] info  - Collecting page data...
[22:50:19.924] info  - Generating static pages (0/5)
[22:50:20.011] info  - Generating static pages (1/5)
[22:50:20.022] info  - Generating static pages (2/5)
[22:50:20.029] info  - Generating static pages (3/5)
[22:50:20.065] info  - Generating static pages (5/5)
[22:50:20.081] info  - Finalizing page optimization...
[22:50:20.085] 
[22:50:20.117] Page                                       Size     First Load JS
[22:50:20.117] ┌ ○ /                                      11 kB           195 kB
[22:50:20.117] ├   /_app                                  0 B             109 kB
[22:50:20.118] ├ ○ /404                                   179 B           109 kB
[22:50:20.118] ├ λ /dependencies                          30.8 kB         245 kB
[22:50:20.118] ├ ○ /error                                 3.53 kB         133 kB
[22:50:20.118] ├ λ /search                                4.66 kB         241 kB
[22:50:20.118] └ ○ /signup                                42.5 kB         194 kB
[22:50:20.118] + First Load JS shared by all              109 kB
[22:50:20.118]   ├ chunks/framework-248ddb2458fac65d.js   42.2 kB
[22:50:20.119]   ├ chunks/main-72922e6a2d43303e.js        31.1 kB
[22:50:20.119]   ├ chunks/pages/_app-d1db4aa3365a299d.js  33.5 kB
[22:50:20.119]   ├ chunks/webpack-546fab29d489db27.js     1.78 kB
[22:50:20.119]   └ css/c653c2c1a3dbcc3f.css               1.55 kB
[22:50:20.119] 
[22:50:20.119] λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
[22:50:20.120] ○  (Static)  automatically rendered as static HTML (uses no initial props)
[22:50:20.120] 
[22:50:21.490] Trying to load missing ENV variables from /.env
[22:50:21.491] Trying to load missing ENV variables from /config/env.development
[22:50:21.492] Using NEXT_PUBLIC_WEB_URL=https://telescope-68ci4dj5s-humphd.vercel.app
[22:50:21.492] Using NEXT_PUBLIC_IMAGE_URL=https://dev.api.telescope.cdot.systems/v1/image
[22:50:21.492] Using NEXT_PUBLIC_POSTS_URL=https://dev.api.telescope.cdot.systems/v1/posts
[22:50:21.492] Using NEXT_PUBLIC_SSO_URL=https://dev.api.telescope.cdot.systems/v1/auth
[22:50:21.492] Using NEXT_PUBLIC_SEARCH_URL=https://dev.api.telescope.cdot.systems/v1/search
[22:50:21.493] Using NEXT_PUBLIC_FEED_DISCOVERY_URL=https://dev.api.telescope.cdot.systems/v1/feed-discovery
[22:50:21.493] Using NEXT_PUBLIC_STATUS_URL=https://dev.api.telescope.cdot.systems/v1/status
[22:50:21.493] Using NEXT_PUBLIC_GIT_COMMIT=undefined
[22:50:21.493] Using NEXT_PUBLIC_SUPABASE_URL=https://dev.api.telescope.cdot.systems/v1/supabase
[22:50:21.493] Using NEXT_PUBLIC_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE
[22:50:21.493] Using NEXT_PUBLIC_DEPENDENCY_DISCOVERY_URL=https://dev.api.telescope.cdot.systems/v1/dependency-discovery
[22:50:21.496] warn  - SWC minify release candidate enabled. https://nextjs.org/docs/messages/swc-minify-enabled
[22:50:21.690] info  - using build directory: /vercel/path1/.next
[22:50:21.696] info  - Copying "static build" directory
[22:50:21.701] info  - No "exportPathMap" found in "/vercel/path1/next.config.js". Generating map from "./pages"
[22:50:21.706] info  - Launching 3 workers
[22:50:21.708] info  - Exporting (0/6)
[22:50:21.708] info  - Copying "public" directory
[22:50:22.468] info  - Exporting (1/6)
[22:50:22.582] info  - Exporting (2/6)
[22:50:22.586] info  - Exporting (4/6)
[22:50:23.002] 
[22:50:23.002] Error occurred prerendering page "/dependencies". Read more: https://nextjs.org/docs/messages/prerender-error
[22:50:23.003] Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
[22:50:23.003] Require stack:
[22:50:23.003] - /vercel/path1/node_modules/.pnpm/@mui+private-classnames@5.7.0/node_modules/@mui/private-classnames/node/index.js
[22:50:23.003] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/composeClasses/index.js
[22:50:23.003] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/BadgeUnstyled/BadgeUnstyled.js
[22:50:23.004] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/BadgeUnstyled/index.js
[22:50:23.004] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/index.js
[22:50:23.004] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/IconButton/IconButton.js
[22:50:23.005] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/IconButton/index.js
[22:50:23.005] - /vercel/path1/.next/server/pages/dependencies.js
[22:50:23.005] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/server/require.js
[22:50:23.005] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/server/load-components.js
[22:50:23.006] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/export/worker.js
[22:50:23.010] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/compiled/jest-worker/processChild.js
[22:50:23.010]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[22:50:23.011]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[22:50:23.011]     at Module.require (internal/modules/cjs/loader.js:974:19)
[22:50:23.012]     at require (internal/modules/cjs/helpers.js:101:18)
[22:50:23.012]     at Object.<anonymous> (/vercel/path1/node_modules/.pnpm/@mui+private-classnames@5.7.0/node_modules/@mui/private-classnames/node/index.js:8:30)
[22:50:23.012]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[22:50:23.012]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[22:50:23.012]     at Module.load (internal/modules/cjs/loader.js:950:32)
[22:50:23.012]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[22:50:23.013]     at Module.require (internal/modules/cjs/loader.js:974:19)
[22:50:23.128] 
[22:50:23.129] Error occurred prerendering page "/search". Read more: https://nextjs.org/docs/messages/prerender-error
[22:50:23.129] Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
[22:50:23.129] Require stack:
[22:50:23.129] - /vercel/path1/node_modules/.pnpm/@mui+private-classnames@5.7.0/node_modules/@mui/private-classnames/node/index.js
[22:50:23.131] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/composeClasses/index.js
[22:50:23.131] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/BadgeUnstyled/BadgeUnstyled.js
[22:50:23.131] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/BadgeUnstyled/index.js
[22:50:23.131] - /vercel/path1/node_modules/.pnpm/@mui+base@5.0.0-alpha.80_569957a51d469c962fcce166a59b9f78/node_modules/@mui/base/node/index.js
[22:50:23.131] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/styles/createTheme.js
[22:50:23.132] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/styles/index.js
[22:50:23.132] - /vercel/path1/node_modules/.pnpm/@mui+material@5.7.0_78e61854d81b39da5e9ad4ef04b13775/node_modules/@mui/material/node/index.js
[22:50:23.132] - /vercel/path1/.next/server/pages/search.js
[22:50:23.132] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/server/require.js
[22:50:23.132] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/server/load-components.js
[22:50:23.133] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/export/worker.js
[22:50:23.133] - /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/compiled/jest-worker/processChild.js
[22:50:23.133]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[22:50:23.133]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[22:50:23.139]     at Module.require (internal/modules/cjs/loader.js:974:19)
[22:50:23.139]     at require (internal/modules/cjs/helpers.js:101:18)
[22:50:23.139]     at Object.<anonymous> (/vercel/path1/node_modules/.pnpm/@mui+private-classnames@5.7.0/node_modules/@mui/private-classnames/node/index.js:8:30)
[22:50:23.140]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[22:50:23.141]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[22:50:23.141]     at Module.load (internal/modules/cjs/loader.js:950:32)
[22:50:23.142]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[22:50:23.142]     at Module.require (internal/modules/cjs/loader.js:974:19)
[22:50:23.144] Error: Export encountered errors on following paths:
[22:50:23.144] 	/dependencies
[22:50:23.144] 	/search
[22:50:23.144]     at /vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/export/index.js:398:19
[22:50:23.144]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[22:50:23.144]     at async Span.traceAsyncFn (/vercel/path1/node_modules/.pnpm/next@12.1.6_9b0027aae606c22bf55a7fd89836f009/node_modules/next/dist/trace/trace.js:79:20)
[22:50:23.144] info  - Exporting (6/6)
[22:50:23.149]  ELIFECYCLE  Command failed with exit code 1.
[22:50:23.170] Error: Command "pnpm run build" exited with 1
```

**Review by cindyledev — DISMISSED** [review]
This works on my machine locally

**Comment by humphd** [comment]
Agreed, filed https://github.com/Seneca-CDOT/telescope/issues/3680 on the Vercel failure so we don't block this.

**Comment by Kevan-Y** [comment]
> Agreed, filed https://github.com/Seneca-CDOT/telescope/issues/3680 on the Vercel failure so we don't block this.

If that the case, this PR is good to go

**Review by Kevan-Y — APPROVED** [review]

**Comment by Kevan-Y** [comment]
@mnosov622 Do you mind update your branch, and squash commit?

**Review by manekenpix — APPROVED** [review]

**Pull request merged**
