### PR TITLE
Add e2e test for signup flow in auth + user services

### PR DESCRIPTION
**Pull request by humphd**
We're getting really close to being able to support login + signup in the microservices.  I wanted to get a complete e2e test written that would allow us to see if it's working properly.

This test won't pass yet, since it requires a few more pieces (authenticated routes, #2058, etc).  However, I wanted to get it written before I forgot and while I had time.

### CODE REVIEW

**Comment by humphd** [comment]
This needs a rebase on https://github.com/Seneca-CDOT/telescope/pull/2103

**Comment by humphd** [comment]
Depends on #2116.

**Review by chrispinkney — APPROVED** [review]
Since it won't pass just yet I'm fine re-approaching this after the missing pieces land. The tests themselves seem fine though 😀

**Review by HyperTHD — APPROVED** [review]

**Comment by humphd** [comment]
This is not blocked anymore, I have fixed it.

**Pull request merged**
