### PR TITLE
automate release

### LINKED ISSUE #1301: Add github action to automate the release process.
**What would you like to be added**:
I'd like to add a GitHub action to automate the release process. When there is a release tag like `1.5.0` push to the master branch, a release will be created with the release code and description.

**Why would you like this to be added**:
automate the release process.

### PR DESCRIPTION
**Pull request by yzwdroid**
## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Automate the release process by github action.  To release a new version, we just add a tag when we push or merge a pr. 

- only the commits follow the pattern will be added to the release note.
[https://github.com/lob/generate-changelog#usage](https://github.com/lob/generate-changelog#usage)
```
type(category): description [flags]

Where type is one of the following:

    breaking
    build
    ci
    chore
    docs
    feat
    fix
    other
    perf
    refactor
    revert
    style
    test
```

Screenshot_20201211_234114

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by yzwdroid** [comment]
I didn't update the release document yet, if this is the right method, I will update the document then.

**Comment by birtony** [comment]
This PR should be closed when https://github.com/Seneca-CDOT/telescope/pull/1628 is merged

**Comment by manekenpix** [comment]
Is it needed now? I think we can just close it? @humphd @birtony

**Comment by birtony** [comment]
> Is it needed now? I think we can just close it? @humphd @birtony

I was thinking of waiting until #1628 is merged

**Comment by birtony** [comment]
Addressed in https://github.com/Seneca-CDOT/telescope/pull/1628. Closing.

**Pull request closed without merging**
