### PR TITLE
[Need Logic / Design Help] adds: material UI for search and search button

### LINKED ISSUE #839: Search Bar submit button + onClick()
**What would you like to be added**:
#792 should hopefully go in soon. It doesn't have a search button, but dynamically returns results based on user input. I made it this way currently because I'm unable to prevent the onClick function from triggering non stop after the initial user click

Here's some code snippets that may speed up the process to resolve the issue:

I removed the following code from `SearchBar.jsx`:
line 90
```
        <IconButton
          type="submit"
          className={classes.iconButton}
          aria-label="search"
          onClick={event => handleClick(event)}
        >
          <SearchIcon />
        </IconButton>
```

Code for `SearchPage.jsx`:
```
  function onClickHandler() {
    executeSearch();
  }
```
line 103
```
      <SearchBar
        onClickHandler={onClickHandler}
        searchText={searchText}
        onChangeHandler={onChangeHandler}
      />
```

**Why would you like this to be added**:
Up for debate, should we search upon user input or when the user clicks on button? If this is not a concern, we can close this issue.

### PR DESCRIPTION
**Pull request by raygervais**
## Issue This PR Addresses

Fixes #839 

## Type of Change

- [X] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [X] **UI**: Change which improves UI

## Description

I opted to restyle the UI to leverage more MaterialUI components and semantics, with the overall look still a WIP. Will deff need @agarcia-caicedo help with this one. With that, I've also added the search button which transmits the click to `SearchPage.jsx`.

If we move forward with this design, I need to make it responsive to various view-ports since the `Paper` component doesn't appear to stack. Will replace with `Grid` instead.

There is still some logic issues / updates that are needed, I was hoping @c3ho we could address those together since you are familiar with the components.

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [X] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

image

image

### CODE REVIEW

**Comment by raygervais** [comment]
@cindyledev, trade review for review? :D

**Comment by cindyledev** [comment]
@raygervais definitely! I can't do a thorough review atm but I'll get to it tonight.
First problem that needs to be addressed is the search bar in mobile
Screenshot_20200626-142530_Chrome

**Comment by raygervais** [comment]
Thanks for pointing it out, was trying to hide that issue @cindyledev :P

**Comment by raygervais** [comment]
Going to pick this back up, think I've had a decent break from React / Frontend.

**Pull request closed without merging**
