### PR TITLE
Fixed issue #1682 - rewrote buttons to be clickable on the entire but…

### LINKED ISSUE #1682: Fix onClick reaction area in Next.js MobileHeader
**What happened**: After porting MobileHeader to Next.js, buttons in the side-menu react only when clicked precisely on the text. 

**What should have happened**: They should react when clicked a little bit to the side as well - the onClick area should be increased

**How to reproduce it (as precise as possible)**: Start the Next.js version of the Front-end, open the mobile view, open the side-menu and try clicking not on the text on any of the buttons, but a bit to the side.

**Anything else we need to know?**:

**Environment**:
Have been noticed only in the mobile version, but you might want to check the desktop as well. 
- OS:
- Browser:

### PR DESCRIPTION
**Pull request by izhuravlev**
…ton space

## Issue This PR Addresses

Fixes #1682 

I tried to add a Gif, but ChromeCapture did not work normally in the DevTools window in Chrome.

## Type of Change

- [X] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by izhuravlev** [comment]
I just mentioned that we are focusing on the new UI and this commit is basically useless.

**Review by HyperTHD — APPROVED** [review]
LGTM, just make sure you rebase this before this lands
https://user-images.githubusercontent.com/16841702/107857108-5f1e3980-6dfa-11eb-893d-9c0d455b8b0d.mp4

**Comment by izhuravlev** [comment]
Thank you @HyperTHD for the recording!

**Review by chrispinkney — DISMISSED** [review]
Pulled and ran locally. Awesome, perfect, wonderful, stupendous, LGTM.

**Comment by izhuravlev** [comment]
I will rebase now, as I have 2 Approvals, and merge this PR. 

Thank you @HyperTHD and @chrispinkney!

**Pull request merged**
