### PR TITLE
Create author result component

### LINKED ISSUE #722: Create an Author Result Component
**What would you like to be added**:
A component that shows the author as a result of a search need to be created. It should look like this:

image

The avatar picture does not need to be implemented at this time.
The last post should be a link the last post the author made.
The more>  will currently not connect to anything

Assets: 
Font: Roboto
icon colour: #3670A5
font color: #002944
Text section background colour: #9E9E9E
Avatar section background color: #444444

**Why would you like this to be added**:
This is part to implement the search functionality

### PR DESCRIPTION
**Pull request by c3ho**
## Issue This PR Addresses
Fixes #722

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

WiP, but would like some feed back. Will fine tune other things so the avatar image will actually stay within the box. The expansion panel I don't know if I want to place it in the second column at the very bottom or to create a third column within the grid and just somehow move it to the very bottom.

image

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
I have a few questions, but I guess the most important one: what font size should we use?

**Comment by cindyledev** [comment]
I played around with your component and it seems my previous suggestion for the expansion panel sucked (I couldn't get it to work either, sorry for wasting your time). I tried using List https://codesandbox.io/s/material-demo-5d6rs and it looks like it works better. I don't know what I did but now the `More >` is always starts as opened instead of closed

**Comment by c3ho** [comment]
@cindyledev How does this look [now](https://codesandbox.io/s/material-demo-wffi6)? 
Two worries:
1. the white space below the avatar in the image container when you expand
2. not enough space for information such as latest post, date

**Comment by cindyledev** [comment]
I like how close this is getting and I think this is good enough for 0.7, the CSS issue can be filed and fixed in another issue (unless you wanna keep working on CSS...) I'd rather get this connected to the backend asap :)

**Pull request merged**
