### PR TITLE
[CI/CD] Fixes #1638: Configured npm version to run tests and push to upstream master

### LINKED ISSUE #1638: Configure npm-version to run tests
**What would you like to be added**:
We should configure [`npm-version`](https://docs.npmjs.com/cli/v6/commands/npm-version) to run tests before proceeding with bumping the version in `package.json` and creating a release tag. It should looks somewhat like:
```json
"scripts": {
    "preversion": "npm test",
    "version": "npm run build && git add -A dist",
    "postversion": "git push && git push --tags && rm -rf build/temp"
}
```
**Why would you like this to be added**:
This would allow us to make sure we release working code.

### PR DESCRIPTION
**Pull request by birtony**
## Issue This PR Addresses
Fixes #1638 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
This PR configures `npm version` to run prettier, eslint and tests locally. If successful, it will bump the version in `package.json` and commit. Finally, it will create a release tag and push both code and tags to `upstream master`. All that's needed to create a release is to run `npm version <new-version> -m "Release description"`. For more details, see [`npm version` docs](https://docs.npmjs.com/cli/v6/commands/npm-version).

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by PedroFonsecaDEV — APPROVED** [review]
LGTM

**Comment by Metropass** [comment]
Looks good on my end as well! Great job!

**Review by Metropass — APPROVED** [review]

**Review by humphd — APPROVED** [review]
Do we have an issue filed on updating our Release docs to indicate how to use this?  If not, can you file that before we merge?

**Comment by birtony** [comment]
> Do we have an issue filed on updating our Release docs to indicate how to use this? If not, can you file that before we merge?

We already have https://github.com/Seneca-CDOT/telescope/issues/1632 filed for it @humphd

**Pull request merged**
