### PR TITLE
Fixes 817 added Footer to DesktopHeader and MobileHeader

### LINKED ISSUE #817: Footer Improvements
Did you know we have a footer? I sure didn't. We have one line in `Layout.js` (line 72) that says:
```
 <footer>© {new Date().getFullYear()}</footer>
```
You'd have to scroll _all_ the way down to the bottom of the main page to see it. Let's find a better place for it so we can actually see it. Location is up to you. Use MUI if you can.

We should add to it as well. `Copyright © 2020 Seneca’s Centre for Development of Open Technology` looks more complete than just `© 2020`.

### PR DESCRIPTION
**Pull request by cindyledev**
## Issue This PR Addresses
Fixes #817 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Initially meant to put this Footer underneath all the blog posts but I notice that after we hit the last blog post, it actually continues to load more blog posts so it doesn't make sense to put the footer there. This adds Footers to the bottom of the side drawer for both the DesktopHeader and MobileHeader.

Annotation 2020-04-08 194402

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by humphd** [comment]
Merge conflict here, let's fix that before we review.

**Comment by agarcia-caicedo** [comment]
Do we want a link for the CDOT website on the footer?

**Comment by agarcia-caicedo** [comment]
Code wise I think it's fine, however because of #965, where would we put the footer when the drawer is removed?

**Comment by cindyledev** [comment]
> Do we want a link for the CDOT website on the footer?

Oh this is a good idea!

**Comment by cindyledev** [comment]
> Code wise I think it's fine, however because of #962, where would we put the footer when the drawer is removed?

Thinking ahead, we should keep the drawer because after I finish #290 , I wanna add another tab that says DOCS underneath ABOUT. But #290 will probably done in May... 

This is up for discussion. Do we wanna remove the drawer for a month and reintroduce it after? Or just keep it? There are plenty of new pages we can add in the future

**Comment by cindyledev** [comment]
added link to Seneca CDOT website :)

**Pull request merged**
