### PR TITLE
Fixed double dash typo.

### PR DESCRIPTION
**Pull request by JackyTea**
Fix issue #626

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
@JackyTea I should've merged this before merging another PR, do you mind rebasing? Once  that's done I'll merge.

**Comment by c3ho** [comment]
@JackyTea I think you accidentally pulled into your issue branch

1. `git checkout master` we only want to pull to master
1. `git pull upstream master` 
1. `git checkout `JackyTea:patch-1` to go to your issue branch
1. `git rebase master` to rebase your issue branch, otherwise you'll be trying to merge stuff since your last commit with your current PR which we want to avoid.

**Comment by humphd** [comment]
@JackyTea if you can't get this to work, I'm happy to do it tomorrow for you.  Really glad to have you working on Telescope, it's great to have you join us.

**Comment by JackyTea** [comment]
Sorry I rebased on my `patch-1` branch instead of `master`.

**Comment by humphd** [comment]
@JackyTea if you want to hack on more Telescope issues with us, we're happy to mentor you.

**Comment by JackyTea** [comment]
@humphd Would love to get more into Telescope, would appreciate the mentoring greatly. Thank you.

**Comment by humphd** [comment]
@JackyTea what are you more interested in, front-end React stuff, or back-end work in node.js, Redis, express.js, etc?

**Comment by JackyTea** [comment]
@humphd I am more interested in the front-end side of React. I have worked with Node.JS along with Express.js to build RESTful APIs but front-end is preferred.

**Comment by humphd** [comment]
@JackyTea what about https://github.com/Seneca-CDOT/telescope/issues/881?

This will give you some experience working with our frontend, getting it running locally, etc.  We can chat about it more in Slack, and/or you can ask questions in the issue.

**Pull request merged**
