### PR TITLE
Fix issue-1424 : Fix colours in GitHub Contributor component

### LINKED ISSUE #1424: Fix font colours in GitHub Contributor component
The new GitHub Contributor component we added to the Footer of the About page is using the wrong font colour for the main text (should be the same "white" as the rest of the footer).

Screen Shot 2020-11-19 at 6 43 44 PM

### PR DESCRIPTION
**Pull request by tianlangwu**
## Issue This PR Addresses
Fix #1424 

## Type of Change

- [X] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
Fixed font colours in GitHub Contributor component. Replaced the colour to the same "white" as the rest of the footer.
Removed unnecessary import and variable.
Fixed a linter error.
Thanks for your consideration!

## Checklist

- [X] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by PedroFonsecaDEV — APPROVED** [review]
LGTM

**Comment by PedroFonsecaDEV** [comment]
Just some considerations:
1. Don't forget to self-assign to issue (so we know who is working on what and so on)
2. Please edit the title of the PR for our pattern (Fixes issue-0000: title of the issue)
***
Please rebase this brach.

**Comment by tianlangwu** [comment]
> Just some considerations:
> 
> 1. Don't forget to self-assign to issue (so we know who is working on what and so on)
> 2. Please edit the title of the PR for our pattern (Fixes issue-0000: title of the issue)
> 
> Please rebase this brach.

Thanks for the advice, I will rebase it later.

**Review by PedroFonsecaDEV — DISMISSED** [review]

**Review by agarcia-caicedo — APPROVED** [review]

**Review by humphd — COMMENTED** [review]
I don't understand why we're using dark-on-dark here for the plain text, it's so dark:

Screen Shot 2020-11-21 at 9 42 50 AM

Question: the whole footer is white, so why not use white everywhere here, and just provide underlines for the anchors?

**Comment by tianlangwu** [comment]
> I don't understand why we're using dark-on-dark here for the plain text, it's so dark:
> 
> Screen Shot 2020-11-21 at 9 42 50 AM
> 
> Question: the whole footer is white, so why not use white everywhere here, and just provide underlines for the anchors?

Agree, I will change the text colour to white.

**Review by humphd — APPROVED** [review]

**Review by PedroFonsecaDEV — APPROVED** [review]

**Pull request merged**
