### PR TITLE
Port SearchInput to NextJS

### LINKED ISSUE #1500: [next] Port SearchInput/ to NextJS
https://github.com/Seneca-CDOT/telescope/tree/master/src/frontend/gatsby/src/components/SearchInput
**What would you like to be added**:
Port all components in SearchInput/ to NextJS using TS
**Why would you like this to be added**:
Porting reason

### PR DESCRIPTION
**Pull request by HenryZerocool**
## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI
- [x] **Next**: Porting to NextJS

## Description

Ported SearchInput to NextJS

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
Did you happen to pull master into your working branch?

**Comment by HenryZerocool** [comment]
Yes I did,
I'm sorry, was that a mistake?

**Comment by c3ho** [comment]
Yeah, you should be rebasing into your working branch with git rebase master. If you check your files changed we have no idea what you did because a lot of other contributors’ code are mixed in as well

**Comment by HenryZerocool** [comment]
Please refer to this PR #1518 
I tried git rebase but it doesn't work anymore.

**Pull request closed without merging**
