### PR TITLE
Added margin after Search bar

### PR DESCRIPTION
**Pull request by strawberries73**
## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
image

Did you pull directly into your issue branch?

**Comment by strawberries73** [comment]
@c3ho I guess I did not.  I made a mistake in my steps.  This time I pull from my issue Branch and was able to fix the conflict properly but now it won't let me push to branch.  I am getting an error that says "the tip of my current Branch is behind.  Is there a way to fix this or do you recommend I create  a new branch and start over.

**Comment by c3ho** [comment]
`git push <branch> origin -f`

**Comment by humphd** [comment]
This is adding 10 million lines of code, which I think is due to node_modules being included, which we don't want.  @strawberries73 do you want to try this again in a anew PR?  Let us know if you have trouble doing a rebase.  It would look something like this:

```
git checkout master
git pull upstream master
git checkout <your-branch>
git rebase master
git push origin <your-branch> -f
```

The `-f` is needed on the final `push` because the history will have changed.

I'm going to close this one for now, and we'll follow up in the next one you create.

**Comment by strawberries73** [comment]
@humphd and @c3ho Yes I would like to do this in a new PR.  Thank you!

**Pull request closed without merging**
