### PR TITLE
Add CONTRIBUTING.md

### LINKED ISSUE #27: Add a CONTRIBUTING.md file for environment setup and tracking
Most projects that I found throughout Hacktoberfest had some sort of documentation that helped developers to set up their environment faster. As we add code to the project, we should have a centralized place to contain everything we need to get working on the project. It could also be used to track the progress of the project (what people are working on and where to look), according to the [MVP Features](https://github.com/Seneca-CDOT/telescope/blob/master/docs/overview.md#mvp-features).

As pull requests are merged, someone should be tracking and updating the CONTRIBUTING.md as needed. It could be a specific person, or a requirement that each pull request must update the CONTRIBUTING.md file if needed. This could also be tracked or linked to in the README or the overview.md doc as well.

A good start would be adding the Redis requirements and setup from #24 .

### PR DESCRIPTION
**Pull request by drwm-base**
Fixes #27 .

This is clearly a work in progress. I will be working on finding better setup instructions, but for now this will work. I would really like feedback on how to approach issues and pull requests from the community, but what I have mirrors what I saw in other projects.

If there is anything I could add, or information I could use, please let me know. I would like to use docker, as that would simplify things greatly, and I know someone is working on it right now. I will update this as pull requests are merged and the system evolves.

### CODE REVIEW

**Comment by humphd** [comment]
Great work.  I'll let others review this.  I don't want to block all reviews on me, personally.  It would be better if we distributed the review load across the community.

**Comment by ImmutableBox** [comment]
@aprilllllllll Doesn't look like you have write access. @humphd Can you give @aprilllllllll access to merge this pull request?

**Comment by humphd** [comment]
@aprilllllllll have you accepted the invitation to become a collaborator?  I sent it via GitHub.

**Comment by aprilllllllll** [comment]
@humphd Yes I have accepted the invitation. Can I merge this PR now?

**Comment by humphd** [comment]
@aprilllllllll for sure, do it.

**Pull request merged**
