### PR TITLE
Fixes #2583 Title container overflow fixed

### LINKED ISSUE #2583: Title container floating with some space, and overflow with the scroll on mobile view.
While working on issue #2373, found out that the title container is floating and overflowing when scrolling through the content. 

https://user-images.githubusercontent.com/54859944/145267660-f8ad73fb-d6ee-4604-b781-08385c3edbb1.mov

**What happened**: 
The title container is stuck on the top, but floating with a small space so that the background content is slightly showing on top of the container.

**What should have happened**: 
It should enclose the top space without any gap.

**Environment**: 

Bug on UI - mobile 

- OS: N/A
- Browser: In all browser

### PR DESCRIPTION
**Pull request by irenejoeunpark**
## Issue This PR Addresses

Fixes #2583

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Setted overflowY as hidden to avoid title container overflow. 

https://user-images.githubusercontent.com/54859944/146446051-ce6f61c1-3b5e-4d64-91cb-2bc1c492bbf5.mp4

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by DukeManh — APPROVED** [review]
@irenejoeunpark is this linked with #2583?

**Review by ritikbheda — APPROVED** [review]

**Comment by irenejoeunpark** [comment]
> @irenejoeunpark is this linked with #2583?

I added the linked issue! Thanks

**Review by dbelokon — APPROVED** [review]

**Comment by AmasiaNalbandian** [comment]
@irenejoeunpark Can we rebase this so it's ready for merge? :)

**Comment by irenejoeunpark** [comment]
> @irenejoeunpark Can we rebase this so it's ready for merge? :)

I have fixed all of the conflicts caused while rebasing, however I am getting error with the pnpm commands which blocks me to commit. I know it is not a good practice, but can I fix the conflicts by editing in github for this one?

**Comment by DukeManh** [comment]
@irenejoeunpark, fixing conflicts here would merge master in your branch, which is not what we want. If u have problems with your local environment, I'd recommend taking a look at our Gitpod docs and continue your work on there.

**Comment by AmasiaNalbandian** [comment]
> @irenejoeunpark, fixing conflicts here would merge master in your branch, which is not what we want. If u have problems with your local environment, I'd recommend taking a look at our Gitpod docs and continue your work on there.

Thanks Duke! @irenejoeunpark It seems easier but it really does make it messier. I will be around if you need help with this :)

**Pull request closed without merging**
