### PR TITLE
Add kibana to Telescope

### PR DESCRIPTION
**Pull request by c3ho**
## Issue This PR Addresses
Part of #1269

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
I was thinking of Kibana ever since we added ElasticSearch, great to finally have it added. I had to also update our ElasticSearch image to 7.9.3 so it is compatible with the current version of Kibana.

To test:

1. make sure the extra lines from `env.example` are copied into your `.env` file
2. `docker-compose up redis elasticsearch kibana`
3. navigate to `http://localhost:5601`

You should see something like this afterwards

image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
image
This is kind of overwhelming

**Review by humphd — APPROVED** [review]
Do we want the `telescope` service to depend on this?  Probably not?

Also, does `kibana` need any info about the Elasticsearch server (port we are using?)

**Comment by raygervais** [comment]
Will review tonight, remind me if I don't get to it @c3ho. 
To answer, I'm fairly certain `kibana` needs to be aware of `elasticsearch` @humphd

**Comment by c3ho** [comment]
@humphd the image has presets using http://elastic search:9200

I personally don’t think telescope should be dependent on kibana yet until we add the front-end things

**Comment by humphd** [comment]
It might have a preset of 9200, but if the user changes it in their `.env` this will break.  We should add some kind of `environment` here to pass the elastic port in as well.

**Comment by manekenpix** [comment]
I have 2 questions:
- How is this going to work in production? (if we want it in prod at all).
- Did you check that nothing broke after changing the image version? I remember when I was working on it that I saw a lot of complaints online about the lack of compatibility between different ES image versions.

**Comment by c3ho** [comment]
@manekenpix I had to run telescope again for the PR, because with the Kibana change, ES had no data on posts. I checked afterwards and Kibana had data on the `post` index, also checked `http://localhost:9200/_cat/indices?v` to see if posts were properly being index. I don't think it is breaking anything yet.

**Review by humphd — APPROVED** [review]

**Review by raygervais — APPROVED** [review]

**Review by manekenpix — APPROVED** [review]

**Pull request merged**
