### PR TITLE
Revert "Removed ioredis/ioredis-mock, added Redis from Satellite inst…

### PR DESCRIPTION
**Pull request by TDDR**
head (#2615)"

This reverts commit 0ddaa159b9e6616951a6cc3fbbb1dd964f6f5535.

Need to revert because this merge caused this issue 
image

### CODE REVIEW

**Review by humphd — APPROVED** [review]
@TueeNguyen you can try this again later with more testing.

**Review by DukeManh — APPROVED** [review]
🚑

**Comment by TueeNguyen** [comment]
I'm checking the code atm

**Comment by humphd** [comment]
@TueeNguyen file a new issue/pr for that, we'll revert here and follow up later.

**Pull request merged**
