### PR TITLE
Fix#122: add error catch when the Redis is not installed

### PR DESCRIPTION
**Pull request by aprilllllllll**
Hi, I update the code and made an error catch when the Redis is not installed.

### CODE REVIEW

**Comment by aprilllllllll** [comment]
Ok.I am working on it now

**Comment by humphd** [comment]
@aprilllllllll I really want to get this landed.  Can we look at it together in the lab on Thursday so we can get this closed?

**Comment by humphd** [comment]
Tried this out tonight, both with Redis running and without.  When Redis isn't running, I see this:

```
Telescope listening on port 3000
Enqueuing Job - https://neilong31.wordpress.com/feed/
Enqueuing Job - http://ajhooper.blogspot.com/feeds/posts/default
Enqueuing Job - http://ljubomirgorscak.blogspot.com/feeds/posts/default
Enqueuing Job - http://nashutzu.blogspot.com/feeds/posts/default
Enqueuing Job - http://nadavid.blogspot.com/feeds/posts/default
Enqueuing Job - http://gkrilov.blogspot.com/feeds/posts/default
Enqueuing Job - http://KrazyDre.blogspot.com/feeds/posts/default?alt=rss
Enqueuing Job - http://dcucereavii.blogspot.com/feeds/posts/default?alt=rss
Cannot connect https://neilong31.wordpress.com/feed/ Please make sure the Redis is install
Cannot connect http://ajhooper.blogspot.com/feeds/posts/default Please make sure the Redis is install
Cannot connect http://ljubomirgorscak.blogspot.com/feeds/posts/default Please make sure the Redis is install
Cannot connect http://nashutzu.blogspot.com/feeds/posts/default Please make sure the Redis is install
Cannot connect http://nadavid.blogspot.com/feeds/posts/default Please make sure the Redis is install
Cannot connect http://gkrilov.blogspot.com/feeds/posts/default Please make sure the Redis is install
Cannot connect http://KrazyDre.blogspot.com/feeds/posts/default?alt=rss Please make sure the Redis is install
Cannot connect http://dcucereavii.blogspot.com/feeds/posts/default?alt=rss Please make sure the Redis is install
UNHANDLED REJECTION:  Shutting down...
Error connect ECONNREFUSED 127.0.0.1:6379
```

So it's sort of working, in that it reports the error after each failed connection attempt when trying to add a feed.  But it still dies in an unhandled Promise rejection, but doesn't really report the right thing.

I think we should combine this with what is happening in #217 and do something like we have in https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/server.js#L11-L17, where we listen for unhandled rejections, and then you could add a check to look for `ECONNREFUSED` to report this error.

**Comment by humphd** [comment]
@aprilllllllll this seems to have stalled.  Should we close it, or are you planning to finish it?

**Comment by aprilllllllll** [comment]
> @aprilllllllll this seems to have stalled. Should we close it, or are you planning to finish it?

I think to close it and I will make a new PR which put my code in the shutdown function

**Pull request closed without merging**
