### PR TITLE
set trust for first proxy when env is prod

### LINKED ISSUE #3792: Trusting the proxy
**What would you like to be added**:

We could try to add trust for proxy in case this makes a difference with the session cookie.secure set to true since we are using nginx.
```
var app = express()
app.set('trust proxy', 1) // trust first proxy
app.use(session({
...
```

**Why would you like this to be added**:

In the [express-session](https://www.npmjs.com/package/express-session) docs they claim this trust should be set if cookie.secure is set to true. This is a part of an ongoing effort to get cookies to send within the post binding part of the Azure AD authentication which I broke with #3789. Could be contributing/considered along with the latest issue #3791.

### PR DESCRIPTION
**Pull request by sfrunza13**
## Issue This PR Addresses
Fixes #3792 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
I am trying to find a way to make the new cookie settings work, perhaps this might be a step in the right direction.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally (but it only changes anything in prod so idk if this means anything)
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — CHANGES_REQUESTED** [review]
From the [docs](https://expressjs.com/en/guide/behind-proxies.html):

> Number: use the address that is at most n number of hops away from the Express application. req.socket.remoteAddress is the first hop, and the rest are looked for in the X-Forwarded-For header from right to left. A value of 0 means that the first untrusted address would be req.socket.remoteAddress, i.e. there is no reverse proxy.When using this setting, it is important to ensure there are not multiple, different-length paths to the Express application such that the client can be less than the configured number of hops away, otherwise it may be possible for the client to provide any value.

We are behind 2 proxies:

1. nginx
2. traefik

I wonder if this should be 2?  I'm not sure.

**Comment by sfrunza13** [comment]
I suppose you're right, it should probably be 2

**Review by humphd — APPROVED** [review]
I think this is good.  @manekenpix, do you have any concerns?

**Comment by manekenpix** [comment]
> I think this is good. @manekenpix, do you have any concerns?

@humphd LGTM :+1:

**Comment by sfrunza13** [comment]
Can I squash and merge?

**Comment by manekenpix** [comment]
@sfrunza13 I think this is good to go.

**Comment by humphd** [comment]
@sfrunza13 yeah, go for it

**Pull request merged**
