### PR TITLE
Use Docusaurus tabs for each OS in environment-setup

### LINKED ISSUE #2882: Environment Setup doc should have tabs to separate instructions by operating systems
Our [environment-setup.md](https://github.com/Seneca-CDOT/telescope/blob/master/src/docs/docs/getting-started/environment-setup.md) has a table of content at the top, this is no longer required because Docusaurus outputs the headings on the right and it acts as a table of content.

Screenshot 2022-02-11 132710

We can also use Docusaurus' [Tabs](https://docusaurus.io/docs/markdown-features/tabs#syncing-tab-choices) to separate set up instructions by operating systems

2022-02-11 13_31_53-Tabs _ Docusaurus - Brave

### PR DESCRIPTION
**Pull request by menghif**
## Issue This PR Addresses
Fixes #2882 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This PR updates the environment-setup doc to separate install instructions by operating systems.

Screen Shot 2022-02-11 at 4 32 38 PM

It also removes the table of content at the top.

## Steps to test the PR

Change directory to /src/docs: `cd src/docs`
Start the server: `pnpm start`
Visit [localhost:4631](http://localhost:4631/) in your browser

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by cindyledev — APPROVED** [review]
This is fantastic! Thank you

Tested locally and it works as expected
Screenshot 2022-02-11 164753

I'm convinced to get a Mac because it's literally 1 step to get Docker set up

**Comment by cindyledev** [comment]
I see you splashed a bit of Admonition at the bottom too. Nice chef's kiss

**Comment by joelazwar** [comment]
tested locally, looks great!

**Review by joelazwar — APPROVED** [review]

**Review by TueeNguyen — APPROVED** [review]
This looks nice, thank you

**Pull request merged**
