### PR TITLE
Update DynamicImage

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
No open issue. 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
As we move towards 2.0, in order to achieve best results for our UI this PR will upgrade our `<DynamicImage>`.

Right now `<DynamicImage>` is only used on our old landing page, but in order to use it properly in other pages or components I made some upgrades, now `<DynamicImage>` accepts some args.

 filter?: boolean;
  color?:string;
  ~~backgroundMode?: boolean;~~

`<DynamicImage filter>` will render the DynamicImage that we use now the filter will use the theme color.
~~`<DynamicImage backgroundMode>` will render the DynamicImage without a filter and it will set the `Zindex:-1` so we can use the image for backgrounds easier.~~
`<DynamicImage filter color="<string>">` will render the DynamicImage with the filter set to the color that you are passing as a string, it can be something like `'yellow'` or a color HEX value.

You can combine the arguments like `<DynamicImage filter color="blue">`

To test you can pull the PR and create a page and play with the `<DynamicImage>`

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by PedroFonsecaDEV** [comment]
@humphd  I'm having this error and I don't know how to solve it:
```
Failed to compile.
06:16:59.177 | ./src/components/DynamicImage.tsx:48:23
06:16:59.177 | Type error: Property 'isBackground' does not exist on type '{}'.
06:16:59.177 | 46 \|     objectFit: 'cover',
06:16:59.177 | 47 \|     zIndex: (stylesProps) => {
06:16:59.177 | > 48 \|       if (stylesProps.isBackground) return stylesProps.zIndex;
06:16:59.178 | \|                       ^
06:16:59.178 | 49 \|       return { zIndex: 0 };
06:16:59.178 | 50 \|     },
06:16:59.178 | 51 \|   },
06:16:59.196
```

`Type error: Property 'isBackground' does not exist on type '{}'.`

Could you please give me a hand on that matter?

**Comment by humphd** [comment]
@PedroFonsecaDEV I think your issues is that you're not defining a type on your props when you do this style:

```js
(stylesProps) => {...}
```

You want something like:

```ts
(props: stylesProps) => {...}
```

Also, are types not supposed to start with a capital?  `StylesProps`?

**Comment by HyperTHD** [comment]
> @PedroFonsecaDEV I think your issues is that you're not defining a type on your props when you do this style:
> 
> ```js
> (stylesProps) => {...}
> ```
> 
> You want something like:
> 
> ```ts
> (props: stylesProps) => {...}
> ```
> 
> Also, are types not supposed to start with a capital? `StylesProps`?

It's purely convention. How you define the types don't matter as long as they function properly. The first letter being capital in a type/interface declaration is generally the norm

**Comment by humphd** [comment]
@PedroFonsecaDEV I took a quick look at this, and I'm not sure what you're trying to accomplish exactly, so I can't advise on the best course of action.  Can you tell me more about your goal here?

**Comment by birtony** [comment]
@PedroFonsecaDEV we have looked into this PR during the triage meeting and were not sure what are the expectations from this PR. Could you take a look at it to fix the deployment error and elaborate, please?

**Comment by PedroFonsecaDEV** [comment]
@humphd, this needs to be tested. 

When I tested it on my machine with `npm run dev`, it doesn’t work, the MUI doesn’t work at the first build, but after you force a re-render (toggling the theme), sometimes it works. I was giving up when I notice that It seems to be working when Vercel builds it on our CI/CD.

So I don't know what we are facing here. In dev mode, it seems to have a sync problem between React and MUI. 
I think the best solution, for now, is to close the PR. Otherwise, we would create a front-end that doesn’t work properly in dev mode.

**Comment by PedroFonsecaDEV** [comment]
Closing.
This PR is not a good alternative. We can go back to this in the future if we need it because right now, it's not necessarily.

**Pull request closed without merging**
