### PR TITLE
Issue 1225 Reposition search button for search UI

### LINKED ISSUE #1225: Reposition search button for search UI
Our frontend kicks off searches every time you start typing.  I'd love to see us:

- add a button so it doesn't happen until I click or press 'enter'
- and/or debounce this keyboard event so it doesn't start happening until I finish typing

If you type something like, it will fire and re-fire the query on every letter.  That's bad UI, and it overloads the network and React.

### PR DESCRIPTION
**Pull request by strawberries73**
## Issue This PR Addresses
Fixes #1225 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Repositioned Icon Button

image

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
Seems like you merged other PRs into your issue branch

**Comment by strawberries73** [comment]
@c3ho  I'm not sure how that happened.  

image

**Comment by c3ho** [comment]
Are the actual changes in your second commit?

**Comment by c3ho** [comment]
Ok, here's what you can do:

On master branch do a git pull on it, so you can update master with all the latest changes.

1. `git checkout -b issue-1225-fix` Or something like that, doesn't matter
2. `git cherry-pick 00618c853178812a4319675533c19d826c5e730a` <--- this is your fix without all your merges
3. at this point you could rename your old branch to another name and rename issue-1225-fix to the old name, so you can keep this PR and not have to open another one.
4. `git push origin <old-branch-name>`

**Comment by c3ho** [comment]
Check for conflicts in your file

**Pull request closed without merging**
