### PR TITLE
Fixes #2746 Create the Docs microservice

### LINKED ISSUE #2746: Create the Docs Microservice
**What is the idea?**
We started loving docs again and will be spawning a great number of new docs:
- #2733 Documentation for React Native
- #2734 Documentation for Supabase
- #2737 Documentation for Turborepo
- #203 Documentation for REST API
and more to come...

We can create a microservice for our docs and containerize the web application where our docs will live. Such an idea has been brewing since 2019 #290 

**How would it look like? (if applicable)**
We kind of started working on this for Telescope 2.0, so we have some sort of MDX implementation (for the About Us page). Let us move the MDX stuff into its own microservice since it's not really related to the main Telescope app. This microservice will live in /src/api/docs so when we visit https://telescope.cdot.systems/docs, we can easily find whatever document we need instead of going to the [/docs](https://github.com/Seneca-CDOT/telescope/tree/master/docs) directory in the Telescope repo

**What existing technologies need to be used? (if applicable)**
I want to try this stack to build this web app.
- Next.js
- MDX
- TailwindCSS

**What areas will have to be worked on? (issue labels of type `area`) Describe which, how, and why.**
- Documentation
- Developer Experience
- User Experience

**What does the idea solve?**
Documentation for our documentation because who is enjoying Telescope's bowl of spaghetti docs?

We can have docs for developers. Docs for users. Docs for Windows, Docs for Mac. Docs for Linux... Docs for everyone. While this may seem like a 'nice-to-have' feature, it should really be 'fun-to-have' because it will be FUN. F-U-N. Fun. Just to further prove how fun this can be, I'm willing to help get this started (once the team has approved this proposal), and whoever wants to jump in can jump in. I'm also okay with munching on this solo if no one else shows interest since I don't see this blocking anything in progress.

### PR DESCRIPTION
**Pull request by cindyledev**
## Issue This PR Addresses

#2746 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

How to review this PR locally the old-school way. Gitpod might work but I haven't tried it yet.

1. Add my repository as a remote: `git remote add cindyledev https://github.com/cindyledev/telescope.git`
2. Fetch my branches: `git fetch cindyledev`
3. Checkout my branch: `git checkout docs-microservice`
4. Install dependencies: `pnpm install`
5. Start the Docker containers: `pnpm services:start`

This is the first time I'm creating a microservice so I'm having some trouble with how either Traefik is stripping the URL or perhaps something to do with the Next.js side?

Visiting `localhost:4631` takes you to the Next.js app running in the Docker container as expected
Screenshot 2022-01-29 144335

However, when you visit the API route `localhost/v1/docs`, you get an 202 OK response which is also good
Screenshot 2022-01-29 144208

but it thinks the Next.js files are at `localhost/_next/*`, I want it route to `localhost/v1/docs/_next/*`

Screenshot 2022-01-29 144314

If you manually go to `http://localhost/v1/docs/favicon.ico`

Screenshot 2022-01-29 144434

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by manekenpix** [comment]
This is nice :+1: 
How are we going to display the docs? Will we have templates that will load content fetched from the telescope repo? or are we going to have the actual docs living inside of the microservice (inside of a folder).

**Comment by humphd** [comment]
If our goal is a docs web site, should we use a docs-website base instead (e.g., Docusaurus)?  We just did a big rewrite of the docs for the C notes, see https://github.com/Seneca-ICTOER/Intro2C, and it was nice not to have to worry about a lot of stuff we'd have to do manually here with next.js.

Just a thought, it doesn't have to be this.

**Comment by cindyledev** [comment]
I'm gonna dig into Docusaurus again since this microservice Next.js approach is taking a long time to get to market because we're building from the ground up and I can already see all the technical debt in its wake sorry LOL

**Comment by cindyledev** [comment]
Scrapping this approach

**Pull request closed without merging**
