### PR TITLE
Fixes #2755: Update ElasticSearch URL 

### LINKED ISSUE #2755: [Satellite] Cannot set property statusCode of Error which has only a getter
While I was testing #2753, I ran into a crash in our error handling code:

```
TypeError: Cannot set property statusCode of Error which has only a getter
    at createError (/app/node_modules/http-errors/index.js:101:33)
    at /app/src/routes/query.js:13:10
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
  error: ResponseError: index_not_found_exception
      at onBody (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:337:23)
      at IncomingMessage.onEnd (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:264:11)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    meta: {
      body: [Object],
      statusCode: 404,
      headers: [Object],
      meta: [Object]
    }
  }
} query error
/app/node_modules/http-errors/index.js:101
    err.status = err.statusCode = status
```

This is being caused by the following code in the search servce:

```js
// search.js

const search = async (
  textToSearch,
  filter = 'post',
  page = 0,
  perPage = ELASTIC_MAX_RESULTS_PER_PAGE
) => {
  ...
  const {
    body: { hits },
  } = await client.search({
    from: calculateFrom(page, perPage),
    size: perPage,
    _source: ['id'],
    index,
    type,
    body: query,
  });

  return {
    results: hits.total.value,
    values: hits.hits.map(({ _id }) => ({ id: _id, url: `${POSTS_URL}/${_id}` })),
  };
};

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// query.js
router.get('/', validateQuery, async (req, res, next) => {
  try {
    const { text, filter, page, perPage } = req.query;
    res.send(await search(text, filter, page, perPage));
  } catch (error) {
    console.log({ error }, 'query error');
    next(createError(503, error));   // <-- crash is here
  }
});

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// http-errors/index.js

  if (!HttpError || !(err instanceof HttpError) || err.status !== status) {
    // add properties to generic error
    err.expose = status < 500
    err.status = err.statusCode = status
  }
```

So what's happening here is that we do a call to Elasticsearch, and because there is no index built yet (I hadn't started the parser), it fails (Promise rejects).  This takes us to the `catch` block in the router, and we try to `createError()` using `503` and the `err` object.  This calls into this code (not ours): https://github.com/jshttp/http-errors/blob/master/index.js#L42-L105.  It is trying to decorate the error with a status code property, but it fails:

```
TypeError: Cannot set property statusCode of Error which has only a getter
    at createError (/app/node_modules/http-errors/index.js:101:33)
    at /app/src/routes/query.js:13:10
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
{
  error: ResponseError: index_not_found_exception
      at onBody (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:337:23)
      at IncomingMessage.onEnd (/app/node_modules/@elastic/elasticsearch/lib/Transport.js:264:11)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    meta: {
      body: [Object],
      statusCode: 404,
      headers: [Object],
      meta: [Object]
    }
  }
}
```

This causes the server to crash.  This same problem will affect *all* of our microservices.

We should add a test to Satellite [here](https://github.com/Seneca-CDOT/satellite/blob/d5c35e071eb3f858e1e484152d4443af86ddbeb8/test.js#L894) that tries to pass an `Error` object vs. a `string` as the second arg, and figure out whose bug this is: ours, elasticsearch's, or http-errors.

### PR DESCRIPTION
**Pull request by AmasiaNalbandian**
## Issue This PR Addresses
fixes #2755 

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
When we started to use Satellite to create ElasticSearch client, I believe we no longer have the address for 127.0.0.1. We need to fetch it using localhost:9200.

## Steps to test the PR
to reproduce the ERROR: 
`cp config/env.development .env`
`docker-compose --env-file ./config/env.development up --build search elasticsearch redis posts nginx planet`
`pnpm start`
then go to `http://localhost:4445/advanced/?post=Amasia%20Nalbandian&filter=author`
in docker container for search you will see the error reported...

after the fix, you should see no errors.

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by AmasiaNalbandian** [comment]
I can't reproduce the issue on my end right now, but I am certain this fixed it earlier this week.

**Review by humphd — COMMENTED** [review]
I don't understand this change

**Comment by cindyledev** [comment]
I remember I had a conversation with @manekenpix asking if there was a difference between `localhost` and `127.0.0.1` on Slack but chat history does not persist on there so I don't remember the details. But I do remember I kept hitting `ECONNREFUSED 127.0.0.1:6379` for some reason. I know this isn't very helpful. Sorry

**Comment by rclee91** [comment]
The crash found in #2755 is twofold. 
1. It is crashing from trying to create an Error from an ElasticSearch Error
2. The ElasticSearch Error was created from it sometimes not being able to recognize the `127.0.0.1` url, which is what is currently set in `env.development`

**Comment by AmasiaNalbandian** [comment]
I'm not too confident this makes sense, but we ripped out the `elastic.js` from Telescope (when we added the tests for elasticsearch) and it looks like we are now using Satellite to connect and create the client to search. I believe that is why we no longer can connect to 127.0.0.1 through Telescope, therefore we need to change it to localhost. Can we confirm this is a legitimate fix? I am not too certain this was the cause.

**Comment by rclee91** [comment]
Changing createError to work with ElasticSearch seems to have fixed the problem. 
I haven't been able to get the crash anymore. 
We can probably close this for now and just keep an eye on it to see if it persists.

**Pull request closed without merging**
