### PR TITLE
[UI 2.0] Fixes1697 - New logo with a red dot

### LINKED ISSUE #1697: [UI 2.0] Add new logo with a red dot
**What would you like to be added**:
Add our new Logo with a red dot.

### PR DESCRIPTION
**Pull request by PedroFonsecaDEV**
## Issue This PR Addresses
Fixes #1697  

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Update our red dot log to our new logo. 
Screen Shot 2021-02-12 at 2 16 29 AM

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by foxviet** [comment]
@PedroFonsecaDEV where can I see this red dot?

**Comment by PedroFonsecaDEV** [comment]
> @PedroFonsecaDEV where can I see this red dot?

@foxviet 
You can open the netlify preview and wait until a new blogpost land and then check the icon on the top of the tab. 
But if you want to check the SVG file, you can pull the PR or copy the SVG code and paste it [here](https://jakearchibald.github.io/svgomg/)

**Review by humphd — DISMISSED** [review]
I love how it's a planet at the far end of the telescope :)

**Review by birtony — APPROVED** [review]

**Review by birtony — CHANGES_REQUESTED** [review]
I was too quick to approve. @PedroFonsecaDEV looks like you did not optimize this image
image
Please, run it by https://tinypng.com/

**Review by foxviet — DISMISSED** [review]
looks like a microphone to me

**Comment by birtony** [comment]
> I was too quick to approve. @PedroFonsecaDEV looks like you did not optimize this image
> image
> Please, run it by https://tinypng.com/

My bad, I must have confused this PR with something else

**Review by birtony — APPROVED** [review]

**Comment by PedroFonsecaDEV** [comment]
I'm going to rebase and then merge the PR.

**Pull request merged**
