### PR TITLE
Issue1225 - Reposition search button for search UI

### LINKED ISSUE #1225: Reposition search button for search UI
Our frontend kicks off searches every time you start typing.  I'd love to see us:

- add a button so it doesn't happen until I click or press 'enter'
- and/or debounce this keyboard event so it doesn't start happening until I finish typing

If you type something like, it will fire and re-fire the query on every letter.  That's bad UI, and it overloads the network and React.

### PR DESCRIPTION
**Pull request by strawberries73**
## Issue This PR Addresses
Fixes #1225 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
Moved search button down to the right of the search bar
image

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by strawberries73** [comment]
@jossiey  I figured out how I added cache.

**Comment by manekenpix** [comment]
I think you added the `public` folder inside of the front-end to this PR.

**Comment by strawberries73** [comment]
@manekenpix I have no idea how I put that there, but it is removed now.

**Review by Jasper-Mui — APPROVED** [review]
Looks good

**Review by humphd — APPROVED** [review]
This works well.

I found one small issue: we need to deal with the button overlapping longer search text input; but I'm going to file it as a follow-up so as to not block this further.

**Comment by humphd** [comment]
Filed #1476 on adornment overlap of input text.

**Pull request merged**
