### PR TITLE
Fix issue #339 improve CSS

### PR DESCRIPTION
**Pull request by aprilllllllll**
I push it to a different branch.
-Based on suggestions from issue #339
-Update styles for menu bar.
-Changed paddings for some elements.
-Changed font family for content.

### CODE REVIEW

**Comment by aprilllllllll** [comment]
I did those steps. Could you check, please?

**Comment by aprilllllllll** [comment]
David, I change the width. But the website on my computer is so weird.

**Comment by aprilllllllll** [comment]
https://imgur.com/AlNYQlD

**Comment by humphd** [comment]
Where did the content of those posts go?  I think you're trying to do too much in this PR, and it's breaking things.  Why not just fix things in 339?

**Comment by aprilllllllll** [comment]
not really. The only thing I touch is CSS.
Also, that's happened to the other person

**Comment by aprilllllllll** [comment]
sure thank you

**Pull request merged**
