### PR TITLE
Issue 1325

### LINKED ISSUE #1325: Load More Posts button overlaps with border of last pos
**What happened**:
image

Discovered while reviewing #1184 . Can confirm it happens in all mobile views

**What should have happened**:
Load More Posts button should look more elegant or at least not have the button overlap with the border of the post
**How to reproduce it (as precise as possible)**:

1. Open up dev console with f12 and switch to mobile view
2. Scroll to the very bottom

**Anything else we need to know?**:
With infinite scrolling being implemented, I have no idea if this fix will be necessary.

**Environment**:

- OS: Chrome
- Browser: Windows 10 Professional

### PR DESCRIPTION
**Pull request by jiyoungsin**
## Issue This PR Addresses

Fixes #1325

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

Devices in the range of xs and sm where rendered with an overlap. This issue fixes this overlap.

## Checklist

- [x] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by c3ho** [comment]
Can we get more information in the title

**Comment by humphd** [comment]
Screen Shot 2020-11-12 at 2 48 30 PM

Let's not merge master into your PR branches.  We rebase instead.

**Comment by humphd** [comment]
@jiyoungsin can you please clean this up, add proper title/desc, fix rebase issue, etc?  If not, please close it and do it properly when you have time vs. leaving it in this state.

**Comment by jiyoungsin** [comment]
I noticed some tests were failing. Thank you for the reminder. I will have this pr ready by the end of today.

**Comment by jiyoungsin** [comment]
Seems like I have committed two separate pull requests into one. I will have a new pull request in a few minutes.

**Comment by jiyoungsin** [comment]
This PR has been closed. If you would like you can check out the [pull request](https://github.com/jiyoungsin/telescope/tree/f131e8c2b4f64072cae53e020b9707a9ce73c34f).

**Pull request closed without merging**
