### PR TITLE
Issue 1956 - Add Avatar to the NavBar

### LINKED ISSUE #1956: Add Avatar in NavBar after login.
**What would you like to be added**:
After a user successfully logged we want to see the user avatar on the NavBar. 
Screen Shot 2021-03-16 at 9 04 56 AM

### PR DESCRIPTION
**Pull request by Meneguini**
## Issue This PR Addresses
This PR fixes #1956

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [X] **UI**: Change which improves UI

## Description

- Adds the `<TelescopeAvatar>` to the `<NavBar>`.
- Adds the logout functionality when the user clicks on the avatar.
- Adds the possibility of changing the `backgroundColor` and `color` of the `<TelescopeAvatar>`. 

## Checklist
desktop-navbar
desktop-navbar-darkTheme
mobile-navbar
mobile-navbar-darkTheme

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [X] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by Meneguini** [comment]
@PedroFonsecaDEV  @humphd @birtony @DukeManh @yuanLeeMidori

**Review by PedroFonsecaDEV — APPROVED** [review]
@Meneguini 
Thanks. Well done.
If you want to join us on slack would be nice.

**Comment by Meneguini** [comment]
> 
> 
> @Meneguini
> Thanks. Well done.
> If you want to join us on slack would be nice.

I have tried joining the slack channel, but it says I need to be invited.

**Comment by PedroFonsecaDEV** [comment]
> > @Meneguini
> > Thanks. Well done.
> > If you want to join us on slack would be nice.
> 
> I have tried joining the slack channel, but it says I need to be invited.

@humphd ^

**Comment by humphd** [comment]
@Meneguini email me your Seneca email and I'll send an invite for Slack.

**Review by humphd — APPROVED** [review]
I tested this on staging, and it's working well:

Screen Shot 2021-04-14 at 6 14 59 PM

Screen Shot 2021-04-14 at 6 13 32 PM

I'll get @DukeManh, @rjayroso, or someone else to do another review of the code, but this is looking really good.  Great job @Meneguini.

**Review by DukeManh — APPROVED** [review]

**Pull request merged**
