### PR TITLE
Fixes #2240: drop node-fetch in apis

### LINKED ISSUE #2240: Use Satellite's fetch() function and remove local deps for microservices
Now that #2135 is fixed, and v1.16.0 of Satellite is released, we can use `const { fetch }  = require('@senecacdot/satellite')` to get a `fetch()` function in our microservices.  Any of the services that are currently using `fetch()` or `got()` or the like to do client HTTP requests should switch to use this.

### PR DESCRIPTION
**Pull request by tuanthanh2067**
## Issue This PR Addresses
Fixes #2240 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [X] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

Drop all node-fetch to use fetch from satellite 

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by tuanthanh2067** [comment]
Hi I dropped all node-fetch from apis.

image

**Review by humphd — DISMISSED** [review]

**Review by HyperTHD — DISMISSED** [review]
Thanks for doing this! Checked each file, looks good to merge

**Comment by HyperTHD** [comment]
Just make sure you rebase this first @tuanthanh2067

**Comment by humphd** [comment]
@tuanthanh2067 please do:

```
git checkout master
git pull upstream master
git checkout issue-2240
git rebase master
git push origin issue-2240 -f
```

And then we can merge it.

**Review by humphd — APPROVED** [review]

**Pull request merged**
