### PR TITLE
Run a Satellite instance to provide healthcheck route

### LINKED ISSUE #3362: Healthcheck fails in parser container
**What happened**:

Healthcheck in parser container fails, I think it's because `parser` service doesn't start a web server like other services using `satellite` 
 so `/healthcheck` doesn't exist. https://github.com/Seneca-CDOT/telescope/blob/28a58e3ce0606a2b9e42130e7e4de1e77d170952/src/api/parser/Dockerfile#L30-L31

Parser should be added to `services` as well I think
https://github.com/Seneca-CDOT/telescope/blob/28a58e3ce0606a2b9e42130e7e4de1e77d170952/src/api/status/src/services.js#L11-L57

Though, the service is working 

**Environment**:

- OS: Windows 10
- Browser: Chrome

### PR DESCRIPTION
**Pull request by TueeNguyen**
## Issue This PR Addresses
Fixes #3362 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
- Run a Satellite instance to provide healthcheck route

image

## Steps to test the PR

- `pnpm install`
- `pnpm services:start`
- `docker ps`
- Check for `telescope_api_parser`'s status
## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — DISMISSED** [review]

**Review by tcvan0707 — DISMISSED** [review]

**Comment by tcvan0707** [comment]
LGTM @TueeNguyen !!

**Comment by TueeNguyen** [comment]
I think I will add parser to https://github.com/Seneca-CDOT/telescope/blob/master/src/api/status/src/services.js and then I'll ask for another round of reviews @tcvan0707

**Review by humphd — APPROVED** [review]
After this, can we rip out the backend telescope container?

**Comment by TueeNguyen** [comment]
I'm focusing on that issue now, hopefully a PR tonight or tomorrow

**Review by manekenpix — APPROVED** [review]

**Review by humphd — APPROVED** [review]

**Pull request merged**
