### PR TITLE
Make terminal scroll to bottom to display latest changes

### LINKED ISSUE #2815: Making build log terminal scroll to the bottom
**What would you like to be added**:

Whenever there's a build happening, the build log does update but it doesn't scroll down to the bottom to display the latest changes.
We can investigate this function 
https://github.com/Seneca-CDOT/telescope/blob/63f41451f07def7eca20521ea728d1c2ef5d81be/src/api/status/public/js/build-log/check-for-build.js#L31-L44

**Why would you like this to be added**:

For better experience!

### PR DESCRIPTION
**Pull request by TueeNguyen**
## Issue This PR Addresses
Fix #2815 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description
- Use `terminal.scrollToBottom()` to scroll to the bottom of the terminal to display new changes.

## Steps to test the PR
To run build log locally, change autodeploymentUrl in src\api\status\public\js\build-log\check-build-status.js
```js
const autodeploymentUrl = (path) => `//dev.telescope.cdot.systems/deploy${path}`;  
````
Allow all connectSrc in src\api\status\src\server.js
```
connectSrc: ["'self'", "*"]
```
Go to `http://localhost/v1/status/build`

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by Andrewnt219 — CHANGES_REQUESTED** [review]
Didn't know xterm has that method. Good job!

I'll approve it after you revert the two other files.

**Comment by TueeNguyen** [comment]
> Didn't know xterm has that method. Good job!
> 
> I'll approve it after you revert the two other files.

Thanks, I pretty much just Ctrl+F bottom in xterm's interface file

**Review by JerryHue — APPROVED** [review]

**Comment by Andrewnt219** [comment]
Whoops, trying out the new update branch on Github, but I accidentally create a merge commit on your PR. Can you rebase that @TueeNguyen?

**Comment by TueeNguyen** [comment]
Fixed and rebased!

**Review by Andrewnt219 — APPROVED** [review]
👍.

**Review by tpmai22 — APPROVED** [review]
LGTM !

**Review by JerryHue — APPROVED** [review]
Very concise!

**Pull request merged**
