### PR TITLE
Fix link to Environment Setup documentation

### PR DESCRIPTION
**Pull request by JackyTea**
Noticed that `Environment Setup documentation` link was pointing to a markdown file that no longer exists.

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [x] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [x] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by sirinoks — APPROVED** [review]

**Review by JiaHua-Zou — DISMISSED** [review]

**Review by TueeNguyen — DISMISSED** [review]
Thanks

**Review by cindyledev — CHANGES_REQUESTED** [review]
Hey Jacky!

Can you change the link to the relative link (../getting-started/environment-setup.md) instead of the (https://github.com/Seneca-CDOT/telescope/blob/master/src/docs/docs/getting-started/environment-setup.md)?

**Comment by TueeNguyen** [comment]
@cindyledev I was wondering the same thing since the old one has absolute path

**Comment by JackyTea** [comment]
> Contributor

Changes made.

**Review by cindyledev — APPROVED** [review]
Thanks! Welcome back to Telescope.

**Review by tpmai22 — APPROVED** [review]

**Comment by TueeNguyen** [comment]
Let's rebase this @JackyTea and we're good to go

**Pull request merged**
