### PR TITLE
Fix #1420 - site crash when no post found

### LINKED ISSUE #1420: Site CRASH: "load more posts" in EMPTY search result
When user try to search with keywords that returns no result, now it showing "load more posts" instead of showing something like "no result". When click on "load more posts" button, the web crash in ~20-30 secs.

This one maybe relate to https://github.com/Seneca-CDOT/telescope/issues/1415, or sth else.

### PR DESCRIPTION
**Pull request by DukeManh**
## Issue This PR Addresses
Fixes: #1420

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by humphd — APPROVED** [review]
Fantastic, nice work!

**Review by manekenpix — APPROVED** [review]

**Comment by humphd** [comment]
@DukeManh while you're hacking on this code, do you want to do another fix for me (new PR)?  When the page initially loads, we get a loading spinner before anything is typed:

https://telescope-lweq34q54.vercel.app/search

Let's not show anything at all until a search has been conducted.

**Comment by izhuravlev** [comment]
@DukeManh you already got 2 Approvals, so you can go ahead and rebase your PR, and after that, you can merge (or ping any of us and we will merge it for you)

**Comment by DukeManh** [comment]
> @DukeManh while you're hacking on this code, do you want to do another fix for me (new PR)? When the page initially loads, we get a loading spinner before anything is typed:
> 
> https://telescope-lweq34q54.vercel.app/search
> 
> Let's not show anything at all until a search has been conducted.
Sounds good. I'll make it render nothing when there's no search yet.

**Comment by DukeManh** [comment]
> @DukeManh you already got 2 Approvals, so you can go ahead and rebase your PR, and after that, you can merge (or ping any of us and we will merge it for you)

Can you merge it for me, I don't have write access to Telescope yet.

**Pull request merged**
