### PR TITLE
Don't log errors when articles are missing fields

### PR DESCRIPTION
**Pull request by humphd**
## Issue This PR Addresses

Part of #548

## Type of Change

- [x] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [ ] **UI**: Change which improves UI

## Description

This adds a new error type, `ArticleError`, which allows us to filter out a bunch of errors we get when an article is missing data that we need to create a post.

By fixing this, I've now dealt with 2/3rds of the errors we get when running normally.  I just have to deal with fatal network errors, which I'll do in a follow-up.

To test this, run the server like this:

```
LOG_LEVEL=info npm start
```

It will look like this, showing what happens as it processes each feed, downloading content (200) or using our cached version (304), etc:

```
[ 2020-01-28 20:57:56.162 ] INFO  (80339 on brightness.local): [HTTP 200 - OK] Feed has new content: http://haxbyte.wordpress.com/category/Open%20Source/feed/
[ 2020-01-28 20:57:56.258 ] INFO  (80337 on brightness.local): [HTTP 304 - Not Modified] Feed not downloaded: http://galewis.blogspot.com/feeds/posts/default
[ 2020-01-28 20:57:56.343 ] INFO  (80338 on brightness.local): [HTTP 304 - Not Modified] Feed not downloaded: http://jmpiltz.blogspot.com/feeds/posts/default
[ 2020-01-28 20:57:56.360 ] INFO  (80340 on brightness.local): [HTTP 304 - Not Modified] Feed not downloaded: http://joeysoddthoughts.blogspot.ca/feeds/posts/default/
[ 2020-01-28 20:57:56.418 ] INFO  (80338 on brightness.local): [HTTP 304 - Not Modified] Feed not downloaded: http://spo600ninawip.blogspot.com/feeds/posts/default/
[ 2020-01-28 20:57:56.487 ] INFO  (80340 on brightness.local): [HTTP 304 - Not Modified] Feed not downloaded: http://mercedes-oop344.blogspot.com/feeds/posts/default
[ 2020-01-28 20:57:56.501 ] INFO  (80339 on brightness.local): [HTTP 304 - Not Modified] Feed not downloaded: http://codingblub.blogspot.com/feeds/posts/default/
[ 2020-01-28 20:57:56.576 ] INFO  (80339 on brightness.local): [HTTP 304 - Not Modified] Feed not downloaded: https://marvinrsanchez.wordpress.com/feed/
[ 2020-01-28 20:57:56.612 ] INFO  (80337 on brightness.local): [HTTP 200 - OK] Feed has new content: http://odjahanpour.wordpress.com/category/spo600/feed
```

### CODE REVIEW

**Comment by c3ho** [comment]
image

Tested locally with your branch, I set LOG_LEVEL=info npm start in .env, I shouldn't be seeing these right?

**Comment by humphd** [comment]
@c3ho when you say `"I set LOG_LEVEL=info npm start in .env"`, how are you doing this?

There are 2 ways you can achieve this:

1. in your `.env` do `LOG_LEVEL=info`
1. on the command line, in order to start the app, override the variable doing `LOG_LEVEL=info npm start`.

I think you might be mixing 1 and 2.

**Comment by c3ho** [comment]
Tested locally, for some reason windows terminal doesn't allow me to set it that way. I actually set LOG_LEVEL=info and then ran npm start. Can confirm your PR works

**Comment by humphd** [comment]
Windows doesn't honour this way to overriding variables.  It's why we use [`cross-env`](https://www.npmjs.com/package/cross-env) in our npm scripts...because Windows :(

**Pull request merged**
