### PR TITLE
Simplify Search Front-End

### PR DESCRIPTION
**Pull request by AmasiaNalbandian**
## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [ ] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description
To be able to finish the [PR for search bar front-end](https://github.com/Seneca-CDOT/telescope/pull/3211), I need to simplify the search. The level of complexity was not required, so I simplified this functionality to be higher up from `SearchPage.tsx` and share across components more uniformly. 

## Steps to test the PR
1. `npm install`
2. `cp config/env.staging .env`
3. `npm run dev`
4. Try using the searchbar - should have the same functionality as previously, meaning nothing should have changed, only the method for submitting front-end changed. 

## Checklist

- [ ] **Quality**: This PR builds and passes our npm test and works locally
- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Comment by nguyenhung15913** [comment]
image
I would recommend to change background color when we hover the bar in dark mode. Everything else is working well

**Comment by DukeManh** [comment]
@HyperTHD, I think this is a regression from your PR https://github.com/Seneca-CDOT/telescope/pull/2046

**Review by HyperTHD — APPROVED** [review]
It's certainly unfortunate that you removed my beautiful provider that took some time for me to make and I really wished you asked me to explain how it works as I would've made some time for that. 

All I ask is that you make the advanced search shine brighter than ever before. Think you owe it to me to do that at least. Rest in Peace my friend :(

GTM btw

**Review by DukeManh — APPROVED** [review]

**Comment by AmasiaNalbandian** [comment]
> image I would recommend to change background color when we hover the bar in dark mode. Everything else is working well

@nguyenhung15913 Thanks for feedback - I'll try to address this in the [PR for UI](https://github.com/Seneca-CDOT/telescope/pull/3211).

**Pull request merged**
